### ISSUE TITLE
Issue for commit ' st/nine: Handle special LIT case' and workaround

### ISSUE THREAD

**Issue by rboxeur** [iXit/Mesa-3D#100]
There is currently an issue while trying to compile the current master of Mesa applying the latest patches for Gallium Nine.

To bypass this issue I had to do 
--------------------
vim src/gallium/drivers/nouveau/nv50/nv50_3ddefs.xml.h

+#define NV50_3D_BLEND_FACTOR_SRC_ALPHA                         0x00004302
+#define NV50_3D_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA               0x00004303
+#define NV50_3D_BLEND_FACTOR_DST_ALPHA                         0x00004304

#endif /* NV_3DDEFS_XML */
---------------------
vim  src/gallium/drivers/nouveau/nvc0/nvc0_3d.xml.h

+#define NVC0_2D_OPERATION_BLEND_PREMULT                         0x00000006

#endif /* NVC0_3D_XML */
---------------------

Else I got error below. To be honest I am not a developer. So perhaps a new review of the code should be helpful

libtool: compile:  gcc -DPACKAGE_NAME=\"Mesa\" -DPACKAGE_TARNAME=\"mesa\" -DPACKAGE_VERSION=\"10.6.0-devel\" "-DPACKAGE_STRING=\"Mesa 10.6.0-devel\"" "-DPACKAGE_BUGREPORT=\"https://bugs.freedesktop.org/enter_bug.cgi?product=Mesa\"" -DPACKAGE_URL=\"\" -DPACKAGE=\"mesa\" -DV
ERSION=\"10.6.0-devel\" -D_FILE_OFFSET_BITS=64 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\"
 -DYYTEXT_POINTER=1 -DHAVE___BUILTIN_BSWAP32=1 -DHAVE___BUILTIN_BSWAP64=1 -DHAVE___BUILTIN_CLZ=1 -DHAVE___BUILTIN_CLZLL=1 -DHAVE___BUILTIN_CTZ=1 -DHAVE___BUILTIN_EXPECT=1 -DHAVE___BUILTIN_FFS=1 -DHAVE___BUILTIN_FFSLL=1 -DHAVE___BUILTIN_POPCOUNT=1 -DHAVE___BUILTIN_POPCOUNTL
L=1 -DHAVE___BUILTIN_UNREACHABLE=1 -DHAVE_FUNC_ATTRIBUTE_FLATTEN=1 -DHAVE_FUNC_ATTRIBUTE_FORMAT=1 -DHAVE_FUNC_ATTRIBUTE_MALLOC=1 -DHAVE_FUNC_ATTRIBUTE_PACKED=1 -DHAVE_FUNC_ATTRIBUTE_UNUSED=1 -DHAVE_DLADDR=1 -DHAVE_CLOCK_GETTIME=1 -DHAVE_PTHREAD=1 -DHAVE_SHA1_IN_LIBNETTLE=1
 -I. -I./include -I../../../../src -I../../../../include -I../../../../src/gallium/include -I../../../../src/gallium/auxiliary -I../../../../src/gallium/drivers -I../../../../src/gallium/winsys -DUSE_EXTERNAL_DXTN_LIB=1 -D_GNU_SOURCE -DUSE_SSE41 -DDEBUG -DTEXTURE_FLOAT_ENA
BLED -DUSE_X86_ASM -DUSE_MMX_ASM -DUSE_3DNOW_ASM -DUSE_SSE_ASM -DHAVE_XLOCALE_H -DHAVE_STRTOF -DHAVE_DLOPEN -DHAVE_POSIX_MEMALIGN -DHAVE_LIBDRM -DGLX_USE_DRM -DHAVE_LIBUDEV -DGLX_INDIRECT_RENDERING -DGLX_DIRECT_RENDERING -DGLX_USE_TLS -DHAVE_ALIAS -DHAVE_DRI3 -DHAVE_MINCOR
E -DHAVE_LLVM=0x0307 -DLLVM_VERSION_PATCH=0 -fvisibility=hidden -I/usr/include/libdrm -I/usr/include/libdrm -Og -ggdb -g -gdwarf-2 -gstrict-dwarf -Wall -std=c99 -Werror=implicit-function-declaration -Werror=missing-prototypes -fno-strict-aliasing -fno-builtin-memcmp -MT nv
c0/nvc0_surface.lo -MD -MP -MF nvc0/.deps/nvc0_surface.Tpo -c nvc0/nvc0_surface.c  -fPIC -DPIC -o nvc0/.libs/nvc0_surface.o
nvc0/nvc0_surface.c: In function 'nvc0_blitctx_prepare_state':
nvc0/nvc0_surface.c:871:24: error: 'NV50_3D_BLEND_FACTOR_SRC_ALPHA' undeclared (first use in this function)
       PUSH_DATA (push, NV50_3D_BLEND_FACTOR_SRC_ALPHA); /* SRC_RGB */
                        ^
nvc0/nvc0_surface.c:871:24: note: each undeclared identifier is reported only once for each function it appears in
nvc0/nvc0_surface.c:872:24: error: 'NV50_3D_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA' undeclared (first use in this function)
       PUSH_DATA (push, NV50_3D_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA); /* DST_RGB */
                        ^
nvc0/nvc0_surface.c:876:24: error: 'NV50_3D_BLEND_FACTOR_DST_ALPHA' undeclared (first use in this function)
       PUSH_DATA (push, NV50_3D_BLEND_FACTOR_DST_ALPHA); /* DST_ALPHA */
                        ^
nvc0/nvc0_surface.c: In function 'nvc0_blit_eng2d':
nvc0/nvc0_surface.c:1284:24: error: 'NVC0_2D_OPERATION_BLEND_PREMULT' undeclared (first use in this function)
       PUSH_DATA (push, NVC0_2D_OPERATION_BLEND_PREMULT);
                        ^
Makefile:1199: recipe for target 'nvc0/nvc0_surface.lo' failed
make[3]: *** [nvc0/nvc0_surface.lo] Error 1
make[3]: *** Attente des tâches non terminées....
make[3]: Leaving directory '/opt/Builds/mesa_2015-03-27_v001/src/gallium/drivers/nouveau'
Makefile:569: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/opt/Builds/mesa_2015-03-27_v001/src/gallium'
Makefile:668: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/opt/Builds/mesa_2015-03-27_v001/src'
Makefile:608: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by sarnex** [comment]
Same compile error on on my PPA, fix was to revert 0979fd8e8a3e37921624a0c5aae1dd538a9a9e9c

**Comment by axeldavy** [comment]
bad commit removed
