### ISSUE TITLE
Saints Row 2 (Steam) missing menu text in Gallium Nine

### ISSUE THREAD

**Issue by CalcProgrammer1** [iXit/Mesa-3D#103]
Saints Row 2 appears to work correctly except none of the menu text or HUD shows up.  This is what shows for the main menu:

![screenshot from 2015-04-09 00 09 52](https://cloud.githubusercontent.com/assets/1051772/7060771/e156d28e-de4c-11e4-8f86-60c8fd75fd68.png)

If I hit Enter it goes into the game, but with no HUD:

![screenshot-saints row 2](https://cloud.githubusercontent.com/assets/1051772/7060774/002a9ee8-de4d-11e4-919d-d2fb8e405964.png)

If I hit Esc, the screen dims but still no menu text:

![screenshot-saints row 2-1](https://cloud.githubusercontent.com/assets/1051772/7060780/1b2abcc8-de4d-11e4-8183-c61a2da2b011.png)

**Comment by CalcProgrammer1** [comment]
I've confirmed the menu does show using wined3d (Nine disabled):

![screenshot-saints row 2-2](https://cloud.githubusercontent.com/assets/1051772/7060812/89c1935a-de4d-11e4-9c75-ceaf93548420.png)

**Comment by iiv3** [comment]
The SR2 menu sample from the FTP seems to work fine after https://github.com/iXit/Mesa-3D/commit/74be6b8995d0144965318256fb1ca8f13029ec99 fix.
