### ISSUE TITLE
Black cars in Flatout 2 with Nine

### ISSUE THREAD

**Issue by vitalif** [iXit/Mesa-3D#104]
Hi!
When Flatout 2 is started with Gallium-Nine, all cars are just black:
![flatout_black](https://cloud.githubusercontent.com/assets/945339/7132934/7e06fbca-e296-11e4-928e-724fc47b9177.png)
I've already written it in http://www.phoronix.com/forums/showthread.php?112137-53-Patches-Published-For-Gallium3D-s-Direct3D-9-Support/page5 - can you fix it please? :)
P.S: Nine is still great, thanks :) works even with DRI_PRIME intel+radeon :)

**Comment by axeldavy** [comment]
Is it on our ixit master branch ? or on mesa git master ?

**Comment by vitalif** [comment]
Not sure, what's now in oibaf "graphics-drivers" PPA? (mesa git?)
I can retest with oibaf "gallium-nine" PPA, but I have to rebuild it to disable "ilo" driver back (don't understand what's the point of replacing i965 with it, it's very buggy)

**Comment by axeldavy** [comment]
It's probably solved on our ixit master branch. The patches will be sent to mesa git master soon.

**Comment by vitalif** [comment]
Just tested again with mesa from oibaf "gallium-nine" ppa package dated 14 apr 2015, "checkout up to f65739cf3fa68db69fadf0fd7af529717621805c" although that revision isn't in current git probably due to some rebase...

The cars are still black :)

**Comment by vitalif** [comment]
Ran the source through diff - it's the same as your current git master. So yes, the bug reproduces with your git master version :)
(I'm using wine 1.7.33 with a slightly outdated patch... may it affect the bug?)

**Comment by axeldavy** [comment]
Ok, I don't know what the problem is.
Updating wine shouldn't change anything for this problem

I guess the problem will solve by itself when we get to fix a few different bugs

**Comment by vitalif** [comment]
Yes, just checked it with latest patched wine - it's all the same. So, I'll probably just wait for the fix to appear? :) or is there any additional detail that I could provide?

**Comment by axeldavy** [comment]
It can be so many things it's hard to debug.

Usually I would advise to do an apitrace, so that we can replay and debug.
However we are pretty busy these days, trying debug with apitrace takes too much time and has low success changes.
Thus I think you'd better wait a few months, and retry. If it's still there, tell again.

**Comment by axeldavy** [comment]
Is the bug still there with last ixit/Mesa-3D ?

**Comment by vitalif** [comment]
It was the same on a ~1 month old mesa + wine. I can recheck it with the very latest version in the evening. Do you think there's a chance it was fixed since that time? :)

**Comment by axeldavy** [comment]
We have quite some fixes on ixit/Mesa-3D, so it's well possible

**Comment by vitalif** [comment]
I've retested wine 1.7.55 with the latest ixit patch manually applied, unfortunately the bug is still there :-( also some visual effects are missing with nine, but that's of course a smaller issue.

**Comment by vitalif** [comment]
I'll now retry with the latest mesa patch

**Comment by vitalif** [comment]
Retried with the latest mesa from oibaf ppa, the bug still reproduces.
It is worth trying to rebuild mesa from your repo?

**Comment by axeldavy** [comment]
no idea how up to date oibaf is, but he is unlikely using our repo.

As our repo has several months of fixes, that's worth it to test it.

**Comment by vitalif** [comment]
Ok, I've just tested a version from your current master branch... the bug is still there

**Comment by axeldavy** [comment]
Is it fixed now ?

**Comment by vitalif** [comment]
Yes it's OK with the latest versions!
