### ISSUE TITLE
Text corruption in The Repopulation

### ISSUE THREAD

**Issue by Altosk** [iXit/Mesa-3D#108]
I know its an alpha stage game. Screenshot below. It works fine with wined3d. Tested with state_rework, and state_rework2. I didn't test master yet. 
 
http://i.imgur.com/y69VbWU.png

**Comment by Altosk** [comment]
tested master still there.

**Comment by axeldavy** [comment]
Wine has specific rules on what alignment should the stride have, depending on the type of resource.
We do have only general rules. I guess here the problem is that the game assumes a specific stride. We should try implement the same than Wine.

**Comment by Altosk** [comment]
just tested with novueau and the text is fine. this might be a radeonsi bug that is showing up in d3d9.

**Comment by Altosk** [comment]
After seeing the #149, maybe this is related so here is a log
https://www.sendspace.com/file/86fku5

**Comment by Altosk** [comment]
this game had to switch game engines and most likely wont have this bug closing
