### ISSUE TITLE
nine_shader.c:2683:sm1_parse_instruction: Assertion `!insn->predicated && "TODO: predicated instructions"' failed.

### ISSUE THREAD

**Issue by Bitiquinho** [iXit/Mesa-3D#11]
Compiled both wine and mesa (without DRI3) from your git, enabling debug information according to the wiki. I can run Steam and verify it is linking to libd3dadapter.so, but every game I try (Steam or non Steam) crashes instantly. Without the "UseNative" registry key set to 1 all runs fine. Here I have a notebook with integrated HD 4200 and discrete HD 5650M graphics cards.

That's the debug information for one of my tests (Tomb Raider Anniversary Edition). Pretty much the same for other games and for the integrated card:

$ export LD_LIBRARY_PATH=/opt/mesa-d3d9/lib32:$LD_LIBRARY_PATH
$ export LIBGL_DRIVERS_PATH=/opt/mesa-d3d9/lib32/xorg/modules/dri
$ export WINEDEBUG=+d3dadapter,+d3d9,-dbghelp_dwarf
$ export NINE_DEBUG=true
$ DRI_PRIME=1 WINEPREFIX=~/.wine_tra/ /opt/wine-d3dadapter/bin/wine tra.exe 
fixme:ole:CoInitializeSecurity ((nil),-1,(nil),(nil),0,3,(nil),0,(nil)) - stub!
fixme:gameux:GameExplorerImpl_VerifyAccess (0x124b60, L"C:\\Program Files\\Tomb Raider - Anniversary\\tra.exe", 0xe8f354)
trace:d3d9:Direct3DCreate9 sdk_version 0x20.
trace:d3dadapter:has_d3dadapter Got DRI2 version 1.4
trace:d3dadapter:has_d3dadapter Got XFixes version 5.0
fixme:win:EnumDisplayDevicesW ((null),0,0xe8ef24,0x00000000), stub!
trace:d3dadapter:dri2_create_adapter9 Associated `r600' with fd 13 opened from `/dev/dri/card0'
trace:d3dadapter:dri2_create_adapter9 Created ID3DAdapter9 with fd 13
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",0,0xe8ef24,0x00000000), stub!
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",1,0xe8ef24,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),1,0xe8ef24,0x00000000), stub!
trace:d3d9:d3dadapter9_GetAdapterIdentifier DeviceName overriden: \\.\DISPLAY1
trace:d3d9:d3dadapter9_GetAdapterIdentifier DeviceId:VendorId overridden: 9712:1002
trace:d3d9:d3dadapter9_GetAdapterIdentifier DeviceName overriden: \\.\DISPLAY1
trace:d3d9:d3dadapter9_GetAdapterIdentifier DeviceId:VendorId overridden: 9712:1002
trace:d3d9:d3dadapter9_GetAdapterModeCount 32 modes.
fixme:system:SystemParametersInfoW Unimplemented action: 59 (SPI_SETSTICKYKEYS)
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",0,0xe8eec4,0x00000000), stub!
trace:d3dadapter:dri2_create_present_group Returning 0x12dd70
trace:d3d9:d3dadapter9_AddRef 0x124fa0 increasing refcount to 2.
trace:d3dadapter:DRI2PresentGroup_AddRef 0x12dd70 increasing refcount to 2.
fixme:d3dadapter:DRI2PresentGroup_GetMultiheadCount (0x12dd70), stub!
fixme:d3dadapter:DRI2PresentGroup_GetMultiheadCount (0x12dd70), stub!
trace:d3dadapter:DRI2Present_AddRef 0x12e090 increasing refcount to 2.
trace:d3dadapter:DRI2Present_AddRef 0x12e090 increasing refcount to 3.
trace:d3dadapter:DRI2Present_Release 0x12e090 decreasing refcount to 2.
trace:d3dadapter:DRI2PresentGroup_Release 0x12dd70 decreasing refcount to 1.
nine:device9.c:414: NineDevice9_EvictManagedResources STUB!
nine:device9.c:414: NineDevice9_EvictManagedResources STUB!
nine:device9.c:414: NineDevice9_EvictManagedResources STUB!
nine:device9.c:414: NineDevice9_EvictManagedResources STUB!
nine:device9.c:414: NineDevice9_EvictManagedResources STUB!
nine:device9.c:414: NineDevice9_EvictManagedResources STUB!
nine:nine_shader.c:2057: NineTranslateInstruction_TEXREG2AR STUB!
nine_shader.c:2683:sm1_parse_instruction: Assertion `!insn->predicated && "TODO: predicated instructions"' failed.
wine: Unhandled exception 0x80000003 in thread 9 at address 0x7d1b2d1b (thread 0009), starting debugger...

**Comment by axeldavy** [comment]
No gallium driver seems to implement predication.
As the bug is likely solved with the ps 1.X instruction fix, I close the bug
