### ISSUE TITLE
Final Fantasy 14 crashes on start

### ISSUE THREAD

**Issue by Altosk** [iXit/Mesa-3D#110]
I'm crashing when starting the game with  err:d3dadapter:DRI3Present_new No focus HWND specified for presentation backend. Normally the game start windowed and then switches to full screen. Works fine in CSMT. Only tested via CSMT due to bugs via normal wined3d related to the UI flickering bug.

**Comment by Altosk** [comment]
heres an apitrace of the crash https://www.sendspace.com/file/7q58us

**Comment by axeldavy** [comment]
The apitrace seems broken. It is much too short, and replays without error

**Comment by Altosk** [comment]
trace:d3dadapter:DRI3Present_AddRef 0x206f58 increasing refcount to 2.
nine:swapchain9:ctor: This=0x7a27b1d8 pDevice=0x7a3cd080 pPresent=0x206f58 pCTX=0x7972ba10 hFocusWindow=0x200c0
trace:d3dadapter:DRI3Present_AddRef 0x206f58 increasing refcount to 3.
nine:swapchain9:Resize: This=0x7a27b1d8 pParams=0x33f9e4
nine:swapchain9:Resize: pParams(0x33f9e4):
BackBufferWidth: 1
BackBufferHeight: 1
BackBufferFormat: D3DFMT_X8R8G8B8
BackBufferCount: 1
MultiSampleType: 0
MultiSampleQuality: 0
SwapEffect: 1
hDeviceWindow: 0x200c0
Windowed: 1
EnableAutoDepthStencil: 0
AutoDepthStencilFormat: D3DFMT_UNKNOWN
Flags: 
FullScreen_RefreshRateInHz: 0
PresentationInterval: 80000000
nine:surface9:ctor: This=0x7a27baf0 pDevice=0x7a3cd080 pResource=0x7a27b890 Level=0 Layer=0 pDesc=0x33f470
nine:resource9:ctor: This=0x7a27baf0 pParams=0x33f3d8 initResource=0x7a27b890 Allocate=0 Type=1 Pool=0 Usage=1
nine:swapchain9:Resize: Failed to create RT surface.
nine:swapchain9:dtor: This=0x7a27b1d8
trace:d3dadapter:DRI3Present_Release 0x206f58 decreasing refcount to 2.
trace:d3dadapter:DRI3Present_Release 0x206f58 decreasing refcount to 1.
nine:device9:dtor: This=0x7a3cd080
wine: Unhandled page fault on write access to 0x00000008 at address 0x7cf15bc8 (thread 0062), starting debugger...

maybe this will help here

**Comment by Altosk** [comment]
does nine support d3dfmt_rawz or d3dfmt_df24?

**Comment by axeldavy** [comment]
None

**Comment by axeldavy** [comment]
rawz is inferior to INTZ, which we support.

We support df16, but not df24, because df24 implies we support a feature used for msaa we don't support (we support other better msaa features)

**Comment by Altosk** [comment]
okay then
should createadditionalswapchain error out with this IDirect3DDevice9::CreateAdditionalSwapChain(this = 0x7a996a48, pPresentationParameters = ?, pSwapChain = ?) = D3DERR_INVALIDCALL

wined3d creates the additional swapchain where nine doesnt 

IDirect3DDevice9::CreateAdditionalSwapChain(this = 0x209358, pPresentationParameters = [{BackBufferWidth = 1280, BackBufferHeight = 720, BackBufferFormat = D3DFMT_X8R8G8B8, BackBufferCount = 1, MultiSampleType = D3DMULTISAMPLE_NONE, MultiSampleQuality = 0, SwapEffect = D3DSWAPEFFECT_DISCARD, hDeviceWindow = NULL, Windowed = TRUE, EnableAutoDepthStencil = FALSE, AutoDepthStencilFormat = D3DFMT_UNKNOWN, Flags = 0x0, FullScreen_RefreshRateInHz = 0, PresentationInterval = D3DPRESENT_INTERVAL_IMMEDIATE}], pSwapChain = [0x4d03d28]) = D3D_OK

**Comment by axeldavy** [comment]
strange it refuses to create it

**Comment by Altosk** [comment]
so i think the problems lies within NineSwapChain9_Resize after following the logs error nine:swapchain9:Resize: Failed to create RT surface. I think it might to with this line hr = ID3DPresent_SetPresentParameters(This->present, pParams, This->mode);.
this is as far as i got.

**Comment by axeldavy** [comment]
The params must have something strange. Could you print it ?

**Comment by axeldavy** [comment]
I mean I'd like you to show the content of pParams just before that failing call.

If you were debugging with gcc, that's easy, else forgive about it.

**Comment by axeldavy** [comment]
Ok I think I know what's going on. But I don't know how to fix this.
I'll talk to other devs.

**Comment by Altosk** [comment]
Is it possible for a game to use invaild parameters when creating additional swapchains? i ask because in the wine d3d trace its using the same present parameters as the first swapchain. Should createadditionalswapchains have a fallback to set the parameters to the first swapchain?

I ask this because I forced the original parameters to the additional swapchain being created and the game kinda started and proceed to freeze my computer when switching to fullscreen.

**Comment by Altosk** [comment]
i'm getting a assertion on a shader 
/var/tmp/portage/media-libs/mesa-9999/work/mesa-9999/src/gallium/state_trackers/nine/nine_shader.c:875: tx_src_param: Assertion `!param->rel' failed.

**Comment by axeldavy** [comment]
Can you give use the last thousand lines of the log produces (you need mesa with debug build) NINE_DEBUG=all ?

It seems you hit a feature we haven't implemented (due to the fact we never found any user so far)

**Comment by Altosk** [comment]
https://www.sendspace.com/file/7nj4w0
heres the full log before I go out tonight

**Comment by axeldavy** [comment]
whoa, these shaders are really using a lot of textures.

There is actually two features we haven't implemented there.
I don't see the first one on that part of the log, but I see the second.

The first one is the hardest to implement, but the second should be ok.
If you could get a working apitrace with wine, it would help test if the implementation works.

**Comment by Altosk** [comment]
I got both nine apitrace and wine d3d apitrace

**Comment by axeldavy** [comment]
I see only a short nine one on this bug report

**Comment by Altosk** [comment]
I got a longer one now with my hack job on the first issue

**Comment by axeldavy** [comment]
I need one that goes further than the crash area, thus why it can't be taken with nine.

**Comment by Altosk** [comment]
https://www.sendspace.com/file/kyp4iu

**Comment by axeldavy** [comment]
OK, looks like some incompatibility between the wine and nine backend (it happens with other traces, it is due to different strides, etc). It crashes on nine.

I'll have to ask you to try when I implement the feature, as I have no way to test.

**Comment by Altosk** [comment]
it crashes because of the invaild params(i think) of createadditionalswapchain, what i did here was set the params to the first swapchain so both had the same present params which seem to fix that issue temporary. i added this line to createadditionalswapchain : *pPresentationParameters = tmplt->params; which got me to the assertion.

**Comment by Altosk** [comment]
should this line be like this in wine ?     hr = DRI3Present_new(gdi_display, This->present_backends[0]->devname, pPresentationParameters, **0**, (struct DRI3Present **)ppPresent);
that zero in bold is what i'm question

**Comment by axeldavy** [comment]
Yeah, we don't implement the right behaviour there.

The documentation states than when you see NULL as the window in the params, whether it's an additional swapchain or the main one, then you use the focus window (given at device creation).

The problem we have is that the Present backend will behave wrong if we map two swapchains to the same X windows. To minimize the risks of that happening, I kept the fallback to NULL instead of the focus window.

According to your comments, I guess there is no collision in your case, and the main device doesn't use the focus window.

I guess we have to implement the fallback to the focus window in wine, and put checks to catch the case with overlap.

**Comment by Altosk** [comment]
http://pastebin.com/W0LwrHA0 <-mesa
http://pastebin.com/0Utg1hkP <- wine
This is what I came up with for the createadditionalswapchain(s) issue. I have no clue if its the "right" way to do it but I want to give it a shot. I havent tested any other games to see if it cause a problem yet but the game starts up like it does on windows going from a window to fullscreen then it hits the assertion.

**Comment by Altosk** [comment]
my attempt at fixing is wrong. Instead I removed the checks that call the invalid error in wine and I haven't had any problems so far.

**Comment by axeldavy** [comment]
Fix issue fixed, second issue duplicate of https://github.com/iXit/Mesa-3D/issues/49

**Comment by Altosk** [comment]
this is fixed on ixit game starts with debug builds closing
