### ISSUE TITLE
Windows don't appear, only outline

### ISSUE THREAD

**Issue by jaimejimbo** [iXit/Mesa-3D#112]
I'm trying to run some games with wine (wine 1.7.43 with gallium patches). I'm using this ppa:
https://launchpad.net/~oibaf/+archive/ubuntu/gallium-nine/

lsb_release -a
> Distributor ID:	LinuxMint
> Description:	Linux Mint 17.1 Rebecca
> Release:	17.1
> Codename:	rebecca

uname -r
> 4.0.4-040004-lowlatency

Glxinfo:
> Mesa 10.7.0-devel (git-065978d 2015-05-29 trusty-sarnex-ppa)

wine output
Running wine- Steam.exe (Working directory : /home/jaime/.PlayOnLinux/wineprefix/SteamGAL9/drive_c/Program Files/Steam)
err:winedevice:ServiceMain driver L"Null" failed to load
fixme:ole:RemUnknown_QueryInterface No interface for iid {00000019-0000-0000-c000-000000000046}
fixme:ver:GetCurrentPackageId (0x32e490 (nil)): stub
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: cannot open shared object file: No such file or directory
fixme:advapi:EventRegister {47a9201e-73b0-42ce-9821-7e134361bc6f}, 0x3f0069c0, 0x3f040cf0, 0x3f040ce8
fixme:advapi:EventRegister {58a9201e-73b0-42ce-9821-7e134361bc70}, 0x3f0069c0, 0x3f040d28, 0x3f040d20
fixme:advapi:EventRegister {3fa9201e-73b0-43fe-9821-7e145359bc6f}, 0x3f0069c0, 0x3f040cb8, 0x3f040cb0
fixme:advapi:EventRegister {1432afee-73b0-42ce-9821-7e134361b433}, 0x3f0069c0, 0x3f040d60, 0x3f040d58
fixme:advapi:EventRegister {4372afee-73b0-42ce-9821-7e134361b519}, 0x3f0069c0, 0x3f040d98, 0x3f040d90
fixme:process:SetProcessShutdownParameters (00000100, 00000000): partial stub.
fixme:imm:ImmGetOpenStatus (0x1e8780): semi-stub
fixme:ver:GetCurrentPackageId (0x32e360 (nil)): stub
fixme:ole:RemUnknown_QueryInterface No interface for iid {00000019-0000-0000-c000-000000000046}
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: cannot open shared object file: No such file or directory
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
fixme:heap:RtlSetHeapInformation 0x110000 0 0x33fd0c 4 stub
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
fixme:ver:GetCurrentPackageId (0x30e5e0 (nil)): stub
fixme:process:SetProcessDEPPolicy (3): stub
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:imm:ImmDisableTextFrameService Stub
fixme:thread:GetThreadPreferredUILanguages 56, 0x33f7a4, (nil) 0x33f7a8
fixme:wbemprox:wbem_locator_ConnectServer unsupported flags
fixme:wbemprox:client_security_SetBlanket 0x7ce8e6e8, 0x10195578, 10, 0, (null), 3, 3, (nil), 0x00000000
fixme:wbemprox:client_security_Release 0x7ce8e6e8
fixme:hnetcfg:fw_apps_get__NewEnum 0x10239b10, 0x4c3e4cc
fixme:hnetcfg:fw_app_put_ProcessImageFileName 0x10239b10, L"C:\\Program Files\\Steam\\steam.exe"
fixme:hnetcfg:fw_app_put_Name 0x10239b10, L"Steam"
fixme:hnetcfg:fw_app_put_Enabled 0x10239b10, -1
fixme:hnetcfg:fw_apps_Add 0x102281f8, 0x10239b10
err:ole:CoGetClassObject class {e2b3c97f-6ae1-41ac-817a-f6f92166d7dd} not registered
err:ole:CoGetClassObject no class object {e2b3c97f-6ae1-41ac-817a-f6f92166d7dd} could be created for context 0x1
fixme:wbemprox:wbem_locator_ConnectServer unsupported flags
fixme:wbemprox:client_security_SetBlanket 0x7ce8e6e8, 0x1029b3d8, 10, 0, (null), 3, 3, (nil), 0x00000000
fixme:wbemprox:client_security_Release 0x7ce8e6e8
fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
fixme:wbemprox:enum_class_object_Next timeout not supported
fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
fixme:wbemprox:enum_class_object_Next timeout not supported
fixme:wbemprox:enum_class_object_Next timeout not supported
fixme:wbemprox:enum_class_object_Next timeout not supported
fixme:wbemprox:enum_class_object_Next timeout not supported
fixme:winsock:WSALookupServiceBeginW (0x33f690 0x00000ff0 0x33f6cc) Stub!
[0530/100840:ERROR:network_change_notifier_win.cc(173)] WSALookupServiceBegin failed with: 8
fixme:iphlpapi:NotifyAddrChange (Handle 0x33f7d8, overlapped 0x158630): stub
fixme:ver:GetCurrentPackageId (0x195e604 (nil)): stub
fixme:win:RegisterDeviceNotificationW (hwnd=0x100aa, filter=0x33f7e4,flags=0x00000000) returns a fake device notification handle!
fixme:win:RegisterDeviceNotificationW (hwnd=0x100aa, filter=0x33f7e4,flags=0x00000000) returns a fake device notification handle!
fixme:win:EnumDisplayDevicesW ((null),0,0x33f0bc,0x00000000), stub!
fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_HANDLE_INFORMATION
fixme:iphlpapi:NotifyAddrChange (Handle 0x1ec03cc, overlapped 0x1ec03d0): stub
fixme:win:RegisterDeviceNotificationA (hwnd=0x100b8, filter=0x55fe4c4,flags=0x00000004) returns a fake device notification handle!
fixme:ver:GetCurrentPackageId (0x33fba8 (nil)): stub
err:ole:CoGetClassObject class {77f10cf0-3db5-4966-b520-b7c54fd35ed6} not registered
err:ole:CoGetClassObject no class object {77f10cf0-3db5-4966-b520-b7c54fd35ed6} could be created for context 0x1
fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
fixme:imm:ImmReleaseContext (0x100ba, 0x10127db8): stub
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:WinHttpDetectAutoProxyConfigUrl discovery via DHCP not supported
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:win:RegisterDeviceNotificationA (hwnd=0x100ce, filter=0x32e4e4,flags=0x00000004) returns a fake device notification handle!
err:x11drv:DRI3CheckExtension DRI3 advertised, but not working
err:d3dadapter:has_d3dadapter Unable to query DRI3. Trying DRI2 fallback (slower performance).
fixme:win:EnumDisplayDevicesW ((null),0,0x32dac8,0x00000000), stub!
fixme:thread:start_thread Started native thread 00000052
fixme:thread:start_thread Started native thread 00000054
fixme:thread:start_thread Started native thread 00000053
fixme:thread:start_thread Started native thread 00000055
nine:adapter9:ctor: Your card is at the limit of Gallium Nine requirements. Some games may run into issues because requirements are too tight
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",0,0x32dac8,0x00000000), stub!
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",1,0x32dac8,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),1,0x32dac8,0x00000000), stub!
fixme:d3d9:d3dadapter9_new [1;32m
Native Direct3D 9 is active.
For more information visit https://wiki.ixit.cz/d3d9[0m
fixme:win:EnumDisplayDevicesW ((null),0,0x32db68,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),1,0x32db68,0x00000000), stub!
fixme:win:RegisterDeviceNotificationW (hwnd=0x10128, filter=0x66fe8fc,flags=0x00000000) returns a fake device notification handle!
fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
fixme:win:RegisterDeviceNotificationW (hwnd=0x20128, filter=0x64ce8fc,flags=0x00000000) returns a fake device notification handle!
fixme:advapi:RegisterTraceGuidsW (0x100a78c0, 0x121b2b38, {3dada31d-19ef-4dc1-b345-037927193422}, 1, 0x121433dc, (null), (null), 0x121b2b50): stub
fixme:advapi:RegisterTraceGuidsW   register trace class {00000000-0000-0000-0000-000000000000}
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: cannot open shared object file: No such file or directory
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
fixme:heap:RtlSetHeapInformation 0x110000 0 0x33fd0c 4 stub
fixme:win:EnumDisplayDevicesW ((null),0,0x32e568,0x00000000), stub!
nine:adapter9:ctor: Your card is at the limit of Gallium Nine requirements. Some games may run into issues because requirements are too tight
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",0,0x32e568,0x00000000), stub!
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",1,0x32e568,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),1,0x32e568,0x00000000), stub!
fixme:d3d9:d3dadapter9_new [1;32m
Native Direct3D 9 is active.
For more information visit https://wiki.ixit.cz/d3d9[0m
fixme:thread:start_thread Started native thread 00000063
fixme:thread:start_thread Started native thread 00000065
fixme:thread:start_thread Started native thread 00000064
fixme:thread:start_thread Started native thread 00000066
fixme:process:SetProcessDEPPolicy (3): stub
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:advapi:RegisterTraceGuidsW (0x100a78c0, 0x121b2b38, {3dada31d-19ef-4dc1-b345-037927193422}, 1, 0x121433dc, (null), (null), 0x121b2b50): stub
fixme:advapi:RegisterTraceGuidsW   register trace class {00000000-0000-0000-0000-000000000000}
fixme:gdi:GdiInitializeLanguagePack stub
fixme:heap:RtlSetHeapInformation 0x110000 0 0x33f3ec 4 stub
[0530/100845:ERROR:renderer_main.cc(212)] Running without renderer sandbox
fixme:ver:GetCurrentPackageId (0x258e9c8 (nil)): stub
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: cannot open shared object file: No such file or directory
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
fixme:heap:RtlSetHeapInformation 0x110000 0 0x33fd0c 4 stub
fixme:process:SetProcessDEPPolicy (3): stub
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:advapi:RegisterTraceGuidsW (0x100a78c0, 0x121b2b38, {3dada31d-19ef-4dc1-b345-037927193422}, 1, 0x121433dc, (null), (null), 0x121b2b50): stub
fixme:advapi:RegisterTraceGuidsW   register trace class {00000000-0000-0000-0000-000000000000}
fixme:gdi:GdiInitializeLanguagePack stub
fixme:heap:RtlSetHeapInformation 0x110000 0 0x33f3ec 4 stub
[0530/100845:ERROR:renderer_main.cc(212)] Running without renderer sandbox
fixme:ver:GetCurrentPackageId (0x258e9c8 (nil)): stub
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
err:ole:RevokeDragDrop invalid hwnd 0x10158
fixme:advapi:UnregisterTraceGuids deadbeef: stub
[0530/100847:WARNING:raw_channel_win.cc(314)] ReadFile: Pipe not connected. (0xE9)
[0530/100847:ERROR:channel.cc(315)] RawChannel read error (unknown)
fixme:gameux:GameExplorerImpl_VerifyAccess (0x108f5978, L"C:\\Program Files\\Steam\\steamapps\\common\\Skyrim\\TESV.exe", 0x32eaa0)
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:advapi:EventRegister {47a9201e-73b0-42ce-9821-7e134361bc6f}, 0x3f0069c0, 0x3f040cf0, 0x3f040ce8
fixme:advapi:EventRegister {58a9201e-73b0-42ce-9821-7e134361bc70}, 0x3f0069c0, 0x3f040d28, 0x3f040d20
fixme:advapi:EventRegister {3fa9201e-73b0-43fe-9821-7e145359bc6f}, 0x3f0069c0, 0x3f040cb8, 0x3f040cb0
fixme:advapi:EventRegister {1432afee-73b0-42ce-9821-7e134361b433}, 0x3f0069c0, 0x3f040d60, 0x3f040d58
fixme:advapi:EventRegister {4372afee-73b0-42ce-9821-7e134361b519}, 0x3f0069c0, 0x3f040d98, 0x3f040d90
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: cannot open shared object file: No such file or directory
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33f6d0 1 C) semi-stub
err:x11drv:DRI3CheckExtension DRI3 advertised, but not working
err:d3dadapter:has_d3dadapter Unable to query DRI3. Trying DRI2 fallback (slower performance).
fixme:win:EnumDisplayDevicesW ((null),0,0x33f808,0x00000000), stub!
fixme:thread:start_thread Started native thread 00000080
fixme:thread:start_thread Started native thread 00000081
fixme:thread:start_thread Started native thread 00000083
nine:adapter9:ctor: Your card is at the limit of Gallium Nine requirements. Some games may run into issues because requirements are too tight
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",0,0x33f808,0x00000000), stub!
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",1,0x33f808,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),1,0x33f808,0x00000000), stub!
fixme:d3d9:d3dadapter9_new [1;32m
Native Direct3D 9 is active.
For more information visit https://wiki.ixit.cz/d3d9[0m
fixme:thread:start_thread Started native thread 00000082
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
Setting breakpad minidump AppID = 72850
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198083649497 [API loaded no]
fixme:advapi:EventRegister {47a9201e-73b0-42ce-9821-7e134361bc6f}, 0x3f0069c0, 0x3f040cf0, 0x3f040ce8
fixme:advapi:EventRegister {58a9201e-73b0-42ce-9821-7e134361bc70}, 0x3f0069c0, 0x3f040d28, 0x3f040d20
fixme:advapi:EventRegister {3fa9201e-73b0-43fe-9821-7e145359bc6f}, 0x3f0069c0, 0x3f040cb8, 0x3f040cb0
fixme:advapi:EventRegister {1432afee-73b0-42ce-9821-7e134361b433}, 0x3f0069c0, 0x3f040d60, 0x3f040d58
fixme:advapi:EventRegister {4372afee-73b0-42ce-9821-7e134361b519}, 0x3f0069c0, 0x3f040d98, 0x3f040d90
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: cannot open shared object file: No such file or directory
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventUnregister deadbeef: stub
fixme:advapi:EventRegister {47a9201e-73b0-42ce-9821-7e134361bc6f}, 0x3f0069c0, 0x3f040cf0, 0x3f040ce8
fixme:advapi:EventRegister {58a9201e-73b0-42ce-9821-7e134361bc70}, 0x3f0069c0, 0x3f040d28, 0x3f040d20
fixme:advapi:EventRegister {3fa9201e-73b0-43fe-9821-7e145359bc6f}, 0x3f0069c0, 0x3f040cb8, 0x3f040cb0
fixme:advapi:EventRegister {1432afee-73b0-42ce-9821-7e134361b433}, 0x3f0069c0, 0x3f040d60, 0x3f040d58
fixme:advapi:EventRegister {4372afee-73b0-42ce-9821-7e134361b519}, 0x3f0069c0, 0x3f040d98, 0x3f040d90
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: cannot open shared object file: No such file or directory
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
err:ole:CoInitializeEx Attempt to change threading model of this apartment from multi-threaded to apartment threaded
err:ole:CoInitializeEx Attempt to change threading model of this apartment from multi-threaded to apartment threaded
err:ole:CoInitializeEx Attempt to change threading model of this apartment from multi-threaded to apartment threaded
err:ole:CoInitializeEx Attempt to change threading model of this apartment from multi-threaded to apartment threaded
err:ole:CoInitializeEx Attempt to change threading model of this apartment from multi-threaded to apartment threaded
err:ole:CoInitializeEx Attempt to change threading model of this apartment from multi-threaded to apartment threaded
err:ole:CoInitializeEx Attempt to change threading model of this apartment from multi-threaded to apartment threaded
err:x11drv:DRI3CheckExtension DRI3 advertised, but not working
err:d3dadapter:has_d3dadapter Unable to query DRI3. Trying DRI2 fallback (slower performance).
fixme:win:EnumDisplayDevicesW ((null),0,0x33f3d8,0x00000000), stub!
fixme:thread:start_thread Started native thread 00000069
fixme:thread:start_thread Started native thread 0000006a
fixme:thread:start_thread Started native thread 0000006e
fixme:thread:start_thread Started native thread 00000066
nine:adapter9:ctor: Your card is at the limit of Gallium Nine requirements. Some games may run into issues because requirements are too tight
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",0,0x33f3d8,0x00000000), stub!
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",1,0x33f3d8,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),1,0x33f3d8,0x00000000), stub!
fixme:d3d9:d3dadapter9_new [1;32m
Native Direct3D 9 is active.
For more information visit https://wiki.ixit.cz/d3d9[0m
fixme:win:EnumDisplayDevicesW ((null),0,0x33f418,0x00000000), stub!
fixme:thread:start_thread Started native thread 0000006f
fixme:thread:start_thread Started native thread 00000063
nine:adapter9:ctor: Your card is at the limit of Gallium Nine requirements. Some games may run into issues because requirements are too tight
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",0,0x33f418,0x00000000), stub!
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",1,0x33f418,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),1,0x33f418,0x00000000), stub!
fixme:d3d9:d3dadapter9_new [1;32m
Native Direct3D 9 is active.
For more information visit https://wiki.ixit.cz/d3d9[0m
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",0,0x33f328,0x00000000), stub!
fixme:thread:start_thread Started native thread 0000007a
fixme:thread:start_thread Started native thread 00000078
fixme:d3dadapter:DRI3PresentGroup_GetMultiheadCount (0x1d3450), stub!
fixme:d3dadapter:DRI3PresentGroup_GetMultiheadCount (0x1d3450), stub!
fixme:d3d9:D3DPERF_SetOptions (0x1) : stub
m Files\Steam\steamapps\common\Skyrim\TESV.exe: ../../../../../../src/gallium/drivers/ilo/shader/toy_tgsi.c:658: aos_SCS: Assertion `!"SCS untested"' failed.
fixme:system:SystemParametersInfoW Unknown action: 116

**Comment by axeldavy** [comment]
Ilo driver (the intel gallium driver) isn't developped enough and you'll find almost nothing working with it.

Sorry, not our bug.
