### ISSUE TITLE
World of Warcraft 1.12.1

### ISSUE THREAD

**Issue by Cardridge** [iXit/Mesa-3D#114]
I'm running the above mentioned game (and patch) with this project. The performance is outstanding compared to running without d3d9 but there's lightning bug in certain view angles.

Please note that TBC (World of Warcraft 2.4.3) works fine.

Here's a comparison:

normal ([video](http://webmshare.com/play/dXbLd))

![2015-07-05-040018_800x600_scrot](https://cloud.githubusercontent.com/assets/13181774/8510002/be1be59e-22ca-11e5-9c40-6ae6cd078044.png)

d3d9 ([video](http://webmshare.com/play/qoYDg))

![2015-07-05-040213_800x600_scrot](https://cloud.githubusercontent.com/assets/13181774/8510004/ccb6a698-22ca-11e5-8424-d7c7336ad775.png)

**Comment by sarnex** [comment]
If you have time can you compile mesa with --enable-debug and post the log of NINE_DEBUG=all wine game.exe.

Also an apitrace might be useful.

**Comment by Cardridge** [comment]
Is there anything specific I need to do ingame for the debug log to be useful? Or should I just pan around as in the example?

**Comment by sarnex** [comment]
Just make sure the graphical errors are present in game.

An apitrace is likely more useful, see info at the bottom of this page
https://wiki.ixit.cz/d3d9_debugging

**Comment by Cardridge** [comment]
When running the application with apitrace I'm getting the following:
```warning: ..\lib\wrappers\d3d9.dll was never used: application probably does not use this API```

Command used to run:
```wine bin/apitrace.exe trace -a d3d9 -v ~/games/World\ of\ Warcraft\ 1.12/WoW.exe```

Not quite sure what do with this.

**Comment by sarnex** [comment]
@Cardridge You need to set WINEDLLOVERRIDES.
Example
````
WINEDLLOVERRIDES='Z:\home\jfonseca\projects\apitrace\build\mingw32\wrappers\d3d9.dll=n'
````

**Comment by Cardridge** [comment]
I did that as well, no dice.

**Comment by iiv3** [comment]
Here is one trick that I use:
Run `winecfg` go into `Labrary` tab and add new override library for `d3d9` as `(native, builtin)`.
Make sure that you don't have native (windows) `d3d9.dll` inside `c:\windows\system32`. A lot of native game installers run DirectX redistributive that could end up installing that file there. By default wine won't use it, but the above command changes that. If you get crashes related to `GDI32` it means you have native windows `d3d9.dll` somewhere in system path.

If everything is OK, you can create apitrace just by putting the apitrace wrapper `d3d9.dll` in the same folder as the game `.exe` and then running the game.

Just don't forget to remove the `d3d9.dll` when you are over. It would continue to make traces until it fills all your free space.
Remove the library override from `winecfg` too.

**Comment by axeldavy** [comment]
With what version of Mesa was the game run ? With Which card ?

Perhaps try again on current git.

**Comment by Altosk** [comment]
This is fixed with latest git. All lighting effects look to be right to me
