### ISSUE TITLE
GTA-San Adreas regression

### ISSUE THREAD

**Issue by iiv3** [iXit/Mesa-3D#117]
The bug causes all people in game to look like cut out silhouettes. It happens only with iXit Mesa3D. The freedesktop Mesa3D 10.6.2 release is fine.

After performing bisect, I located the first bad commit to be: iXit/Mesa-3D@18c154d1f5c6a72289ae5da92fe00af239c45ad5
```
commit 18c154d1f5c6a72289ae5da92fe00af239c45ad5
Author: Axel Davy <axel.davy@ens.fr>
Date:   Fri May 8 19:50:15 2015 +0200

    st/nine: Advertise Fog flags
```

The commit seems to enable functionality that have been added in previous commits. I was able to disable the bug by eliminating just two of the flags: 
`D3DPRASTERCAPS_FOGTABLE` and `D3DPRASTERCAPS_FOGVERTEX` .

Unfortunately I cannot create an d3d9 apitrace - with nine the gameplay bugs the video (i can still hear the game). When using the opengl wrapper the game hits assertion at startup. The situation is similar under real windows7 where it also crashes at startup.

I can provide log made with NINE_DEBUG=all, it's 220MB raw and 700KB compressed.

**Comment by iiv3** [comment]
By advice from Axel Davy, I redid the bisect, this time adding both flags manually at each iteration, in order to locate what really causes the regression. The result was narrowed down to:
```
commit 51f08e8e92b9b36f352a66d3663b50e69a290a27
Author: Axel Davy <axel.davy@ens.fr>
Date:   Fri May 8 19:26:20 2015 +0200
    st/nine: Fix fixed function fog support
```

**Comment by axeldavy** [comment]
The video shows that every character is fully fogged.
Which means the fog scalar always get the same value (fully fogged)

The game uses vertex fog
What would be interesting is to change it to pixel fog see if the problem is solved (it likely will be, just to check)

for that go in nine_ff.c

You'll see one usage of D3DRS_FOGTABLEMODE and one usage of D3DRS_FOGVERTEXMODE

rename D3DRS_FOGTABLEMODE  to D3DRS_FOGVERTEXMODE
and D3DRS_FOGVERTEXMODE to D3DRS_FOGTABLEMODE
and tell if this worked.

**Comment by axeldavy** [comment]
we found the bug, game bug. advertising wfog like everyone out there makes the bug have different non buggy path

**Comment by iiv3** [comment]
D3D provides with 2 ways to implement fog through fixed functions - Vertex Fog and Pixel Fog.

Vertex Fog is faster but uglier. It calculates fog parameters for each vertex or the 3D object. Then during the pixel calculation the fog is calculated by interpolation between fog parameters.
If the game uses vertex shader, then the fixed function is disabled and the vertex shader should calculate fog parameters too. GTA-SA uses two different vertex shaders, one for the world and one for the people. It seems the later is given wrong input by the game and produces bogus parameters.

The workaround for the game includes advertising WFOG flag. When it is present the game picks the second method for calculating fog - Pixel Fog. In that mode fog parameters are calculated for each pixel. The calculation takes into account the exact pixel depth, from the depth buffer.

The workaround have been amended in https://github.com/iXit/Mesa-3D/commit/6667be544ca55784df27511e05d3580cbb59c9f6

**Comment by iiv3** [comment]
I just want to add, that when apitrace got fixed, I did remove the WFOG flag and took a trace. Then tried replaying it under wined3d and native win7. They all looked the same as Nine.

**Comment by axeldavy** [comment]
ok, so was really game buggy path
