### ISSUE TITLE
Background scene not shown in Tropico 4

### ISSUE THREAD

**Issue by karolherbst** [iXit/Mesa-3D#118]
In tropico 4 there is a scene in the background inside the main menu, which isn't shown on native d3d9.

using nouveau-git on GTX 770M

**Comment by axeldavy** [comment]
Is it fixed now ?

**Comment by karolherbst** [comment]
I don't know, tropci 4 crashes now :/

**Comment by axeldavy** [comment]
What is the status now ?

**Comment by iiv3** [comment]
It works flawlessly on my HD5670 Evergreen Redwood (r600 driver).

I've uploaded an apitrace in `fixed/issue.118.Tropico4.no.background.in.menu/` .

Please test on RadeonSI and Nouveau.

**Comment by siro20** [comment]
Works on nouveau NVD9 and radeonsi TAHITI.
