### ISSUE TITLE
FEAR visual glitches

### ISSUE THREAD

**Issue by iiv3** [iXit/Mesa-3D#119]
I have noticed two image glitches when running FEAR.

1. Transparent weapons.
The bug seems similar to [this winehq bug](https://bugs.winehq.org/show_bug.cgi?id=27145) .  Axel Davy also found some workarounds, related to the depth buffer.

2. Mangled bodies of game characters.
When testing with some options, I found that `R600_DEBUG=nosb` makes the problem go away. This indicates that the problem is most likely caused by miscompilation of a vertex shader.
I've tried to locate the vertex shader linked to body drawing (using helixmod). I believe it is [this one](https://gist.github.com/iiv3/8098b4a01cec0acfad82#file-fear-vertex-shader-173-suspected-to-trigger-r600compiler-bug).

 After making some logs with `NINE_DEBUG=shader R600_DEBUG=vs` , I think I might have located the shader in TGSI and R600 bytecode forms:
[#100](https://gist.github.com/iiv3/427e9d31f4a680231457#file-fear-vertex-shader-173-suspected-to-trigger-r600compiler-bug-tgsi-and-r600gpucode)

 However, disabling SB optimizations for the above shader, fixes only the body mangling, the shadow is still wrong. After some more tests I've located the shader that bugs it:
[#131](https://gist.github.com/iiv3/83fdab9e81576e3797f9#file-fear-vertex-shader-131-causes-buggy-shadow-with-r600-sb)

I've already uploaded `FEAR1.mangled.bodies.d3d9.trace` file that reproduces both issues with apitrace.
My video card is Radeon HD5670 (Redwood).

**Comment by axeldavy** [comment]
Was R600 bug. Fix on mailing list.

**Comment by iiv3** [comment]
1. Transparent weapons are fixed by https://github.com/iXit/Mesa-3D/commit/ceaaa17b8a14b9b5379aba3dae5d90ab388c9ad5

2. Body mangling is fixed by [r600g: Fix handling of TGSI_OPCODE_ARR with SB](http://lists.freedesktop.org/archives/mesa-dev/2015-August/091629.html)
The patch is pending inclusion into Mesa3D.
