### ISSUE TITLE
d3d9-patched mesa built with -mfpmath=sse gcc flag on x86 causes d3d9-patched wine to segfault

### ISSUE THREAD

**Issue by xpue** [iXit/Mesa-3D#120]
While native x86 binaries work on this mesa without segfaults.

https://bugs.freedesktop.org/show_bug.cgi?id=91039

**Comment by axeldavy** [comment]
I don't know exactly how we can fix that properly

**Comment by iiv3** [comment]
SSE requires alignment of 16 bytes. When code is compiled with SSE support the stack is aligned to 16 bytes by default. However windows executable can miss-align the stack.

One way to fix that is by having `gcc -mstackrealign` that would pad the stack on every function entry. This is not only slower, in most of the time it is unnecessary.

The preferable solution is to align the stack at API entry points.
 It's done by `__attribute__((force_align_arg_pointer))` that is placed in front of the API function.
That attribute is already used in Mesa llvmpipe code as `PIPE_ALIGN_STACK`.

However the real question is... why the pointer is not aligned by Wine?
It seems that Wine redefines `__stdcall` to include that attribute. Then wined3d uses it to define `WINE_GLAPI` that is applied for all API functions.

**Comment by axeldavy** [comment]
Fixed on ixit/master.
