### ISSUE TITLE
"Prince of Persia - Sands of Time" visual problems

### ISSUE THREAD

**Issue by iiv3** [iXit/Mesa-3D#122]
1. Intro is not visible and menu screen doesn't have any text or cursor.
2. When in game, character bodies are horribly mangled.
![pop1sof_mangle](https://cloud.githubusercontent.com/assets/4492960/9290739/79f28ac4-43a6-11e5-9e63-447d0e7f54ff.png)

None of the bugs are present in wine opengl wrapper.
The second bug looks similar to #119 , however the fix for it does not seem to affect this bug.

I've uploaded `POP.SandsOfTime.mangled.bodies_missing.menu.d3d9.trace.xz`.
My videocard is Radeon HD5670 (Redwood).

**Comment by sarnex** [comment]
Trace shows the same bug on HD7950 Tahiti.

**Comment by iiv3** [comment]
This commit https://github.com/iXit/Mesa-3D/commit/f4c1a1841563f13345cef7970c862d543288ab43 fixes the first problem. Now Intro and Menu are visible.

The second problem (from the picture) remains.

**Comment by iiv3** [comment]
The following patch fixes the second issue
```
--- a/src/gallium/state_trackers/nine/nine_shader.c
+++ b/src/gallium/state_trackers/nine/nine_shader.c
@@ -2716,4 +2716,3 @@ struct sm1_op_info inst_table[] =
     _OPI(NOP, NOP, V(0,0), V(3,0), V(0,0), V(3,0), 0, 0, NULL), /* 0 */
-    _OPI(MOV, MOV, V(0,0), V(1,1), V(0,0), V(0,0), 1, 1, SPECIAL(MOV_vs1x)),
-    _OPI(MOV, MOV, V(2,0), V(3,0), V(0,0), V(3,0), 1, 1, NULL),
+    _OPI(MOV, MOV, V(0,0), V(3,0), V(0,0), V(3,0), 1, 1, NULL),
     _OPI(ADD, ADD, V(0,0), V(3,0), V(0,0), V(3,0), 1, 2, NULL), /* 2 */
```

It effectively disables this function:
```
DECL_SPECIAL(MOV_vs1x)
{
    if (tx->insn.dst[0].file == D3DSPR_ADDR) {
        /* Implementation note: We don't write directly
         * to the addr register, but to an intermediate
         * float register.
         * Contrary to the doc, when writing to ADDR here,
         * the rounding is not to nearest, but to lowest
         * (wine test).
         * Since we use ARR next, substract 0.5. */
        ureg_SUB(tx->ureg,
                 tx_dst_param(tx, &tx->insn.dst[0]),
                 tx_src_param(tx, &tx->insn.src[0]),
                 ureg_imm1f(tx->ureg, 0.5f));
        return D3D_OK;
    }
    return NineTranslateInstruction_Generic(tx);
}
```

**Comment by siro20** [comment]
Good catch ! It fixes Tomb Raider: Legend too. It's using vs1_1 instead of FF when using "Next Gen Content".
![bildschirmfoto_2015-11-11_08-20-16](https://cloud.githubusercontent.com/assets/2340747/11086023/3b1b15b4-884d-11e5-8e24-12fcf3f01c08.png)
![bildschirmfoto_2015-11-11_08-15-55](https://cloud.githubusercontent.com/assets/2340747/11086027/3e5316be-884d-11e5-9022-24ee6ddac0c7.png)

**Comment by iiv3** [comment]
The last bug have been fixed by https://github.com/iXit/Mesa-3D/commit/5f3fb2a489d138bff1701f2aedc60157c2444397 .
