### ISSUE TITLE
Prince of Persia 4 visual issue

### ISSUE THREAD

**Issue by iiv3** [iXit/Mesa-3D#127]
For the most part the game have no visible glitches. However there are some rectangular shadows that have nothing to cast them. These are only visible with Nine and are gone with wine opengl wrapper.

I've uploaded `PrinceOfPersia4.square_shadows.d3d9.trace`.
My video card is Radeon HD5670 (Redwood).

![pop4_shadows](https://cloud.githubusercontent.com/assets/4492960/9360587/b0dac154-469f-11e5-9d14-326b39b11f8f.png)

**Comment by axeldavy** [comment]
Likely some blending thing.

Try again after reverting Add Render state validation layer up to  Add validation to SetSamplerState

**Comment by iiv3** [comment]
I should have mentioned that same issue is visible when using Freedesktop Mesa 10.6.1 . These commits seem too new to be present in it.

**Comment by sarnex** [comment]
Bug does not occur on radeonsi, only r600.

**Comment by axeldavy** [comment]
Not our bug then

**Comment by iiv3** [comment]
Please, don't close bugs that are not fixed.

You DO fork Mesa3D so this makes it your bug, TOO.

**Comment by axeldavy** [comment]
LOL

**Comment by iiv3** [comment]
I've used Helixmod again to locate the shaders that are related to this bug. Under it's numbering they are vertex shader 25 (crc: 0x6656B983)  and pixel shader 35 (crc: 0x5E3848B0). When they are disabled, same rectangular areas become solid black, even with wine opengl wrapper. (aka these areas are always handled by these shaders).

Then I've created a log using `NINE_DEBUG=shader NINE_TGSI_DUMP=1` and located these shaders in it: Here is the relevant part containing both shaders in D3D and TGSI form:
[vs25 ps35](https://gist.github.com/iiv3/64b83eb28e47c96706d1#file-pop4_nine_shader_tgsi_vs25_ps35) 

What I find really puzzling is the sudden appearance of extremely huge constant in the TGSI.

Vertex Shader
```
VS3.0
DEF c16 { 0.000031 1.000000 0.007874 -1.000000 }
DEF c17 { 0.001000 0.000000 0.000000 0.000000 }
DEF c18 { 11.000000 0.000000 -1.000000 1.000000 }
```
```
IMM[0] FLT32 {    0.0000,     1.0000,     0.0079,    -1.0000}
IMM[1] FLT32 {    0.0010,     0.0000, 340282346638528859811704183484516925440.0000,    -1.0000}
IMM[2] FLT32 {   11.0000,     0.0000,    -1.0000,     1.0000}
```

Pixel Shader:
```
PS3.0
DEF c26 { 0.816497 0.577350 0.000000 0.000244 }
DEF c27 { 0.707107 -0.408248 0.577350 -0.707107 }
DEF c28 { 0.000000 2.000000 -1.000000 0.005000 }
DEF c29 { 0.000000 0.000977 0.000244 8.000000 }
DEF c30 { 4096.000000 1024.000000 0.400000 0.000000 }
```
```
IMM[0] FLT32 {    0.8165,     0.5774,     0.0000,     0.0002}
IMM[1] FLT32 {    0.7071,    -0.4082,     0.5774,    -0.7071}
IMM[2] FLT32 {    0.0000,     2.0000,    -1.0000,     0.0050}
IMM[3] FLT32 {    0.0000,     0.0010,     0.0002,     8.0000}
IMM[4] FLT32 { 4096.0000,  1024.0000,     0.4000,     0.0000}
IMM[5] FLT32 {340282346638528859811704183484516925440.0000,     0.0000,     0.0000,     0.0000}
```

**Comment by iiv3** [comment]
This bug seems to be duplicate of https://github.com/iXit/Mesa-3D/issues/126
It is resolved by same patch.
