### ISSUE TITLE
Unigine Valley glitches

### ISSUE THREAD

**Issue by xpue** [iXit/Mesa-3D#129]
With disabled nine it runs without glitches. Video card is nvidia gts450, libdrm, mesa, wine are installed from git with your patches. d3dcompiler_43.dll from windows is used, without it valley fails. CFLAGS are "-O2", arch is x86. XZipped log with NINE_DEBUG=all NINE_FF_DUMP=1 NINE_TGSI_DUMP=1 TGSI_PRINT_SANITY=1 is here (unpacked it takes 1gigabyte): http://drive.google.com/file/d/0Bw8YULLJvu4gX2xYUEpkX0VZcms/view

![1](http://drive.google.com/uc?export=view&id=0Bw8YULLJvu4gbzcwOWZWc2YyZzQ)
![2](http://drive.google.com/uc?export=view&id=0Bw8YULLJvu4gUVIzb0NkS3NTcVk)
![3](http://drive.google.com/uc?export=view&id=0Bw8YULLJvu4gYU1xV1ZlVlBObGc)

**Comment by iiv3** [comment]
There are two code paths for uploading shader constants. The Nvidia one is known to have an issue (with Mafia2), so it would be useful if you try the ATI one. Instructions here https://github.com/iXit/Mesa-3D/issues/128#issuecomment-132781501

**Comment by xpue** [comment]
Yes, this fixes blue trees and flying polygons, however textures on some boulders and fallen tree trunks are still covered in black pixels, you can click on screenshots for full size.

**Comment by siro20** [comment]
I see black pixels on the fallen tree trunks, too.
I'm using R600, so this is not related to Nouveau.

**Comment by siro20** [comment]
*Update* it looks like one of the many tree textures contains uninitialized memory.

**Comment by axeldavy** [comment]
windows is known to clear textures to 0 before passing to the app (for security).
We don't (idea is that it is easier to catch uninitialized memory issues). Perhaps the apps rely on that behaviour ?

**Comment by siro20** [comment]
Writing 0 (black) into the textures on creation makes a huge difference for this application. The trees look more natural, the blended "noise" isn't visible any more.

**Comment by axeldavy** [comment]
If this fixes it (ie the expected look), then I will accept a patch to implement the behaviour.

**Comment by axeldavy** [comment]
The fix landed.

**Comment by siro20** [comment]
What's the fix ? It's still visible in current git.

**Comment by axeldavy** [comment]
The bug was quite hard to find but... WHAT !!!!

Fix will land shortly
