### ISSUE TITLE
R600 asserts in tgsi_cmp/make_src_for_op3

### ISSUE THREAD

**Issue by iiv3** [iXit/Mesa-3D#131]
While testing the traces in the ftp, I found four of them that are triggering the same assert.
```r600_shader.c:4891: tgsi_make_src_for_op3: Assertion `temp!=0' failed.```

The files in question are `BorderlandsPreSequel.trace.tar.xz`, `FullMojo.tar.xz`, `WorldOfTanks.tar.xz`, `Prototype2_apitrace5.trace.7z`. 
This happens only when using Nine acceleration, they seem to play fine on wined3d opengl wrapper.

I've run them with `R600_DEBUG=vs,ps` and extracted the last shader. The long contains only the TGSI code, because the assert triggers at the initial compilation. You can take a look of the shaders (and backtraces) here:
[_TGSI_CMP/op3 assert_](https://gist.github.com/iiv3/374794d015d60dc2f0fc#file-nine_tgsi_cmp_assert_x4)

I'm going to report this bug to freedesktop mesa, but I'd like first to confirm that Nine have created valid TGSI code.

My videocard is HD5670 (Redwoord).

**Comment by axeldavy** [comment]
Looks like it happens when the CMP instruction has input with absolute value.
Probably with some more conditions.

**Comment by iiv3** [comment]
This bug have been fixed by ["r600g: Fix assert in tgsi_cmp"](http://cgit.freedesktop.org/mesa/mesa/commit/?id=50932268aad0cc21511f370793e77c76e038bd06).
