### ISSUE TITLE
Heroes of the Storm visual issue

### ISSUE THREAD

**Issue by odh0** [iXit/Mesa-3D#132]
The last mesa patch series introduced a regression, causing visual glitches in the hero selection screen.
Some of the heros don't seem to cause any issues. However when selecting different heros the colors in the corners are sometimes wrong.

I did a bisect and found out that reverting this commit 
(http://cgit.freedesktop.org/mesa/mesa/commit/?id=98f786b270b3e55a1e8a7bdc8182e436702748a2) fixes the issue.
![heroes1](https://cloud.githubusercontent.com/assets/14013215/9543021/b754b454-4d75-11e5-8dea-844dac13b4ba.jpg)

**Comment by axeldavy** [comment]
With which card ?

**Comment by axeldavy** [comment]
are you 100% sure it's this commit and not the one after for example?
the one faster is
"st/nine: Use CSO cache for sampler views"

**Comment by odh0** [comment]
This is my first bug report. I forgot to mention.
My graphics Card is an AMD R9 280x

glxinfo:

OpenGL vendor string: X.Org
OpenGL renderer string: Gallium 0.4 on AMD TAHITI (DRM 2.42.0, LLVM 3.8.0)
OpenGL core profile version string: 4.1 (Core Profile) Mesa 11.1.0-devel (git-ce23272)
OpenGL core profile shading language version string: 4.10
OpenGL core profile context flags: (none)

When i build mainline mesa the glitch occurs. After git reverting this commit it disappears.
I don't know why the error happens sorry. Could i provide any more information?

**Comment by axeldavy** [comment]
This is really strange bug, the patch looks harmless.

What is your gcc version and compile flags ?

Do you double confirm only reverting this patch solves your issue ?

**Comment by odh0** [comment]
gcc version:
gcc (GCC) 5.1.1 20150618 (Red Hat 5.1.1-4)

I took the same compile flags as fedora. But mine were slightly different. I had -O3 and fedora has -O2. Building mesa with -O2 works and -O3 doesn't. I didn't know that this could cause errors.
Now it seems to be working without reverting the commit.
Sorry if this has caused any trouble. I think the issue can be closed?

**Comment by axeldavy** [comment]
Yes, also gcc 5.2 solves some issues with gcc 5.0 and 5.1
