### ISSUE TITLE
R600: fast clear delayed by 2 frames

### ISSUE THREAD

**Issue by siro20** [iXit/Mesa-3D#138]
This issue is observed on R600.
It is not present in Wine, using D3D_ALWAYS_SOFTWARE=1 or by using slow clear path.
I'm clearing the color buffer with {black, red, green, blue} and draw a white quad.

Fastclear: the background is delayed by 2 Present calls
![d3d_broken_fastclear](https://cloud.githubusercontent.com/assets/2340747/9652079/46d393f6-5218-11e5-91fe-773b13c47a31.png)

Slow clear: the background has the correct color
![d3d_broken_slowclear](https://cloud.githubusercontent.com/assets/2340747/9652083/4c164200-5218-11e5-97dd-5660aeebddf8.png)

**Comment by axeldavy** [comment]
Do you have a test program ?

**Comment by siro20** [comment]
static void test_r600_fastclear(void)
	{
		IDirect3DDevice9 *device;
		IDirect3D9 *d3d;
		HWND window;
		HRESULT hr;
		int i;
	
		static const D3DMATRIX view_mat =
		{{{
			2.0f / 10.0f, 0.0f,         0.0f, 0.0f,
			0.0f,         2.0f / 10.0f, 0.0f, 0.0f,
			0.0f,         0.0f,         1.0f, 0.0f,
			0.0f,         0.0f,         0.0f, 1.0f
		}}};
	
		struct
		{
			struct vec3 position;
		} vertex_data[4] =
				{{-1.0f, -1.0f, 0.0f},
				{-1.0f,  1.0f, 0.0f},
				{ 1.0f, -1.0f, 0.0f},
				{ 1.0f,  1.0f, 0.0f}};
	
		window = CreateWindowA("static", "d3d9_test", WS_OVERLAPPEDWINDOW | WS_VISIBLE,
				0, 0, 640, 480, NULL, NULL, NULL, NULL);
		d3d = Direct3DCreate9(D3D_SDK_VERSION);
		ok(!!d3d, "Failed to create a D3D object.\n");
		if (!(device = create_device(d3d, window, window, TRUE)))
		{
			skip("Failed to create a D3D device, skipping tests.\n");
			goto done;
		}
	
		hr = IDirect3DDevice9_SetRenderState(device, D3DRS_LIGHTING, FALSE);
		ok(hr == D3D_OK, "IDirect3DDevice9_SetRenderState returned %08x\n", hr);
	
		hr = IDirect3DDevice9_SetTransform(device, D3DTS_VIEW, &view_mat);
		ok(hr == D3D_OK, "IDirect3DDevice9_SetTransform returned %08x\n", hr);
	
		unsigned colors[4] = {0xff000000, 0xffff0000, 0xff00ff00, 0xff0000ff};
	
		for (i = 0; i < 4; ++i) {
			hr = IDirect3DDevice9_Clear(device, 0, NULL, D3DCLEAR_TARGET, colors[i], 0.0, 0);
			ok(SUCCEEDED(hr), "Failed to clear %08x\n", hr);
	
			hr = IDirect3DDevice9_BeginScene(device);
			ok(SUCCEEDED(hr), "Failed to begin scene, hr %#x.\n", hr);
	
			hr = IDirect3DDevice9_SetFVF(device, D3DFVF_XYZB3);
			ok(SUCCEEDED(hr), "Failed to set FVF, hr %#x.\n", hr);
	
			hr = IDirect3DDevice9_DrawPrimitiveUP(device, D3DPT_TRIANGLESTRIP, 2, vertex_data, 3 * sizeof(float));
			ok(SUCCEEDED(hr), "Failed to draw, hr %#x.\n", hr);
	
			hr = IDirect3DDevice9_EndScene(device);
			ok(SUCCEEDED(hr), "Failed to end scene, hr %#x.\n", hr);
	
			hr = IDirect3DDevice9_Present(device, NULL, NULL, NULL, NULL);
			ok(hr == D3D_OK, "IDirect3DDevice9_Present failed with %08x\n", hr);
			Sleep(1000);
		}
	
		IDirect3DDevice9_Release(device);
	
	done:
		IDirect3D9_Release(d3d);
		DestroyWindow(window);
	}

**Comment by siro20** [comment]
R600_DEBUG=notiling fixes this issue

**Comment by iiv3** [comment]
This bug have been fixed by https://github.com/iXit/Mesa-3D/commit/6bd76845266389a32c92331c8e0919baec6a17ef .
