### ISSUE TITLE
Nine crashes on connecting with recent Blizzard games using nouveau

### ISSUE THREAD

**Issue by Altosk** [iXit/Mesa-3D#140]
Diablo III , starcraft 2, and heroes of the storm are the games that I tested. The video card I tested with is a gtx760. I can make traces later if needed.

**Comment by iiv3** [comment]
Please, check if crash happens with Nine disabled.

Traces would be most useful. Make them with Nine disabled. Then make sure that they crash Nine in same way as the games.

What version of Mesa and Wine are you running?
If you compile them on your own, would you recompile then with the debug options given in [_d3d9 debugging_](https://wiki.ixit.cz/d3d9_debugging).
If would be helpful if you provide backtrace of the crash (wine does one automatically) with debug symbols.

**Comment by axeldavy** [comment]
tizbac has similar crashes, and are solved with the null vertex buffer patches (https://github.com/iXit/Mesa-3D/commit/c40194d0ac625160f382ada69e9444f6c3025b9c)

I remember having written a patch to make nine behaviour more happy to nouveau relative to that point, but It seems to have disappeared.

**Comment by Altosk** [comment]
null vertex buffer patch worked

**Comment by okias** [comment]
@axeldavy do we need to fix it on our side, or can we ask imirkin to accept patch?

**Comment by axeldavy** [comment]
It is supposed to be solved by:
https://github.com/iXit/Mesa-3D/commit/4acbf420d1101bd32e8f23acadff5fe6c6fa9b26

But this was long ago, it's strange the bug is still noticed

**Comment by Altosk** [comment]
this is fixed upstream now
