### ISSUE TITLE
Several games and battle.net app render incorrectly with recent patch

### ISSUE THREAD

**Issue by Altosk** [iXit/Mesa-3D#143]
latest git has rendering issues in several game that worked fine before. The games that are effected are Beyond good and evil -instead of the grey fog the screen is black making impossible to play-, Fallout : new vegas - rendering of the lights on character create screen turn to boxes-, and Fable III - UI flicking/missing plus shadows would glitch at times. The battle.net app would render with a grey fog.
I was able to fix these bugs by reverting st/nine: Fix clear for multisample mismatch depth-stencil patch.

**Comment by axeldavy** [comment]
I have fallout new vegas. Could you describe me the fastest way to reproduce the bug ?

**Comment by Altosk** [comment]
start a new game and when you get the point where you can choose your gender if you look at the lights where it says gender/face/hair/etc. looks like a big block instead of a redish light.

**Comment by axeldavy** [comment]
Ok. With aliasing off it works ok, but the bug is triggered when I enable it

**Comment by axeldavy** [comment]
should be fixed on master

**Comment by Altosk** [comment]
all games check out okay playing like they should. in case of Beyond good and evil its back to the grey fog issue

**Comment by axeldavy** [comment]
a trace of the game will be helpful to reproduce the grey fog bug.

I close this bug related to depth buffer clear.
