### ISSUE TITLE
Ultra Street Fighter 4 incorrect rendering

### ISSUE THREAD

**Issue by mikejuni** [iXit/Mesa-3D#144]
I'd like to report an incorrect rendering under Ultra Street Fighter 4 (Steam version). Since upgrading to Mesa 11 (I'm using Arch Linux) and updating to latest mesa-git repository USF4 main menu and other transition screens are not rendering properly.

It used to work with Mesa 10. Pure Mesa 11.0.2 in Arch simply crashed out.

I can be pretty sure that it is not an issue on wine side since I tried both the latest wine-staging-d3dadapter and PlayOnLinux (which offers wine 1.7.44-d3dadapter).

Other than the main menu and those transition screens gameplay is perfectly ok and smooth.

1 thing to note is that those transition screen seems to have both 2D and 3D elements on it.

Attaching the correct and incorrect screens.
![right](https://cloud.githubusercontent.com/assets/3623403/10312497/1861503c-6c7e-11e5-9de8-fa786572ffae.JPG)
![wrong](https://cloud.githubusercontent.com/assets/3623403/10312498/18b5ac7c-6c7e-11e5-9705-654ebdf2c253.JPG)

Sorry about the upside down images.

I'm currently on kernel 4.2.2, latest ArchLinux (always updated) and mesa 11 from the mesa-git repository as per advised.

Hardware - AMD FM2+ A10-7850K (on board R7 graphics)

**Comment by mikejuni** [comment]
Sorry about the upside down images but I believe you get my point.

**Comment by axeldavy** [comment]
Can you either create an apitrace of the game (to enable us to reproduce) or figure out which commit is bad by bisecting ?

**Comment by mikejuni** [comment]
I'll try to do an API trace. Do I need to compile a debug version of Wine and mesa to do so?

**Comment by axeldavy** [comment]
no. Getting apitrace to work is a bit tricky though. Is the game using steam ?

**Comment by mikejuni** [comment]
Yes, that's I think is also a problem.

**Comment by axeldavy** [comment]
if you put apitrace d3d9.dll instead of the one in windows's system32 and that you set d3d9.dll override mode to native then integrated it may work

**Comment by mikejuni** [comment]
Will try, will post apitrace in a day or 2

**Comment by mikejuni** [comment]
I think I got a trace file now. Believe it is around 121Mb large. How can I upload it?

**Comment by okias** [comment]
As described on wiki, xz -9e and you can  upload it to our FTP, get in touch with sarnex on IRC

**Comment by sarnex** [comment]
The FTP is down right now, I'll try to get it fixed tonight.

**Comment by sarnex** [comment]
@mikejuni FTP is back

**Comment by sarnex** [comment]
Here is the trace: https://docs.google.com/uc?export=download&confirm=19j7&id=0B5zQohZGgTCSVTQ4UjY5Rkh3a1k


I can reproduce the issue on Tahiti, and turning off nine with the trace gives correct rendering.

**Comment by iiv3** [comment]
My bisect attempt laded me at
```
dd4802c8deedc0b2bad7d361c487761be31f2b56 is the first bad commit
commit dd4802c8deedc0b2bad7d361c487761be31f2b56
Author: Axel Davy <axel.davy@ens.fr>
Date:   Fri May 8 19:48:45 2015 +0200

    st/nine: Begin programmable shader fog support
```
I bisected freedesktop git Mesa, since it have nice tags for the releases.

**Comment by axeldavy** [comment]
Strange, I'll have to investigate.

**Comment by axeldavy** [comment]
ok, likely an error in the doc:
https://msdn.microsoft.com/en-US/library/bb173400.aspx
"If the programmable pipeline is used, then v1.w (in the pixel shader) equals 0, even if oD1.w is explicitly written in a vertex shader."
The patch implements that behaviour, among others.
If I revert just that behaviour the trace works.

**Comment by axeldavy** [comment]
Was the trace taken on nine or wine ?

**Comment by axeldavy** [comment]
can a trace be done on the other one (whatever the one is) ?

**Comment by mikejuni** [comment]
The trace was taken with nine enabled. Do you need another one with it disabled?

**Comment by axeldavy** [comment]
yes.
Wine doesn't advertise a flag Nine advertises. I want to see if the game changes its behaviour relative to this flag.

**Comment by iiv3** [comment]
There is something I don't understand - using `qapitrace` I can't find any mention of "FOGCOLOR" in the trace.

Also, at least one of the missing elements (The menu highlight line) doesn't seem to use any fixed function and sets its own Vertex and Pixel Shaders.

So why Fixed Function interfere with that code?

**Comment by axeldavy** [comment]
It does not.
Only the shader part of the link I gave interfere:
"If the programmable pipeline is used, then v1.w (in the pixel shader) equals 0, even if oD1.w is explicitly written in a vertex shader."

The shaders I've seen to multiply the color output by .... v1.w
a little stupid if it was supposed to be 0, right ? So msdn must be wrong there.
I'd like to know if with wine it still tries to use v1.w or something else.

**Comment by sarnex** [comment]
The trace without nine is usf4_no_nine.trace on the ftp.

**Comment by axeldavy** [comment]
Strange, it doesn't change its behaviour. That's very weird.

**Comment by iiv3** [comment]
This commit is supposed to fix/workaround it : https://github.com/iXit/Mesa-3D/commit/181b45f8ed4b0aaf717d04bc1603c07d923fb0cc

**Comment by mikejuni** [comment]
Should I recompile from this git repository to test it? I'm using mesa-git at this moment.

**Comment by axeldavy** [comment]
Yes if you want to test

**Comment by mikejuni** [comment]
Yes it worked. Thanks.

**Comment by mikejuni** [comment]
Hi just wondering, how often would patches here be sent upstream?

**Comment by axeldavy** [comment]
we accumulate patches and then send them by batch.

The current list of patches is likely to be sent in November or December.
