### ISSUE TITLE
WoW Gallium 9 + Wine 1.7 on Imac 11,2 WoW crashes on boot

### ISSUE THREAD

**Issue by vurstp** [iXit/Mesa-3D#145]
Explanation:
Cannot run WoW using gallium 9 + wine 1.7 on my iMac 11,2 GFX: 5730/6570 on Ubuntu 15.4.
WoW crashes on start up with a black screen. 

OpenGL version string: 3.0 Mesa 11.1.0-devel (git-1fda56c 2015-10-08 trusty-sarnex-ppa)

vurstp@Silverback:~$ NINE_DEBUG=all wine '/home/vurstp/.wine/drive_c/Program Files (x86)/World of Warcraft/Wow.exe'
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:heap:RtlSetHeapInformation 0x16e0000 0 0x32fdb8 4 stub
vurstp@Silverback:~$ fixme:heap:RtlSetHeapInformation 0x380000 0 0x23fda0 4 stub
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:WinHttpDetectAutoProxyConfigUrl discovery via DHCP not supported
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:mpr:WNetGetUniversalNameW (L"C:\\Program Files (x86)\\World of Warcraft\\data\\data", 0x00000001, 0x23cbe0, 0x23cba0): stub
fixme:thread:start_thread Started native thread 00000017
Mesa: User error: GL_INVALID_ENUM in glRenderbufferStorage(internalFormat=GL_SLUMINANCE8)
Mesa: User error: GL_INVALID_ENUM in glRenderbufferStorage(internalFormat=GL_SLUMINANCE8_ALPHA8)
Mesa: User error: GL_INVALID_OPERATION in glTexImage3D(bad target for depth texture)
Mesa: User error: GL_INVALID_OPERATION in glTexImage3D(bad target for depth texture)
Mesa: User error: GL_INVALID_OPERATION in glTexImage3D(bad target for depth texture)
Mesa: User error: GL_INVALID_OPERATION in glTexImage3D(bad target for depth texture)
Mesa: User error: GL_INVALID_OPERATION in glTexImage3D(bad target for depth texture)
Mesa: User error: GL_INVALID_OPERATION in glTexImage3D(bad target for depth texture)
Mesa: User error: GL_INVALID_OPERATION in glTexImage3D(bad target for depth texture)
Mesa: User error: GL_INVALID_OPERATION in glTexImage3D(bad target for depth texture)
Mesa: User error: GL_INVALID_OPERATION in glTexImage3D(bad target for depth texture)
Mesa: User error: GL_INVALID_OPERATION in glTexImage3D(bad target for depth texture)
fixme:win:EnumDisplayDevicesW ((null),0,0x23eff0,0x00000000), stub!
fixme:d3d11:D3D11CoreCreateDevice Ignoring feature levels.
fixme:dxgi:dxgi_device_init Ignoring adapter type.
fixme:winediag:dxgi_device_init Direct3D 10 is not supported on this GPU with the current shader backend.
fixme:win:EnumDisplayDevicesW ((null),0,0x23e8f0,0x00000000), stub!
err:x11drv:DRI3CheckExtension DRI3 extension is not present
err:d3dadapter:has_d3dadapter Unable to query DRI3. Trying DRI2 fallback (slower performance).
fixme:win:EnumDisplayDevicesW ((null),0,0x23e840,0x00000000), stub!
nine:get_bus_info: PCI info: vendor=0x1002, device=0x68c0
nine:adapter9:ctor: This=0x7c70ace0 pParams=0x23e4d0 pCTX=0x7c84d570
nine:nine_dump_D3DADAPTER_IDENTIFIER9: D3DADAPTER_IDENTIFIER9(0x7c84d580):
Driver: atiumdag.dll
Description: ATI Radeon HD 5600 Series
DeviceName: Gallium 0.4 with X.Org
DriverVersion: 000a0500.00060011
VendorId: 1002
DeviceId: 68c0
SubSysId: 0
Revision: 0
GUID: aeb2cdd4.6e41.43ea.94.1c.83.61.cc.76.07.81
WHQLLevel: 0
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",0,0x23e840,0x00000000), stub!
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",1,0x23e840,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),1,0x23e840,0x00000000), stub!
fixme:d3d9:d3dadapter9_new 
Native Direct3D 9 is active.
For more information visit https://wiki.ixit.cz/d3d9
nine:adapter9:GetAdapterIdentifier: This=0x7c70ace0 Flags=0 pIdentifier=0x23ef00
nine:adapter9:dtor: This=0x7c70ace0
fixme:thread:start_thread Started native thread 00000081
fixme:thread:start_thread Started native thread 00000085
fixme:thread:start_thread Started native thread 00000094
fixme:thread:start_thread Started native thread 00000080
fixme:thread:start_thread Started native thread 00000075
Mesa: User error: GL_INVALID_ENUM in glRenderbufferStorage(internalFormat=GL_SLUMINANCE8)
Mesa: User error: GL_INVALID_ENUM in glRenderbufferStorage(internalFormat=GL_SLUMINANCE8_ALPHA8)
Mesa: User error: GL_INVALID_OPERATION in glTexImage3D(bad target for depth texture)
Mesa: User error: GL_INVALID_OPERATION in glTexImage3D(bad target for depth texture)
Mesa: User error: GL_INVALID_OPERATION in glTexImage3D(bad target for depth texture)
Mesa: User error: GL_INVALID_OPERATION in glTexImage3D(bad target for depth texture)
Mesa: User error: GL_INVALID_OPERATION in glTexImage3D(bad target for depth texture)
Mesa: User error: GL_INVALID_OPERATION in glTexImage3D(bad target for depth texture)
Mesa: User error: GL_INVALID_OPERATION in glTexImage3D(bad target for depth texture)
Mesa: User error: GL_INVALID_OPERATION in glTexImage3D(bad target for depth texture)
Mesa: User error: GL_INVALID_OPERATION in glTexImage3D(bad target for depth texture)
Mesa: User error: GL_INVALID_OPERATION in glTexImage3D(bad target for depth texture)
fixme:win:EnumDisplayDevicesW ((null),0,0x23ed50,0x00000000), stub!
fixme:dxgi:dxgi_adapter_CheckInterfaceSupport iface 0x5fa30, guid {9b7e4c0f-342c-4106-a19f-4f2704f689f0}, umd_version (nil) stub!
fixme:win:EnumDisplayDevicesW ((null),0,0x23ed70,0x00000000), stub!
fixme:thread:start_thread Started native thread 0000008e
fixme:thread:start_thread Started native thread 00000078
fixme:thread:start_thread Started native thread 0000007a
nine:get_bus_info: PCI info: vendor=0x1002, device=0x68c0
nine:adapter9:ctor: This=0x7c862540 pParams=0x23ea00 pCTX=0x7c804740
nine:nine_dump_D3DADAPTER_IDENTIFIER9: D3DADAPTER_IDENTIFIER9(0x7c804750):
Driver: atiumdag.dll
Description: ATI Radeon HD 5600 Series
DeviceName: Gallium 0.4 with X.Org
DriverVersion: 000a0500.00060011
VendorId: 1002
DeviceId: 68c0
SubSysId: 0
Revision: 0
GUID: aeb2cdd4.6e41.43ea.94.1c.83.61.cc.76.07.81
WHQLLevel: 0
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",0,0x23ed70,0x00000000), stub!
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",1,0x23ed70,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),1,0x23ed70,0x00000000), stub!
fixme:d3d9:d3dadapter9_new 
Native Direct3D 9 is active.
For more information visit https://wiki.ixit.cz/d3d9
nine:adapter9:GetDeviceCaps: This=0x7c862540 DeviceType=HAL pCaps=0x23f260
nine:adapter9:dtor: This=0x7c862540
fixme:thread:start_thread Started native thread 00000042
fixme:thread:start_thread Started native thread 0000008c
fixme:win:EnumDisplayDevicesW ((null),0,0x23eb50,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),0,0x23eaa0,0x00000000), stub!
fixme:thread:start_thread Started native thread 0000008a
fixme:thread:start_thread Started native thread 00000079
fixme:thread:start_thread Started native thread 00000072
fixme:thread:start_thread Started native thread 00000088
fixme:thread:start_thread Started native thread 0000007c
nine:get_bus_info: PCI info: vendor=0x1002, device=0x68c0
nine:adapter9:ctor: This=0x7c862540 pParams=0x23e730 pCTX=0x7c70c0c0
nine:nine_dump_D3DADAPTER_IDENTIFIER9: D3DADAPTER_IDENTIFIER9(0x7c70c0d0):
Driver: atiumdag.dll
Description: ATI Radeon HD 5600 Series
DeviceName: Gallium 0.4 with X.Org
DriverVersion: 000a0500.00060011
VendorId: 1002
DeviceId: 68c0
SubSysId: 0
Revision: 0
GUID: aeb2cdd4.6e41.43ea.94.1c.83.61.cc.76.07.81
WHQLLevel: 0
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",0,0x23eaa0,0x00000000), stub!
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",1,0x23eaa0,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),1,0x23eaa0,0x00000000), stub!
fixme:d3d9:d3dadapter9_new 
Native Direct3D 9 is active.
For more information visit https://wiki.ixit.cz/d3d9
nine:adapter9:GetAdapterIdentifier: This=0x7c862540 Flags=0 pIdentifier=0x23f160
nine:adapter9:dtor: This=0x7c862540
fixme:win:EnumDisplayDevicesW ((null),0,0x23f220,0x00000000), stub!
nine:get_bus_info: PCI info: vendor=0x1002, device=0x68c0
nine:adapter9:ctor: This=0x7c862540 pParams=0x23eeb0 pCTX=0x7c6f2b10
nine:nine_dump_D3DADAPTER_IDENTIFIER9: D3DADAPTER_IDENTIFIER9(0x7c6f2b20):
Driver: atiumdag.dll
Description: ATI Radeon HD 5600 Series
DeviceName: Gallium 0.4 with X.Org
DriverVersion: 000a0500.00060011
VendorId: 1002
DeviceId: 68c0
SubSysId: 0
Revision: 0
GUID: aeb2cdd4.6e41.43ea.94.1c.83.61.cc.76.07.81
WHQLLevel: 0
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",0,0x23f220,0x00000000), stub!
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",1,0x23f220,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),1,0x23f220,0x00000000), stub!
fixme:d3d9:d3dadapter9_new 
Native Direct3D 9 is active.
For more information visit https://wiki.ixit.cz/d3d9
nine:adapter9:GetDeviceCaps: This=0x7c862540 DeviceType=HAL pCaps=0xd2af558
fixme:thread:start_thread Started native thread 00000097
fixme:thread:start_thread Started native thread 0000006c
fixme:thread:start_thread Started native thread 0000007b
fixme:thread:start_thread Started native thread 00000090
fixme:thread:start_thread Started native thread 00000087
fixme:d3d9:D3DPERF_SetOptions (0x1) : stub
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",0,0x23ec40,0x00000000), stub!
nine:adapter9:CreateDevice: This=0x7c862540 RealAdapter=0 DeviceType=HAL hFocusWindow=0x400e6 BehaviourFlags=52 pD3D9=0x5fa30 pPresentationGroup=0x5d8e0 ppReturnedDeviceInterface=0xd2af550
nine:adapter9:GetDeviceCaps: This=0x7c862540 DeviceType=HAL pCaps=0x23eda0
nine:device9:ctor: This=0x7c9502e0 pParams=0x23ecc0 pScreen=0x7c6f4360 pCreationParameters=0x23ed80 pCaps=0x23eda0 pPresentationParameters=0x23f1c0 pD3D9=0x5fa30 pPresentationGroup=0x5d8e0 pCTX=0x7c6f2b10 ex=0 pFullscreenDisplayMode=(nil)
fixme:d3dadapter:DRI3PresentGroup_GetMultiheadCount (0x5d8e0), stub!
fixme:d3dadapter:DRI3PresentGroup_GetMultiheadCount (0x5d8e0), stub!
nine:swapchain9:ctor: This=0x7c9cf310 pDevice=0x7c9502e0 pPresent=0x5dc90 pCTX=0x7c6f2b10 hFocusWindow=0x400e6
nine:swapchain9:Resize: This=0x7c9cf310 pParams=0x23f1c0
nine:swapchain9:Resize: pParams(0x23f1c0):
BackBufferWidth: 1920
BackBufferHeight: 1080
BackBufferFormat: D3DFMT_X8R8G8B8
BackBufferCount: 1
MultiSampleType: 0
MultiSampleQuality: 0
SwapEffect: 1
hDeviceWindow: 0x400e6
Windowed: 0
EnableAutoDepthStencil: 1
AutoDepthStencilFormat: D3DFMT_D24S8
Flags: LOCKABLE_BACKBUFFER
FullScreen_RefreshRateInHz: 60
PresentationInterval: 80000000
nine:surface9:ctor: This=0x7c877f20 pDevice=0x7c9502e0 pResource=0x7c9d00e0 Level=0 Layer=0 pDesc=0x23e980
nine:resource9:ctor: This=0x7c877f20 pParams=0x23e8a0 initResource=0x7c9d00e0 Allocate=0 Type=1 Pool=0 Usage=1
nine:surface9:Dump: 
NineSurface9(0x7c877f20->0x7c9d00e0/(nil)): Pool=DEFAULT Type=SURFACE Usage=RT
Dims=1920x1080 Format=D3DFMT_X8R8G8B8 Stride=7680 Lockable=1
Level=0(0), Layer=0
nine:unknown:QueryInterface: This=0x7c9cf310 riid=0x23e780 ppvObject=0x23e778
Mesa: User error: GL_INVALID_ENUM in glEGLImageTargetTexture2D(target=9728)
fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 6
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:process:GetLogicalProcessorInformationEx (3,(nil),0x33ef44): stub
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 412 requests (412 known processed) with 0 events remaining.
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:WinHttpDetectAutoProxyConfigUrl discovery via DHCP not supported

**Comment by Altosk** [comment]
what version of mesa do you have? also did u use oibaf ppa?

**Comment by axeldavy** [comment]
it is strange, at first it says nine is active, but then it says it is disabled.

**Comment by sarnex** [comment]
He's using my PPA which is ixit git + oibaf + debug. I think he has two logs in one by accident.

**Comment by vurstp** [comment]
Fixed

**Comment by vurstp** [comment]
OpenGL version string: 3.0 Mesa 11.1.0-devel (git-1fda56c 2015-10-08 trusty-sarnex-ppa)

**Comment by axeldavy** [comment]
Try with DRI3

**Comment by vurstp** [comment]
Added 

Section "Device"
   Identifier "radeon"
   Driver "radeon"
   Option "DRI" "3"
EndSection

to xorg.conf. Still crashes.

**Comment by vurstp** [comment]
Breakthrough update:
I managed to get WoW to run. All I did was comment out the original device section in the xorg.conf file, so that the new device section I added wasn't getting conflicted with. WoW ran, but barely... I got somewhere around 2fps on the lowest possible settings.

Unless I'm doing something wrong, this is disappointing, as wow will get at least 15 on d3d9 without gallium 9 + wine 1.7.52, and around 30 with opengl.

**Comment by axeldavy** [comment]
are you sure it's using gallium nine ? And that's it's using the gpu at all ?

**Comment by vurstp** [comment]
I'm not sure... I found this in the debug output:
DeviceName: Gallium 0.4 with X.Org

So I guess no. This is the guide I followed: https://wiki.ixit.cz/d3d9_tutorial

**Comment by vurstp** [comment]
So I guess I'm not using Gallium 9, which I'm not sure why - or what I did wrong here. 

The debug output is listing my graphics card, so I assume it is being used.

**Comment by Altosk** [comment]
I play WoW 1.12.1 and it works fine. Another users said that wow 2.3.4 works fine as well. Is this for WoW:WoD?

**Comment by vurstp** [comment]
Correct 6.2.2

**Comment by Altosk** [comment]
Are u using the d3d9 client/ option?

**Comment by Altosk** [comment]
if i remember correctly is that the WoD starts with like dx10 or dx11 and u have to set it dx9 if memory serves

**Comment by vurstp** [comment]
It starts with d3d9. What should I do?

**Comment by Altosk** [comment]
32 or 64 bit client?

**Comment by vurstp** [comment]
64

**Comment by Altosk** [comment]
Try a 32bit client in  32 bit prefix

**Comment by vurstp** [comment]
I tried just launching from the battle.net client with settings set to launch 32 bit client: it ran just about the same as standard d3d9 with regular wine installed at around 14-17fps on lowest settings.

Then I tried NINE_DEBUG=all wine '/home/vurstp/.wine/drive_c/Program Files (x86)/World of Warcraft/Wow.exe' -noautolaunch64bit
Which ran at about 2fps at best. So basically the same if I ran the command without the noautolaunch64bit

But this is a grim comparison to opengl performance. I just don't understand what I'm doing wrong.

**Comment by Altosk** [comment]
I haven't played in 64 prefix don't know if nine works right in it

**Comment by vurstp** [comment]
Well it doesn't have any improvement in 32bit apparently.

**Comment by Altosk** [comment]
Try a fresh 32 bit wine prefix not just 32 bit mode wow

**Comment by vurstp** [comment]
That did it! 53fps of fair - that's just awesome! Thank you so much!
