### ISSUE TITLE
Guild Wars 2 NineBaseTexture9_UpdateSamplerView: Assertion `resource' failed.

### ISSUE THREAD

**Issue by steemandlinux** [iXit/Mesa-3D#15]
When I try to run the Guild Wars 2, the nine shows the error:

basetexture9.c:438:NineBaseTexture9_UpdateSamplerView: Assertion `resource' failed.

Radeon 6850, last build of gallium-nine.

FULL LOG:

https://www.mediafire.com/?anydu0a6ibtrr4z

**Comment by steemandlinux** [comment]
Why you do not close a bug?

**Comment by axeldavy** [comment]
because we only have workaround for it. Proper fix is not there yet

**Comment by axeldavy** [comment]
The proper fix is now on master. Closing.
