### ISSUE TITLE
Deus Ex: Human Revolution Directors Cut FPS drops while the game stream in new content.

### ISSUE THREAD

**Issue by DarkDefender** [iXit/Mesa-3D#154]
Thanks to the native d3d9 implementation I'm able to play this game finally with acceptable framerates.

However when the game is supposed to dynamicly stream in new content, my fps drops from ~60 to 5 till it's done loading. At first i thought it might be because it perhaps were using too much cpu when it tried to load in stuff. So I used the following gallium HUD command:
```
GALLIUM_HUD="cpu0+cpu1+cpu2+cpu3:100,cpu:100,fps;draw-calls,requested-VRAM+requested-GTT,pixels-rendered"
```

When I then went into one of the "loading zones" I saw that my cpu usage per core didn't go over 50%. However I did see that the requested VRAM did not go over 256MB.

Because I have a 290x (4GB VRAM) I think that it's strange that the game would only use 256MB. So I guess that whats happening is that framerate tanks because it's trying to load more stuff into VRAM but has to swap stuff out instead because it only uses 256MB.

If I run dxdiag with wine it reports that I have 16MB VRAM and Steam reports 0MB. I tried the wine VRAM regedit hack but it didn't help with the Deus Ex problems.

Here is what Steam says about my GPU:
```
Video Card:
    Driver:  AMD Radeon R9 290

    DirectX Driver Name:  atiumdag.dll
    Driver Version:  1.0
    DirectX Driver Version:  6.17.10.1280
    Driver Date Not Detected
    OpenGL Version: 3.0
    Desktop Color Depth: 32 bits per pixel
    DirectX Card: AMD Radeon R9 290
    VendorID:  0x1002
    DeviceID:  0x67b0
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    No SLI or Crossfire Detected
    Primary Display Resolution:  1920 x 1200
    Desktop Resolution: 1920 x 1200
    Primary Display Size: 20.00" x 12.52"  (23.58" diag)
                                            50.8cm x 31.8cm  (59.9cm diag)
    Primary Bus Type Not Detected
    Primary VRAM: 0 MB
    Supported MSAA Modes:  2x 4x 8x 
```

This problem might be a problem with wine itself (or the game). Is there anyway to see how much VRAM is reported when using the native d3d9 implementation?

**Comment by sarnex** [comment]
I did a fresh install of Steam in a fresh wineprefix. The card is identified right but my VRAM is -1024, even after I deleted the registry key about it from POL. Strange.

**Comment by siro20** [comment]
I see the same behaviour. It is using about 256Mbyte of Vram.
I guess this is intended by the developers to be compatible with older cards.
I don't see huge performance drops. I get around 30fps in loading zones.
Tested with HD6780 1GB Vram.
Low CPU usage could be due to WINEs poor thread management.

**Comment by DarkDefender** [comment]
@siro20 what CPU do you have? I got a AMD Bulldozer cpu that I think should be equal to a intel i5. The game seems to make use of quite a few threads so it uses all of my 8 cores.

If you have a better CPU (i7 or something) then I guess that it could be wine that is not taking advantage of all available CPU power.

Perhaps there is something we can do to see what is really happening when it is loading stuff. I get about 5fps on the loading screens also. So perhaps it has something to do with disk access?

**Comment by siro20** [comment]
I'm on Intel(R) Core(TM) i5-3450 - 4Cores
I'm running this game on my slowest harddisk.
Steam takes about 5 minutes to start the first time, but the game runs fine.

**Comment by DarkDefender** [comment]
After some searching I found this program to test out if only 256MB could be allocated:
https://connect.microsoft.com/VisualStudio/feedback/details/1263324/gpu-memory-allocation-limit-on-directx9-windows-8

The program is in the attachment for that issue. Start it up and hold down/tap space to have it try to allocate more VRAM. I got it to use ~4GB so I guess it's not an allocation issue.
The source code for the program is also in the zip file.

However I did find this:
http://forums.evga.com/Deus-Ex-human-revolution-low-memory-usage-m1189556.aspx

It seems like if I crank up everything to max I also get a memory usage close to 400MB. I didn't notice any lower fps than before either...  IE still around 60 in my test area and 5 when loading stuff. So I guess that bottleneck is somewhere else...

I guess this is really a general wine issue then. I'm still curious why it seems to lock the fps to 5 when loading in stuff though... I would think that it would fluctuate a bit. But it is rock solid 5 fps till it's done loading it seems. My Gallium hud fps graph looks like a square wave after playing a bit.

So I guess this issue can be closed then? I don't know how I could see were the bottleneck in wine is.

The dx9 test program does however temporarly freeze for me when it tries to allocate more memory. But I guess that is expected?

**Comment by siro20** [comment]
Does it show the same performance drop in vanilla wine while loading? You can use Gallium hud too, to see the fps and vram usage.

**Comment by DarkDefender** [comment]
I can only check the menu and loading screens as it crashes when it tries to go in game.
There is something wrong with the gallium hud when I run the game with opengl. The graphs jumps back and forward. And I think that the fps value is wrong also. It said I had 0-1 fps in the menus but those felt as smooth as with native d3d (~110fps). With opengl, it said it used 1.5GB VRAM. But I guess that is the additional overhead from the d3d wrapper.

So I don't really know how to test it with vanilla wine :(

**Comment by siro20** [comment]
Tested on Wine:
"The graphs jumps back and forward. " - I see the same behaviour.
The vram usage is about 270Mbyte, looks similar to nine.
In loading areas the framerate drops to 1fps, in other areas it is acceptable.
Summarized it is much worse than nine.

**Comment by DarkDefender** [comment]
@siro20 does your total cpu usage drop when you are in the loading zones? I did notice that the fps and cpu graph have the same pattern. 

So with GALLIUM_HUD="cpu:100,fps" I can see that my cpu usage is around 30% when I'm in my test area with about 60fps. Then when I go to a loading area my cpu usage drops to 15% and my fps to 5. Then it goes back up to 30% and 60fps when it's done loading.

Because it seems like you get the same drop when using opengl or native d3d, I guess you were right when you guessed it was something with WINEs poor thread management.

Perhaps it tries to load in new stuff with a new/other thread and then wine chokes on it. I would at least think that the CPU usage should go up when it tries to load in new stuff...

**Comment by axeldavy** [comment]
Ok, I close the issue then.
