### ISSUE TITLE
fallout new vegas started to crash on nouveau

### ISSUE THREAD

**Issue by xpue** [iXit/Mesa-3D#160]
It crashes with message:

.../src/gallium/drivers/nouveau/codegen/nv50_ir_emit_nvc0.cpp:1723: void nv50_ir::CodeEmitterNVC0::emitLoadStoreType(nv50_ir::DataType): Assertion `!"invalid type"' failed.

It did work fine with gcc 5.2.0 some time ago, and skyrim on same engine works now, also works with wine d3d. System: nouveau on gts450, gcc 5.2.0, cflags "-O0", same problems with ixit git master and upstream mesa git master.

**Comment by axeldavy** [comment]
looks like the game thinks it is allowed to use a format that nouveau doesn't support (games works on radeon).

Could you give the log (NINE_DEBUG=all with mesa compiled with --enable-debug)

**Comment by xpue** [comment]
Log with NINE_DEBUG=all

https://drive.google.com/file/d/0Bw8YULLJvu4gd1FYeWx6N08zUkk/view

**Comment by axeldavy** [comment]
It looks like it is rather a compilation problem. Could you use NINE_TGSI_DUMP=1 as well ?

**Comment by xpue** [comment]
Thats on upstream mesa, if it matters.

https://drive.google.com/file/d/0Bw8YULLJvu4gWjVDLXZOMmZ2VGM/view

**Comment by axeldavy** [comment]
Can you try the patch proposed here:

https://bugs.freedesktop.org/show_bug.cgi?id=90348

**Comment by xpue** [comment]
Yes, this patch fixes the issue.

**Comment by xpue** [comment]
Fixed upstream: http://cgit.freedesktop.org/mesa/mesa/commit/?id=4deb118d06e96731f3481daa72c201d7258bfbbb
