### ISSUE TITLE
'Prefer native Direct3D 9' option missing in fresh install

### ISSUE THREAD

**Issue by vurstp** [iXit/Mesa-3D#164]
I recently reinstalled ubuntu 15.10, but with my /home partition unformated and intact. I tried removing all traces of wine from my home directory in the process. 

The option is missing probably because I have the wrong version installed wine --version wine-1.7.55, although I followed the steps in https://wiki.ixit.cz/d3d9_tutorial down to the line.

I believe the drivers are installed properly:
OpenGL version string: 3.0 Mesa 11.1.0-devel (git-dd05ffe 2015-11-18 trusty-sarnex-ppa)

I tried using both the aptitude approach as well as regular apt-get install approach.

Help would be much appreciated.

**Comment by xpue** [comment]
This option was moved to staging tab and description text was changed.

**Comment by vurstp** [comment]
wow, and I even thought meanwhile "they must have changed something." Sorry for not exploring the issue myself more thoroughly. The https://wiki.ixit.cz/d3d9_tutorial should be modified accordingly. 

This issue has bee resolved.

**Comment by sarnex** [comment]
Thanks, I've updated the wiki

**Comment by okias** [comment]
wiki is still wrong. This issue is solved, but all references on wiki should be changed.

**Comment by sarnex** [comment]
@okias Sorry about that, the wiki should be updated everywhere now
