### ISSUE TITLE
Battle.net application

### ISSUE THREAD

**Issue by maaniv** [iXit/Mesa-3D#167]
Arch linux
Graphic card: 290x.
mesa 11.06, xf86-video-ati - 7.6.1 (dri 3 enabled) - from standard repos.
wine-staging-d3dadapter - from aur.
Battle.net with nine enabled crashed on start. Without nine - all is ok.
wow.exe and wow64.exe run without problems.
Sorry for my english.

**Comment by sarnex** [comment]
@maaniv Can you compile mesa with --enable-debug and run the game with NINE_DEBUG=all wine game.exe and post the log?

**Comment by Altosk** [comment]
wine64 doesnt work with nine

**Comment by sarnex** [comment]
I've had reports of it working fine, but yeah we don't really support it.

**Comment by maaniv** [comment]
I could not make the mesa debug version because of build errors. I've tried aur mesa-git. Sorry :(

**Comment by sarnex** [comment]
@maaniv Does this still happen to you with mesa git from today?

**Comment by maaniv** [comment]
I tried the gears on gallium live cd - everything is ok.

**Comment by sarnex** [comment]
@maaniv To confirm, this bug is fixed with mesa git?

**Comment by maaniv** [comment]
Yes, fixed.
