### ISSUE TITLE
World of warcraft 1.12.1 crashing on alt tabbing nouveau

### ISSUE THREAD

**Issue by Altosk** [iXit/Mesa-3D#169]
When alt-tabbing back into the game, the game crashes on nouveau. on AMD card its fine no crashing at all.

nouveau: kernel rejected pushbuf: No such file or directory

this is line caught my eyes, perhaps someone knows a fix. other than this the game run great with reclocking from karolherbst's github on par with amd cards.

**Comment by sarnex** [comment]
Can you post an apitrace? I had a similar issue with X crashing via alt tab and it was captured in apitrace.

**Comment by Altosk** [comment]
Apitrace doesn't work with wow 1.12.1 sadly

**Comment by imirkin** [comment]
There should be an accompanying error in dmesg which should tell you what the actual issue was.

**Comment by Altosk** [comment]
i need to retest with latest mesa but it should be fixed with siro's patches

**Comment by vurstp** [comment]
Are you running full screen mode? If yes, try running windowed full screen and alt tab. This worked for me.

**Comment by Altosk** [comment]
Its a bug that was fixed on mesa git I just need to retest the fixes

**Comment by Altosk** [comment]
this is fixed upstream closing.
