### ISSUE TITLE
Age of Conan renders only in windowed mode

### ISSUE THREAD

**Issue by Altosk** [iXit/Mesa-3D#173]
AoC renders when minimized and not when in focus. I'm currently on windows so I can't provide an apitrace nor a log.

**Comment by siro20** [comment]
I've investigated into the issue:
The game doesn't use TestCooperativeLevel, but listens to window message.
As soon as a mouse message is received it stops rendering until Alt+Tab is used.

**Comment by Altosk** [comment]
siro20 running the game in a windowed mode work and i can play the game fine but fullscreen doesnt work should i update the bug name?

**Comment by Altosk** [comment]
Sins of a solar empire : Rebellion shows the same issues but in both fullscreen and window modes

**Comment by siro20** [comment]
Yes, please update the name.
I've done some tests and it looks like it's not Alt+Tab itself, but mouse messages (first mouse message) stops the app from drawing. By hacking wine and removing all mouse messages the game renders, but you aren't able to click anywhere...
I've managed to get it working in WINE's virtual desktop mode.
There are some other apps that seem to be affacted by this issue.

**Comment by Altosk** [comment]
siro this "may" lead to something : https://bugs.webkit.org/show_bug.cgi?id=121329 it seems that webkit ran into a similar problem, maybe we can do the same?

**Comment by Altosk** [comment]
does nine implement BOOL InvalidateRect(__in  HWND hWnd, __in  const RECT *lpRect, __in  BOOL bErase); ? just been researching this problem some more, i cant seem to find it if it is. heres the link i dug up http://kittyandbear.net/c-programming-guides/win32-erase-invalidaterect.txt on it.

**Comment by Altosk** [comment]
siro20 any word on this?

**Comment by siro20** [comment]
Stil doesn't work with latest for_upstream_staging.

**Comment by iiv3** [comment]
World of Goo is having the same issue. It's good test case, since it is small and have free demo.

Also, no issues with wined3d.

**Comment by iiv3** [comment]
Using `WINEDEBUG=+timestamp,+message wine WorldOfGoo.exe` revealed that the WM_MOUSEMOVE message is repeated over thousand times per second. Probably there is some infinite recursion caused by wrong routing of messages. I have no idea what exactly happens, but it is a step in the right direction.


The following patch, workarounds the issue, by remembering the parameters of the last mouse move and not passing along the duplicate messages:
```
--- a/dlls/d3d9-nine/wndproc.c  2016-07-02 17:43:20.942787583 +0300
+++ b/dlls/d3d9-nine/wndproc.c  2016-07-02 17:54:26.572802626 +0300
@@ -171,6 +171,15 @@
     proc = entry->proc;
     nine_wndproc_mutex_unlock();
 
+    if(message == WM_MOUSEMOVE){
+        static WPARAM mouse_move_wparam;
+        static LPARAM mouse_move_lparam;
+
+        if (wparam == mouse_move_wparam && lparam == mouse_move_lparam) return S_OK;
+        mouse_move_wparam = wparam;
+        mouse_move_lparam = lparam;
+    }
+
     if (present)
         return device_process_message(present, window, unicode, message, wparam, lparam, proc);
     if (unicode)
```

**Comment by axeldavy** [comment]
Any idea why the issue doesn't happen with wine ?

iive, do you think this is a correct fix (the expected behaviour) or something else should be done ?

**Comment by iiv3** [comment]
I can confirm that this fixes "World of Goo".
