### ISSUE TITLE
Need For Speed Most Wanted won´t start.

### ISSUE THREAD

**Issue by Ufeldraku** [iXit/Mesa-3D#175]
It gives this error, in the PlayOnLinux´s debugger.
https://drive.google.com/open?id=0BzRFhGifYUn2MTZ0d1BxSXUzbjg
It opens, but the screen is buggied.
It works with CSMT, though.

**Comment by axeldavy** [comment]
32 bits wine used ?

**Comment by Ufeldraku** [comment]
Yup.

**Comment by Ufeldraku** [comment]
Tried editing the d3dx9_26.dll overrides, didn´t help.

**Comment by Ufeldraku** [comment]
Nothing?

**Comment by axeldavy** [comment]
You can build mesa with --enable-debug an post the output of the game with NINE_DEBUG=all

**Comment by Ufeldraku** [comment]
Sadly, when I tried to compile mesa-git en manjaro, it complains about some missing files, I will try again though

**Comment by axeldavy** [comment]
if possible use this mesa git repo.

**Comment by Ufeldraku** [comment]
does that make any difference?

**Comment by Ufeldraku** [comment]
I have edited my makepkg.conf with the --enable-debug flag, so if everything goes fine, I´ll report something in a few hours.
If I put NINE_DEBUG=all in the PlayonLinux´s command to enter before executing the application, Wiil it work? or is it just related to windows´ commands

**Comment by axeldavy** [comment]
it should work.

And yes there is difference, as this mesa git repo has several nine fixes not upstream.

**Comment by Ufeldraku** [comment]
Crap, I´m compiling the aur´s mesa
Well, I´ll still debug though.

**Comment by sarnex** [comment]
If you want to use the POL commmad to run before execution, put 'export NINE_DEBUG=all' no quotes

**Comment by siro20** [comment]
*Generated by NFS MW Demo*:

wine: Unhandled page fault on read access to 0x00000000 at address 0x7d742555 (thread 0009), starting debugger...
Unhandled exception: page fault on read access to 0x00000000 in 32-bit code (0x7d742555).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7d742555 ESP:0032fb24 EBP:7ca170e0 EFLAGS:00210246(  R- --  I  Z- -P- )
 EAX:00000000 EBX:00000000 ECX:0000001a EDX:7c6fef28
 ESI:00000000 EDI:7c68f5b0
Stack dump:
0x0032fb24:  00000000 00000000 7c6fef28 7c6ff348
0x0032fb34:  00000008 7c6fef28 00000000 7db00000
0x0032fb44:  7ca170e0 7c7008bc 7c7008bc 00000000
0x0032fb54:  3f800000 00000001 7d741b3b 7db00000
0x0032fb64:  7c6fef08 7ca16f58 00000010 7d74319e
0x0032fb74:  00000000 00000000 7d976b2f 7c6fef08
Backtrace:
=>0 0x7d742555 nine_state_copy_common+0xa25() in d3dadapter9.so.1 (0x7ca170e0)
  1 0x7d74319e NineStateBlock9_Capture+0x1cd() in d3dadapter9.so.1 (0x00000010)
  2 0x00b86185 in d3dx9_26 (+0x106184) (0x0032fbd0)
  3 0x00b89a9e in d3dx9_26 (+0x109a9d) (0x0032fbfc)
0x7d742555 nine_state_copy_common+0xa25 in d3dadapter9.so.1: repe movsl	(%esi),%

It crashes on FF lighting as src->ff.light is NULL.
```
for (i = 0; i < mask->ff.num_lights; ++i)
   if (mask->ff.light[i].Type != NINED3DLIGHT_INVALID)
        dst->ff.light[i] = src->ff.light[i];

memcpy(dst->ff.active_light, src->ff.active_light, sizeof(src->ff.active_light) );
dst->ff.num_lights_active = src->ff.num_lights_active;
```
I guess this should be:
```
for (i = 0; i < mask->ff.num_lights; ++i)
    if (mask->ff.light[i].Type != NINED3DLIGHT_INVALID)
        dst->ff.light[i] = mask->ff.light[i];

memcpy(dst->ff.active_light, src->ff.active_light, sizeof(src->ff.active_light) );
dst->ff.num_lights_active = src->ff.num_lights_active;
```

**Comment by axeldavy** [comment]
crash fixed on ixit master.

However game seems to be too dark compare to wined3d.
I suspect the active light stateblock code is the culprit, but that's another bug.

Closing.

**Comment by axeldavy** [comment]
Great, I found an error in my patch, and fixing it seems to have the game render properly.
Perhaps we have at last lights working properly !
