### ISSUE TITLE
About "Improve state validation"

### ISSUE THREAD

**Issue by rboxeur** [iXit/Mesa-3D#177]
Hi,

Do you plan to update  the commit "Improve state validation"

 +    case NINE_STATE_RANGE_PREV_VAL:
+        assert(!"TODO");
+        break;

This assert can break a couple of games. Bad solution is to comment this line assert else it can break a couple of games sadly :(

**Comment by axeldavy** [comment]
No state is associated to NINE_STATE_RANGE_PREV_VAL so far (and perhaps nothing will), so nothing to worry.
