### ISSUE TITLE
Everything crashes with 1.8.2 wine and nine enabled (HD7700m)

### ISSUE THREAD

**Issue by nicman23** [iXit/Mesa-3D#178]
Not sure if i m supposed to post this here, but everything crashes with nine enabled with 1.8 wine.

Last working version was 1.7.55. DRI3 is enabled and I just compiled the mesa git from your fork.

With NINE_DEBUG=all and Fallout NV (64 bit prefix but other games ie league of legends also crash with a 32 bit prefix) the terminal spews out this

```
Native Direct3D 9 is active.
For more information visit https://wiki.ixit.cz/d3d9
Hook_DirectInput8Create_Execute
fixme:d3dadapter:d3dadapter9_new
Native Direct3D 9 is active.
For more information visit https://wiki.ixit.cz/d3d9
fixme:d3dadapter:DRI3PresentGroup_GetMultiheadCount (0x1ef090), stub!
fixme:d3dadapter:DRI3PresentGroup_GetMultiheadCount (0x1ef090), stub!
fixme:d3dadapter:D3DPERF_SetOptions (0x1) : stub
fixme:driver:D3DKMTOpenAdapterFromHdc (0x33ec08): stub
ERROR: Could Not Get Primary Adapter Handle
```

I am with linux 4.3.2-1 (ck), gcc 5.3.0 on Arch Linux. The only thing I can thing of is the fact that 1.7.55 is compiled without the -O2 flag.

My gpu is and firepro 4000m (hd7700m 1002:682d).

EDIT: I m using this aur package https://aur.archlinux.org/packages/wine-gaming-nine/ in which the author tried to help me with the hd7700m_support.patch patch. It did not help

PS: this is my first post on github please be kind :)

**Comment by nicman23** [comment]
possible relevance? #163

**Comment by ChristophHaag** [comment]
For testing I use the very first example here: http://www.codesampler.com/dx9src/dx9src_1.htm#dx9_initialization (the c++ version).

Then start it with `winedbg --gdb dx9_initialization.exe` (or any other d3d9 program) and enter "continue" or "c" once and press enter. If it then starts and crashes with
`0x78ff1fab in LLVMAddTargetDependentFunctionAttr () from /usr/lib32/libLLVM-3.8svn.so` you have probably the same problem.

**Comment by nicman23** [comment]
full log (not the same issue!)
`fixme:winediag:start_process Wine Staging 1.8-rc3 is a testing version containing experimental patches.
fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
0027:0028: create process 'Z:\home\nikos\dx9_initialization\dx9_initialization.exe'/0x110590 @0x40138a (0<0>)
fixme:module:load_dll Loader redirect from L"d3d9.dll" to L"d3d9-nine.dll"
0027:0028: create thread I @0x40138a
xe: ../../../wine-patched-staging-1.8-rc3/programs/winedbg/gdbproxy.c:2375: gdb_exec: Assertion `0' failed.
winedbg: Internal crash at 0xf7790bf0`

**Comment by siro20** [comment]
Your debugger crashed! Does it work with ixit/wine + ixit/Mesa?

**Comment by nicman23** [comment]
will try tomorrow, can you tell me the flags for compiling ixit/wine

**Comment by sarnex** [comment]
Just use --with-d3dadapter and the rest of the usual flags.

**Comment by nicman23** [comment]
Currently compiling with a modified pkgbuild
[PKGBUILD.txt](https://github.com/iXit/Mesa-3D/files/63690/PKGBUILD.txt)
Will update this comment when ready ~ 30 mins (on a laptop don't judge my anaemic cpu :( )

**Comment by nicman23** [comment]
Duplicate of #163 closing and copying last log.
