### ISSUE TITLE
World of warcraft 1.12.1 crash on latest

### ISSUE THREAD

**Issue by Altosk** [iXit/Mesa-3D#180]
wow 1.12.1 crashes on start with latest ixit patches. also beyond good and evil crashes as well.

**Comment by axeldavy** [comment]
Weird, our beyond good and evil trace works.

Can you try to bisect find the bad commit for you ?

**Comment by axeldavy** [comment]
alternatively if you have the debug build, you can give the log and the location of the crash.

**Comment by Altosk** [comment]
https://www.sendspace.com/file/2us4xz wow 1.12.1 log

**Comment by Altosk** [comment]
https://www.sendspace.com/file/zll57j beyond good and evil log

**Comment by axeldavy** [comment]
Reading the log it crashes at about the same location, but I fail to see why.
I didn't manage to reproduce with all my apps and my local traces, could it be a problem with your build ?

**Comment by Altosk** [comment]
st/nine: Use ff vertex shader when position_t is used
removing this patch fixes the crashing for me in both games

**Comment by axeldavy** [comment]
Unfortunately I fail to see how the commit could cause the problem.
Have you checked to have the last ixit git ?

Perhaps you can try:
in nine_state.c,

Change the line

sampler_mask = state->vs ? state->vs->sampler_mask : 0;

to 

sampler_mask = state->programmable_vs ? state->vs->sampler_mask : 0;

I don't expect it to fix it, but who knows..

**Comment by Altosk** [comment]
@axeldavy the game complains about not being able to "read" an address when using the original patch.

**Comment by Altosk** [comment]
i looked over the patch and i was wondering when does programmable_vs get set to false or true? I feel like i'm missing it?

**Comment by Altosk** [comment]
no go with that line changed

**Comment by axeldavy** [comment]
Someone reported Beyond good and evil works for him with ixit master.
Perhaps your have some compilation bug ?

**Comment by axeldavy** [comment]
Besides, it is true state->programmable_vs doesn't get reset.
Initially it is worth 0, as everything. We should reset it in some cases.
However in the case of you logs, it crashes too soon to encounter any point where we should reset the value, so it is correctly initialized.

**Comment by Altosk** [comment]
this might be a bug in gcc 5.3.0 but i'm unable to test untill gentoo fixes their live build of llvm as it fails on applying a needed patch. using gcc 4.9.3 fails to build mesa because llvm is built with gcc 5.3.0?

**Comment by sarnex** [comment]
yeah abi broke between 4.9 and 5.3, so i'm guessing thats why mesa wont
build

**Comment by axeldavy** [comment]
As the problem is likely compiler bug, I intend to send the patches anyway for merging.

**Comment by Altosk** [comment]
@sarnex what useflags are u using to build mesa & wine? I've reinstalled
gentoo and now its not running nine at all?

**Comment by sarnex** [comment]
@Altosk https://bpaste.net/show/b33efe3d98a1 https://bpaste.net/show/d5cc421b8f80

**Comment by Altosk** [comment]
@sarnex hm for some reason i'm not getting up to date ixit patches on my mesa build to apply(its doesnt error out)? does the patches folder need to be in /etc or /etc/portage? my bashrc in the portage folder is working because wine is showing staging + nine?

**Comment by sarnex** [comment]
@Altosk you need the ixit use flag with mesa from wine-a-holics and you should get the latest patch from https://github.com/NP-Hardass/mesa-d3d9-patches For wine, you put the staging+nine patch in /etc/portage/patches/app-emulation/wine/ninestaging.patch or whatever it's called

**Comment by Altosk** [comment]
hm something else is wrong then because I've done it all sorts of ways, i'm not getting support for r8g8b8 format from siro's patch which worked before.

**Comment by Altosk** [comment]
this was a compiler error closing
