### ISSUE TITLE
DX9 SDK sample: ConfigSytem crash

### ISSUE THREAD

**Issue by siro20** [iXit/Mesa-3D#181]
The sample allows to choose between programmable and FF shaders and crashes on nine when using FF in nine_state_copy_common().
It doesn't crash on vanilla wine.

**Comment by axeldavy** [comment]
Is it fixed with my last patch ?

**Comment by siro20** [comment]
With latest ixit/master I get "The Direct3D device has a non-zero reference count, meaning some objects were not released." at startup. I can't test the FF shaders until this is fixed.

**Comment by axeldavy** [comment]
Weird, any idea ?

**Comment by siro20** [comment]
Nine creates objects that it shouldn't create, or it increments the refcount even in error cases where object creation failed.

**Comment by siro20** [comment]
Broken with vanilla wine (1.9.1. and 1.9.2), too.

**Comment by axeldavy** [comment]
does the recent patches to fix refcount help ?

**Comment by siro20** [comment]
I reinstalled DXSDK, which allows to start the app. The issue is fixed in latest git.
