### ISSUE TITLE
issues with r8g8b8 patch

### ISSUE THREAD

**Issue by Altosk** [iXit/Mesa-3D#182]
latest mesa+latest nine breaks this patch for me. I've recompiled multiple times but Star Wars Galaxies is crashing on load into the world with every card I have.

**Comment by siro20** [comment]
Where does I crash?
Is it it regression? 
Can you provide provide apitrace that shows the problem?

**Comment by Altosk** [comment]
crashes after selecting a character and trying to load into the game world.
I'm not sure after reading the log if its the user assert failed on first format check or r8g8b8 not being available which it should be. 
i had an apitrace somewhere, I will look for it or make a new one soon.

**Comment by Altosk** [comment]
nine:adapter9:GetAdapterIdentifier: This=0x7c4b5fc8 Flags=0 pIdentifier=0x62b82fd8
nine:adapter9:CheckDeviceFormat: This=0x7c4b5fc8 DeviceType=HAL AdapterFormat=D3DFMT_A8R8G8B8
nine:adapter9:CheckDeviceFormat: User assertion failed: `display_format(AdapterFormat, 0)'

shouldn't a8r8g8b8 be supported?

**Comment by siro20** [comment]
MSDN lists D3DFMT_X8R8G8B8 as valid display format, but D3DFMT_A8R8G8B8 isn't:
http://msdn.microsoft.com/en-us/library/bb172558(v=VS.85).aspx#BackBuffer_or_Display_Formats

**Comment by Altosk** [comment]
the r8g8b8 format works for u siro?

**Comment by siro20** [comment]
r8b8g8 isn't supported by mesa.
The patch "st/nine: Support D3DFMT_R8G8B8" allows to use r8g8b8 for pool scratch.
It fixes a crash in trackmania nations.
Does it fix the issue if you revert the commit "st/nine: Support D3DFMT_R8G8B8" ?

**Comment by Altosk** [comment]
actually the original issues were similar so this should have fixed it. my logs show it being used in the scratch pool.

**Comment by Altosk** [comment]
the game is trying to render/copy from scratch to managed but since the format isn't supported by mesa, its getting a NULL from it. From what I read, this shouldn't be a happen unless it copied. this is probably why when i set r8g8b8 to pipe format x8b8g8r8, the game plays fine.

**Comment by Altosk** [comment]
https://www.sendspace.com/file/7mxybo trace

**Comment by siro20** [comment]
The trace crashes for me after locking RGB8 scratch surface.
I found something strange in the trace you provided:
"Dims=256x32 Format=D3DFMT_R8G8B8 Stride=256"
But the Stride should be 3*256 = 768 !

**Comment by Altosk** [comment]
Odd

**Comment by siro20** [comment]
Can you try this patch ?
https://github.com/siro20/Mesa-3D/commit/42d488f87d9bd47963866ff668310d3d0194d65d

**Comment by Altosk** [comment]
works for me triple-checked it =)

**Comment by axeldavy** [comment]
Can you try current git see if that works ?

**Comment by Altosk** [comment]
yes current git works as well

**Comment by siro20** [comment]
fixed by https://github.com/iXit/Mesa-3D/commit/e186885d5c4bd21769a1b13d0e2f7cc8131d6d77
