### ISSUE TITLE
D3DRS_POINTSCALEENABLE not working properly

### ISSUE THREAD

**Issue by axeldavy** [iXit/Mesa-3D#188]
The msdn documentation is quite unclear about that.

According to:
https://books.google.fr/books?id=kwQuwDmfthwC&pg=PA238&lpg=PA238&dq=calculation+D3DRS_POINTSCALE_A&source=bl&ots=LciewD-dAE&sig=lSi4QUQKmNOovFpkhc5O9zhRji8&hl=fr&sa=X&ved=0ahUKEwiuxra6l-nKAhUCrRoKHR8SBMgQ6AEILDAC#v=onepage&q=calculation%20D3DRS_POINTSCALE_A&f=false

The Calculation should be ViewPort Height * POINTSIZE * 1/ sqrt(POINTSCALE_A + D * POINTSCALE_B + D^2 * POINTSCALE_C)

The calculation done by our code is obscure, so I'm not sure if only the Height multiplication is missing or not.

I did some research, and I cannot tell for sure if it is ok that POINTSCALE does nothing for non-ff, but this is likely.

**Comment by axeldavy** [comment]
Actually it was described here as well:
https://msdn.microsoft.com/fr-fr/library/windows/desktop/bb147281(v=vs.85).aspx

**Comment by axeldavy** [comment]
Fixed

**Comment by Archimagus** [comment]
Care to elaborate on how you fixed this?

**Comment by axeldavy** [comment]
Our implementation was missing the viewport height term. We had already the remaining of the calculation right.
