### ISSUE TITLE
Need For Speed Undercover Crashes

### ISSUE THREAD

**Issue by Ufeldraku** [iXit/Mesa-3D#193]
As the title says, NFSU crashes, sometimes early in the intro chase, or ahead, where the highway goes up, this is the log
`[02/26/16 11:47:06] - Running wine- wineboot (Working directory : /usr/share/playonlinux/python)
fixme:winediag:start_process Wine Staging 1.9.4 is a testing version containing experimental patches.
fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
[02/26/16 11:47:10] - Running wine- winecfg (Working directory : /usr/share/playonlinux/python)
fixme:winediag:start_process Wine Staging 1.9.4 is a testing version containing experimental patches.
fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
[02/26/16 11:51:40] - Running wine- nfs.exe (Working directory : /home/ufeldraku/.PlayOnLinux/wineprefix/NFS/drive_c/Program Files/EA Games/Need for Speed Undercover)
fixme:winediag:start_process Wine Staging 1.9.4 is a testing version containing experimental patches.
fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
fixme:module:load_dll Loader redirect from L"d3d9.dll" to L"d3d9-nine.dll"
fixme:ntdll:__syscall_NtQueryObject Unsupported information class 3
err:rpc:I_RpcGetBuffer no binding
fixme:d3dadapter:d3dadapter9_new [1;32m
Native Direct3D 9 is active.
For more information visit https://wiki.ixit.cz/d3d9[0m
fixme:d3dadapter:d3dadapter9_new [1;32m
Native Direct3D 9 is active.
For more information visit https://wiki.ixit.cz/d3d9[0m
fixme:file:K32EnumPageFilesA (0x17e1f40, 0x23489f4) stub
fixme:file:K32EnumPageFilesA (0x17e1f40, 0x2313310) stub
fixme:d3dadapter:d3dadapter9_new [1;32m
Native Direct3D 9 is active.
For more information visit https://wiki.ixit.cz/d3d9[0m
fixme:d3dadapter:d3dadapter9_new [1;32m
Native Direct3D 9 is active.
For more information visit https://wiki.ixit.cz/d3d9[0m
fixme:d3dadapter:d3dadapter9_new [1;32m
Native Direct3D 9 is active.
For more information visit https://wiki.ixit.cz/d3d9[0m
fixme:d3dadapter:d3dadapter9_new [1;32m
Native Direct3D 9 is active.
For more information visit https://wiki.ixit.cz/d3d9[0m
fixme:d3dadapter:d3dadapter9_new [1;32m
Native Direct3D 9 is active.
For more information visit https://wiki.ixit.cz/d3d9[0m
fixme:d3dadapter:d3dadapter9_new [1;32m
Native Direct3D 9 is active.
For more information visit https://wiki.ixit.cz/d3d9[0m
fixme:ntdll:__syscall_NtQueryInformationProcess (process=0xffffffff) Unimplemented information class: ProcessDeviceMap
fixme:ntdll:__syscall_NtQueryObject Unsupported information class 3
err:rpc:I_RpcGetBuffer no binding
fixme:thread:SetThreadIdealProcessor (0x668): stub
fixme:thread:SetThreadIdealProcessor (0x668): stub
fixme:thread:SetThreadIdealProcessor (0x744): stub
fixme:thread:SetThreadIdealProcessor (0x748): stub
fixme:thread:SetThreadIdealProcessor (0x750): stub
fixme:d3dadapter:d3dadapter9_new [1;32m
Native Direct3D 9 is active.
For more information visit https://wiki.ixit.cz/d3d9[0m
fixme:system:SystemParametersInfoW Unimplemented action: 59 (SPI_SETSTICKYKEYS)
fixme:system:SystemParametersInfoW Unimplemented action: 53 (SPI_SETTOGGLEKEYS)
fixme:system:SystemParametersInfoW Unimplemented action: 51 (SPI_SETFILTERKEYS)
fixme:d3dadapter:DRI3PresentGroup_GetMultiheadCount (0x1ef198), stub!
fixme:d3dadapter:DRI3PresentGroup_GetMultiheadCount (0x1ef198), stub!
fixme:dsound:DSOUND_RecalcFormat Conversion from 4 to 2 channels is not implemented, falling back to stereo
fixme:dsound:DSOUND_RecalcFormat Conversion from 6 to 2 channels is not implemented, falling back to stereo
fixme:dsound:DSOUND_RecalcFormat Conversion from 6 to 2 channels is not implemented, falling back to stereo
fixme:dsound:DSOUND_RecalcFormat Conversion from 6 to 2 channels is not implemented, falling back to stereo
fixme:dsound:DSOUND_RecalcFormat Conversion from 6 to 2 channels is not implemented, falling back to stereo
fixme:dsound:DSOUND_RecalcFormat Conversion from 6 to 2 channels is not implemented, falling back to stereo
fixme:dsound:DSOUND_RecalcFormat Conversion from 6 to 2 channels is not implemented, falling back to stereo
fixme:dsound:DSOUND_RecalcFormat Conversion from 4 to 2 channels is not implemented, falling back to stereo
fixme:dsound:DSOUND_RecalcFormat Conversion from 4 to 2 channels is not implemented, falling back to stereo
fixme:dsound:DSOUND_RecalcFormat Conversion from 4 to 2 channels is not implemented, falling back to stereo
fixme:dsound:DSOUND_RecalcFormat Conversion from 4 to 2 channels is not implemented, falling back to stereo
fixme:dsound:DSOUND_RecalcFormat Conversion from 4 to 2 channels is not implemented, falling back to stereo
fixme:dsound:DSOUND_RecalcFormat Conversion from 6 to 2 channels is not implemented, falling back to stereo
fixme:dsound:DSOUND_RecalcFormat Conversion from 6 to 2 channels is not implemented, falling back to stereo
fixme:dsound:DSOUND_RecalcFormat Conversion from 6 to 2 channels is not implemented, falling back to stereo
fixme:dsound:DSOUND_RecalcFormat Conversion from 6 to 2 channels is not implemented, falling back to stereo
fixme:dsound:DSOUND_RecalcFormat Conversion from 6 to 2 channels is not implemented, falling back to stereo
fixme:thread:SetThreadIdealProcessor (0x788): stub
fixme:win:RegisterDeviceNotificationA (hwnd=0x20054, filter=0x237f5b8,flags=0x00000000) returns a fake device notification handle!
fixme:wbemprox:client_security_SetBlanket 0x727577a0, 0x216bb8, 10, 0, (null), 3, 3, (nil), 0x00000000
fixme:wbemprox:client_security_Release 0x727577a0
fixme:wbemprox:enum_class_object_Next timeout not supported
fixme:thread:SetThreadIdealProcessor (0x7d4): stub
EE r600_texture.c:1062 r600_texture_transfer_map - failed to create temporary texture to hold untiled copy
EE r600_texture.c:1062 r600_texture_transfer_map - failed to create temporary texture to hold untiled copy
EE r600_texture.c:1062 r600_texture_transfer_map - failed to create temporary texture to hold untiled copy
EE r600_texture.c:1062 r600_texture_transfer_map - failed to create temporary texture to hold untiled copy
EE r600_texture.c:1062 r600_texture_transfer_map - failed to create temporary texture to hold untiled copy
EE r600_texture.c:1062 r600_texture_transfer_map - failed to create temporary texture to hold untiled copy
EE r600_texture.c:1062 r600_texture_transfer_map - failed to create temporary texture to hold untiled copy
EE r600_texture.c:1062 r600_texture_transfer_map - failed to create temporary texture to hold untiled copy
EE r600_texture.c:1062 r600_texture_transfer_map - failed to create temporary texture to hold untiled copy
EE r600_texture.c:1062 r600_texture_transfer_map - failed to create temporary texture to hold untiled copy
EE r600_texture.c:1062 r600_texture_transfer_map - failed to create temporary texture to hold untiled copy
EE r600_texture.c:1062 r600_texture_transfer_map - failed to create temporary texture to hold untiled copy
EE r600_texture.c:1062 r600_texture_transfer_map - failed to create temporary texture to hold untiled copy
EE r600_texture.c:1062 r600_texture_transfer_map - failed to create temporary texture to hold untiled copy
EE r600_texture.c:1062 r600_texture_transfer_map - failed to create temporary texture to hold untiled copy
EE r600_texture.c:1062 r600_texture_transfer_map - failed to create temporary texture to hold untiled copy
wine: Unhandled page fault on read access to 0x96dfb120 at address 0xf7534630 (thread 004c), starting debugger...
Unhandled exception: page fault on read access to 0x96dfb120 in 32-bit code (0xf7534630).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:f7534630 ESP:0914dfe0 EBP:96dfb120 EFLAGS:00010206(  R- --  I   - -P- )
 EAX:96dfb120 EBX:7cf7a000 ECX:00000080 EDX:72a86000
 ESI:00000001 EDI:72a86000
Stack dump:
0x0914dfe0:  7cf7a000 7caaea79 72a86000 96dfb120
0x0914dff0:  00000080 00000000 00000000 00000020
0x0914e000:  00000080 00000020 00000000 00000000
0x0914e010:  7caae969 96dfb120 72a86000 00000001
0x0914e020:  00000001 7caaeb6e 72a86000 00000001
0x0914e030:  00000100 00000000 00000000 00000020
000c: sel=0067 base=00000000 limit=00000000 32-bit r-x
Backtrace:
=>0 0xf7534630 __memcpy_ssse3_rep+0x40() in libc.so.6 (0x96dfb120)
  1 0x7caaea79 in d3dadapter9.so.1 (+0x97a78) (0x96dfb120)
  2 0x7caaeb6e in d3dadapter9.so.1 (+0x97b6d) (0x00000001)
  3 0x7cab291d in d3dadapter9.so.1 (+0x9b91c) (0x0914e12c)
  4 0x7cba8494 in d3dadapter9.so.1 (+0x191493) (0x00000080)
  5 0x7cb1fdc6 in d3dadapter9.so.1 (+0x108dc5) (0x48c13040)
  6 0x7cb993b0 in d3dadapter9.so.1 (+0x1823af) (0x7bdd0d14)
  7 0x7cb9a32c in d3dadapter9.so.1 (+0x18332b) (0x7bdcf580)
  8 0x7cb2766a in d3dadapter9.so.1 (+0x110669) (0x0914e37c)
  9 0x006a1d0e in nfs (+0x2a1d0d) (0x06148020)
  10 0x0614b0a8 (0x00c24330)
  11 0x007aa600 in nfs (+0x3aa5ff) (0x007a7ac0)
  12 0xff6af8e4 (0x83ec8b55)
0xf7534630 __memcpy_ssse3_rep+0x40 in libc.so.6: repe movq	0x0(%eax),%mm0
Modules:
Module	Address			Debug info	Name (181 modules)
PE	  230000-  246000	Deferred        xinput1_3
PE	  400000- 1e71000	Export          nfs
PE	 2380000- 26ef000	Deferred        d3dx9_34
PE	10000000-100db000	Deferred        paul
ELF	48777000-488ad000	Deferred        opengl32<elf>
  \-PE	487a0000-488ad000	\               opengl32
ELF	488af000-489f9000	Deferred        wined3d<elf>
  \-PE	488c0000-489f9000	\               wined3d
PE	70bd0000-70c14000	Deferred        shlwapi
ELF	70cd7000-70cff000	Deferred        dxgi<elf>
  \-PE	70ce0000-70cff000	\               dxgi
ELF	7271f000-72758000	Deferred        wbemprox<elf>
  \-PE	72730000-72758000	\               wbemprox
ELF	72a3f000-72a46000	Deferred        libnss_dns.so.2
ELF	72a67000-72a7a000	Deferred        libnss_myhostname.so.2
ELF	76af7000-76b12000	Deferred        libnsl.so.1
ELF	76b17000-76ba6000	Deferred        libvorbisenc.so.2
ELF	76ba7000-76bd6000	Deferred        libvorbis.so.0
ELF	76bd7000-76c5d000	Deferred        libflac.so.8
ELF	76c5f000-76c8b000	Deferred        liblzma.so.5
ELF	76c8f000-76d1a000	Deferred        libsndfile.so.1
ELF	76d1f000-76dae000	Deferred        libsystemd.so.0
ELF	76daf000-76e0b000	Deferred        libdbus-1.so.3
ELF	76e0f000-76e9a000	Deferred        libpulsecommon-8.0.so
ELF	76e9f000-76efa000	Deferred        libpulse.so.0
ELF	7743f000-77489000	Deferred        dinput<elf>
  \-PE	77450000-77489000	\               dinput
ELF	7901f000-7b7fa000	Deferred        libllvm.so.3.7
ELF	7b800000-7ba68000	Deferred        kernel32<elf>
  \-PE	7b810000-7ba68000	\               kernel32
ELF	7ba7f000-7ba87000	Deferred        libogg.so.0
ELF	7bc00000-7bcfb000	Deferred        ntdll<elf>
  \-PE	7bc20000-7bcfb000	\               ntdll
ELF	7bf00000-7bf04000	Deferred        <wine-loader>
ELF	7bf0f000-7bf39000	Deferred        winepulse<elf>
  \-PE	7bf20000-7bf39000	\               winepulse
ELF	7bf6f000-7bf9b000	Deferred        msvfw32<elf>
  \-PE	7bf70000-7bf9b000	\               msvfw32
ELF	7bf9f000-7bfd7000	Deferred        uxtheme<elf>
  \-PE	7bfb0000-7bfd7000	\               uxtheme
ELF	7bfd7000-7c0d2000	Deferred        comctl32<elf>
  \-PE	7bfe0000-7c0d2000	\               comctl32
ELF	7c0d7000-7c0fa000	Deferred        mmdevapi<elf>
  \-PE	7c0e0000-7c0fa000	\               mmdevapi
ELF	7c207000-7c20e000	Deferred        libasyncns.so.0
ELF	7c337000-7c37c000	Deferred        usp10<elf>
  \-PE	7c340000-7c37c000	\               usp10
ELF	7c37f000-7c3f9000	Deferred        riched20<elf>
  \-PE	7c390000-7c3f9000	\               riched20
ELF	7c407000-7c414000	Deferred        libjson-c.so.2
ELF	7c41f000-7c4aa000	Deferred        libgmp.so.10
ELF	7c4af000-7c4e5000	Deferred        libhogweed.so.4
ELF	7c4e7000-7c525000	Deferred        libnettle.so.6
ELF	7c527000-7c53c000	Deferred        libtasn1.so.6
ELF	7c53f000-7c573000	Deferred        libidn.so.11
ELF	7c577000-7c5d9000	Deferred        libp11-kit.so.0
ELF	7c5df000-7c611000	Deferred        libcrypt.so.1
ELF	7c617000-7c764000	Deferred        libgnutls.so.30
ELF	7c767000-7c7eb000	Deferred        libcups.so.2
ELF	7c827000-7c866000	Deferred        winspool<elf>
  \-PE	7c830000-7c866000	\               winspool
ELF	7c867000-7c86d000	Deferred        libtxc_dxtn.so
ELF	7c9a7000-7ca15000	Deferred        libncursesw.so.6
ELF	7ca17000-7cfca000	Dwarf           d3dadapter9.so.1
ELF	7d04f000-7d068000	Deferred        libresolv.so.2
ELF	7d06f000-7d085000	Deferred        libgpg-error.so.0
ELF	7d087000-7d0a1000	Deferred        libgcc_s.so.1
ELF	7d21f000-7d23b000	Deferred        libelf.so.1
ELF	7d23f000-7d24a000	Deferred        libdrm_amdgpu.so.1
ELF	7d24f000-7d25d000	Deferred        libdrm_radeon.so.1
ELF	7d25f000-7d269000	Deferred        libdrm_nouveau.so.2
ELF	7d26f000-7d31e000	Deferred        libgcrypt.so.20
ELF	7d327000-7d32c000	Deferred        libcap.so.2
ELF	7d32f000-7d350000	Deferred        libudev.so.1
ELF	7d55f000-7d59b000	Deferred        libfontconfig.so.1
ELF	7d59f000-7d614000	Deferred        libpcre.so.1
ELF	7d617000-7d73d000	Deferred        libglib-2.0.so.0
ELF	7d73f000-7d7a9000	Deferred        libharfbuzz.so.0
ELF	7d7af000-7d7ec000	Deferred        libpng16.so.16
ELF	7d7ef000-7d800000	Deferred        libbz2.so.1.0
ELF	7d807000-7d8cb000	Deferred        libfreetype.so.6
ELF	7d8cf000-7d8e2000	Deferred        libxi.so.6
ELF	7d8e7000-7d8eb000	Deferred        libxcomposite.so.1
ELF	7d8ef000-7d8fc000	Deferred        libxrandr.so.2
ELF	7d8ff000-7d90b000	Deferred        libxrender.so.1
ELF	7d90f000-7d913000	Deferred        libxinerama.so.1
ELF	7d917000-7d922000	Deferred        libxcursor.so.1
ELF	7d94f000-7d9e0000	Deferred        winex11<elf>
  \-PE	7d960000-7d9e0000	\               winex11
ELF	7d9e7000-7da03000	Deferred        wsock32<elf>
  \-PE	7d9f0000-7da03000	\               wsock32
ELF	7da07000-7da31000	Deferred        iphlpapi<elf>
  \-PE	7da10000-7da31000	\               iphlpapi
ELF	7da37000-7daf0000	Deferred        winmm<elf>
  \-PE	7da40000-7daf0000	\               winmm
ELF	7daf7000-7db47000	Deferred        dsound<elf>
  \-PE	7db00000-7db47000	\               dsound
ELF	7db47000-7db7d000	Deferred        wintrust<elf>
  \-PE	7db50000-7db7d000	\               wintrust
ELF	7db7f000-7db93000	Deferred        psapi<elf>
  \-PE	7db80000-7db93000	\               psapi
ELF	7db97000-7dbae000	Deferred        libz.so.1
ELF	7dbb7000-7dbe6000	Deferred        netapi32<elf>
  \-PE	7dbc0000-7dbe6000	\               netapi32
ELF	7dbe7000-7dc4e000	Deferred        dbghelp<elf>
  \-PE	7dbf0000-7dc4e000	\               dbghelp
ELF	7dc4f000-7dc6a000	Deferred        imagehlp<elf>
  \-PE	7dc50000-7dc6a000	\               imagehlp
ELF	7dc6f000-7dd3e000	Deferred        crypt32<elf>
  \-PE	7dc80000-7dd3e000	\               crypt32
ELF	7dd3f000-7de94000	Deferred        msvcp80<elf>
  \-PE	7dd80000-7de94000	\               msvcp80
ELF	7de97000-7df5e000	Deferred        msvcr80<elf>
  \-PE	7deb0000-7df5e000	\               msvcr80
ELF	7df5f000-7e090000	Deferred        oleaut32<elf>
  \-PE	7df80000-7e090000	\               oleaut32
ELF	7e097000-7e0d0000	Deferred        ws2_32<elf>
  \-PE	7e0a0000-7e0d0000	\               ws2_32
ELF	7e0d7000-7e0fb000	Deferred        imm32<elf>
  \-PE	7e0e0000-7e0fb000	\               imm32
ELF	7e0ff000-7e3a0000	Deferred        shell32<elf>
  \-PE	7e110000-7e3a0000	\               shell32
ELF	7e3a7000-7e415000	Deferred        setupapi<elf>
  \-PE	7e3b0000-7e415000	\               setupapi
ELF	7e417000-7e497000	Deferred        rpcrt4<elf>
  \-PE	7e420000-7e497000	\               rpcrt4
ELF	7e497000-7e5cf000	Deferred        ole32<elf>
  \-PE	7e4b0000-7e5cf000	\               ole32
ELF	7e5cf000-7e5eb000	Deferred        dinput8<elf>
  \-PE	7e5d0000-7e5eb000	\               dinput8
ELF	7e5ef000-7e6ac000	Deferred        msvcrt<elf>
  \-PE	7e600000-7e6ac000	\               msvcrt
ELF	7e6af000-7e819000	Deferred        user32<elf>
  \-PE	7e6c0000-7e819000	\               user32
ELF	7e81f000-7e93b000	Deferred        gdi32<elf>
  \-PE	7e830000-7e93b000	\               gdi32
ELF	7e93f000-7e9b5000	Deferred        advapi32<elf>
  \-PE	7e950000-7e9b5000	\               advapi32
ELF	7e9b7000-7e9c0000	Deferred        librt.so.1
ELF	7e9c7000-7e9d0000	Deferred        libffi.so.6
ELF	7e9d7000-7e9de000	Deferred        libxdmcp.so.6
ELF	7e9df000-7e9e3000	Deferred        libxau.so.6
ELF	7e9e7000-7e9ee000	Deferred        libxxf86vm.so.1
ELF	7e9ef000-7ea0a000	Deferred        libxcb-glx.so.0
ELF	7ea0f000-7ea15000	Deferred        libxfixes.so.3
ELF	7ea17000-7ea1b000	Deferred        libxdamage.so.1
ELF	7ea1f000-7ea3b000	Deferred        libglapi.so.0
ELF	7ea3f000-7ea51000	Deferred        libdrm.so.2
ELF	7ea57000-7ea80000	Deferred        libexpat.so.1
ELF	7ea87000-7ea98000	Deferred        libwayland-server.so.0
ELF	7ea9f000-7eaad000	Deferred        libwayland-client.so.0
ELF	7eaaf000-7eabe000	Deferred        libgbm.so.1
ELF	7eabf000-7eac2000	Deferred        libxshmfence.so.1
ELF	7eac7000-7eacf000	Deferred        libxcb-sync.so.1
ELF	7eacf000-7ead4000	Deferred        libxcb-shape.so.0
ELF	7ead7000-7eae2000	Deferred        libxcb-render.so.0
ELF	7eae7000-7eaf7000	Deferred        libxcb-randr.so.0
ELF	7eaf7000-7eafd000	Deferred        libxcb-dri2.so.0
ELF	7eaff000-7eb26000	Deferred        libxcb.so.1
ELF	7eb27000-7eb2b000	Deferred        libxcb-dri3.so.0
ELF	7eb2f000-7eb33000	Deferred        libxcb-present.so.0
ELF	7eb37000-7ec86000	Deferred        libx11.so.6
ELF	7ec87000-7ec9c000	Deferred        libxext.so.6
ELF	7ec9f000-7ed4a000	Deferred        libgl.so.1
ELF	7ed4f000-7ed81000	Deferred        libegl.so.1
ELF	7ed87000-7ed9b000	Deferred        shfolder<elf>
  \-PE	7ed90000-7ed9b000	\               shfolder
ELF	7ed9f000-7edb9000	Deferred        version<elf>
  \-PE	7eda0000-7edb9000	\               version
ELF	7ef57000-7ef6a000	Deferred        libnss_files.so.2
ELF	7ef6f000-7efc4000	Deferred        libm.so.6
ELF	7efc7000-7efca000	Deferred        libx11-xcb.so.1
ELF	7efcf000-7efd8000	Deferred        libxcb-xfixes.so.0
ELF	7efdf000-7f000000	Deferred        d3d9-nine<elf>
  \-PE	7eff0000-7eff4000	\               d3d9
ELF	f73c7000-f73cc000	Deferred        libdl.so.2
ELF	f7407000-f75bc000	Dwarf           libc.so.6
ELF	f75bf000-f75dc000	Deferred        libpthread.so.0
ELF	f75df000-f77a9000	Dwarf           libwine.so.1
ELF	f77af000-f77d3000	Deferred        ld-linux.so.2
ELF	f77d8000-f77d9000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
00000008 (D) C:\Program Files\EA Games\Need for Speed Undercover\nfs.exe
	0000005d    0
	0000005b   15
	00000058   15
	00000056   15
	00000055    0
	00000054    0
	00000053    2
	00000052    2
	00000051    2
	00000050    2
	0000004f    0
	0000004e    1
	0000004d    2
	0000004c    0 <==
	0000004b    0
	0000003f    0
	00000009    0
0000000e services.exe
	0000004a    0
	0000001d    0
	00000014    0
	00000010    0
	0000000f    0
00000012 winedevice.exe
	0000001a    0
	00000019    0
	00000018    0
	00000013    0
0000001b plugplay.exe
	00000020    0
	0000001f    0
	0000001c    0
00000035 explorer.exe
	0000003a    0
	00000039    0
	00000038    0
	00000037    0
	00000036    0
System information:
    Platform: i386
    Version: Windows XP
`

**Comment by axeldavy** [comment]
Can you describe more your config ?

I have already played that game on nine fine with radeonsi.

**Comment by Ufeldraku** [comment]
AMD Radeon HD 7520g 
AMD A6-4440M x2 @ 2.7GHz
6GB RAM DDR3
Radeon Drivers [R600]
Kernel 4.4.1-2-ARCH
It's a laptop.
HP Pavilion G4-2205la, BTW, I can't recompile Mesa because my laptop overheats and the last time it hanged.

**Comment by Ufeldraku** [comment]
I think this is the issue, however, Dunno how to fix it 
`EE r600_texture.c:1062 r600_texture_transfer_map - failed to create temporary texture to hold untiled copy`

**Comment by axeldavy** [comment]
Perhaps you don't have enough graphic memory.

Have you tried both cards ?

**Comment by Ufeldraku** [comment]
Both Cards, I just have one, plus It ran fine in Windows, tested it yesterday, Almost everything on High

**Comment by axeldavy** [comment]
ok, a moment I thought you had both the card coming with A6-4440M and an HD 7520g.

Perhaps under windows more GTT space is allocated ? There must be some way to tune the space allocated for linux as well. One thing also is that in nine we don't implement a specific feature that reduces memory usage when needed (at cost of some performance), perhaps that's why it runs on windows and not here. I guess it doesn't run either with normal wine ?

**Comment by Ufeldraku** [comment]
It runs fine in CSMT, but yeah, less FPS

**Comment by axeldavy** [comment]
wine doesn't implement the memory feature either, so perhaps something else ?

With GALLIUM_HUD=GTT-usage you can compare memory usage.

**Comment by Ufeldraku** [comment]
Uhm, I have to do some stuff, 
It goes in the "Debug" Field of PlayonLinux or in the "Command to enter before execution" one, [My POL is in spanish so, yeah, I'm not the best one translating stuff :P

**Comment by Ufeldraku** [comment]
Uh, I put GALLIUM_HUD=GTT-usage in both field mentioned above, but It crashed BEFORE showing the intro sequence. Maybe my card is shitty.

**Comment by Ufeldraku** [comment]
Tried with normal wine, Crashed without showing the window...... Such a let down

**Comment by Ufeldraku** [comment]
Closing, Going to install Windows 10 tomorrow.

**Comment by axeldavy** [comment]
weird

**Comment by Ufeldraku** [comment]
I'm going to try it there, to see if me playing some hours make it crash, I did not want to be rude, English is not my native language.
