### ISSUE TITLE
Game renderring totally wrong on debian8 testing, buf correct on Ubuntu15.10 (self compiled wine)

### ISSUE THREAD

**Issue by andysendo** [iXit/Mesa-3D#194]
Hi, i compiled mesa (debian8 testing, nine and r600-llvm-compiler options enabled) + wine1.9.3 (offical source, d3dadapter patched), testing game got totally wrong renderring as attachment bellow. Then i copy the self-compiled wine binarry to Ubuntu15.10 (mesa is ppa Oibaf as recommend), tested same game got correct renderring.

I also tested same game with wine 1.9.2 (ppa Nick Sarnie as recommend), got same problem.(AKA correct on  Ubuntu15.10, wrong on debian8 testing using uncompressed binarry).

So i don't think i miss something when compilling, package dependency should be fine, but i cant find out whats going on. (WINEDEBUG=+d3dadapter9,+d3d9 got nothing)

Thanks.

**Comment by andysendo** [comment]
Cant submit attachment screnshots ?

**Comment by siro20** [comment]
It's WINEDEBUG=d3dadapter
WINEDEBUG=d3d9 has no effect if you are using nine.

**Comment by andysendo** [comment]
So WINEDEBUG=d3dadapter i got logs like :
trace:d3dadapter:present_create_adapter9 Created ID3DAdapter9 with fd 13
trace:d3dadapter:d3dadapter9_GetAdapterIdentifier DeviceName overriden: \\.\DISPLAY1
trace:d3dadapter:d3dadapter9_GetAdapterModeCount 22 modes.
trace:d3dadapter:d3dadapter9_AddRef 0x131ba0 increasing refcount to 3.
trace:d3dadapter:d3dadapter9_Release 0x131ba0 decreasing refcount to 2.
trace:d3dadapter:d3dadapter9_AddRef 0x131ba0 increasing refcount to 3.
trace:d3dadapter:get_d3d_drawable No d3d_drawable attached to hwnd 0x20054, creating one.
trace:d3dadapter:d3dadapter9_AddRef 0x131ba0 increasing refcount to 3.
trace:d3dadapter:d3dadapter9_Release 0x131ba0 decreasing refcount to 2.

But debian8 testing and Ubuntu15.10 got same logs, so still can't find out whats going on.

**Comment by axeldavy** [comment]
Well I guess it's just the two distro have different mesa versions.

Unless Ubuntu 15.10 has older mesa than debian8 testing (and then it would be regression), please close this bug report.
