### ISSUE TITLE
World of Warships geometry issues

### ISSUE THREAD

**Issue by Oblit03** [iXit/Mesa-3D#195]
A game patch has resulted in ships and land rendering incorrectly on radeon with nine. They do appear to render correctly on wined3d.

**The following images show the problem:**
![shot-16 03 02_23 52 15-0155](https://cloud.githubusercontent.com/assets/17604550/13480281/aa14d5ce-e0d4-11e5-9fb0-4dd405c51cf1.jpg)
Looking away from ships:
![shot-16 03 03_15 42 39-0629](https://cloud.githubusercontent.com/assets/17604550/13509427/3f096c22-e183-11e5-88b8-96850225bdb3.jpg)

Projectiles don't render (or seem to render relative to screen space) and the cursor also doesn't render on nine but render fine on wined3d.

**Log segment (`NINEDEBUG=all` + `WINEDEBUG=d3dadapter`):**
[nineWoWS.txt](https://github.com/iXit/Mesa-3D/files/155949/nineWoWS.txt)

[Nine apitrace](https://mega.nz/#!yl8CwY6S!z37Y2ZFfIjEqtFmdDNqzj0sNuIMZr9qbySbJCPJA7BE)

**Setup:**
Kubuntu 15.10 (64-bit)
Kernel 4.2.0-30
Wine 1.9.2 (32-bit)

**Hardware:**
Intel i7 3770
Asus P8Z77-M
Radeon HD6950 2GB (Asus)
16 GB RAM

**Tested using the following:**
[Oibaf PPA](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers)
[Sarnex iXit](https://launchpad.net/~commendsarnex/+archive/ubuntu/ixitmaster)
[Sarnex Wine](https://launchpad.net/~commendsarnex/+archive/ubuntu/winedri3)
Also tested using locally compiled mesa from this repository.

The bugs are present on nine regardless of version and are even present on versions that worked before. None of the R600_DEBUG options that I have tried have had any effect on it (nosb,notiling,nodcc,nodma,no2d,noinvalrange)

**///**
**There is another problem that may be relevant:**
wined3d requires `R600_DEBUG=notiling` or some UI elements are rendered incorrectly and may cause a crash:

../../../../../../src/gallium/drivers/r600/r600_blit.c:359: r600_decompress_color_textures: Assertion `tex->cmask.size' failed.

**Log:** 
[wined3dWoWS.txt](https://github.com/iXit/Mesa-3D/files/159557/wined3dWoWS.txt)

This means any wined3d trace will either have to be run on an old mesa or run with notiling enabled as the crash occurs during loading.

wined3d appears to function normally up to and including commit [4a448a6](https://github.com/iXit/Mesa-3D/commit/4a448a63adbbece1d9bddacd9428aad7cc68a628) on February 3rd. Subsequent changes to st_cb_texture.c cause the above error and I've been unable to determine which or if it is related to another file.
**///**

**Comment by axeldavy** [comment]
So it used to be correct before ?

**Comment by Oblit03** [comment]
The game was mostly functional with nine after the games open beta ended. The cursor and projectiles have never worked as far as I know. 

This isn't the first time this has occurred as the game originally appeared as the images show. A game patch seemed to fix those issues and a recent one has brought them back again. As far as I know it is unrelated to any nine changes as compiling mesa+nine from January this year results in the same problems, when it was originally functional during that time.

The compressed texture crash doesn't occur under nine, at least from the testing I've done.

Pontostroy [made a video](http://www.gearsongallium.com/?p=2580) some time back and it shows how it used to look before returning to this broken state.

If a wined3d trace would be useful I can attempt to create one as the game does load on low settings, but it does eventually crash.

**Comment by axeldavy** [comment]
Have you tried to find exactly the bad commit for wined3d ? saying that "commit 4a448a6 on February 3rd" works is not much help. Could you bisect find the first bad commit ?

**Comment by axeldavy** [comment]
If you replay your trace with a mesa that version that was working, does it work ? Perhaps the game does something illegal that apitrace can't capture.

**Comment by Oblit03** [comment]
git bisect output:

> 757071ca7cdda12d2974614f9a9d02d5a834f38c is the first bad commit
> commit 757071ca7cdda12d2974614f9a9d02d5a834f38c
> Author: Fredrik Höglund <fredrik@kde.org>
> Date:   Fri Jan 8 16:31:14 2016 -0500
> 
>     st/mesa: Accelerate PBO uploads
>     
>     Create a PIPE_BUFFER sampler view on the pixel-unpack buffer, and draw
>     the image on the texture with a fragment shader that maps fragment
>     coordinates to buffer coordinates.
>     
>     Modifications by Nicolai Hähnle:
>     - various cleanups and fixes (e.g. error handling, corner cases)
>     - split try_pbo_upload into two functions, which will allow code to be
>       shared with compressed texture uploads
>     - modify the source format selection to only test for support against
>       the PIPE_BUFFER target
>     
>     v2:
>     - update handling of TGSI_SEMANTIC_POSITION for recent changes in master
>     - MaxTextureBufferSize is number of texels, not bytes (Ilia Mirkin)
>     - only enable when integers are supported (Marek Olšák)
>     - try harder to hit the TextureBufferOffsetAlignment
>     - remove unnecessary MOV from the fragment shader
>     
>     Reviewed-by: Edward O'Callaghan <eocallaghan@alterapraxis.com>
> 
> :040000 040000 6dd3b195435a28c8dc9491eac54aa2692a5306d5 84e562ad440d978b3d17d3cad596281b20970d28 M      src

The traces appear the same on both the recent and the previously working mesa versions (triangles everywhere on nine, no land/ships/sky on wined3d). 

wined3d traces replayed with nine show triangles across the screen.
nine traces replayed with nine show triangles across the screen.
wined3d traces replayed with wined3d show missing land/ships/sky.
nine traces replayed with wined3d show missing land/ships/sky.

wined3d in-game:
![shot-16 03 09_21 06 45-0342](https://cloud.githubusercontent.com/assets/17604550/13650578/46c5d75e-e63b-11e5-8f8e-3968d884d11c.jpg)

wined3d qapitrace:
![snapshot153](https://cloud.githubusercontent.com/assets/17604550/13650599/57e4b64a-e63b-11e5-8997-31698082ce18.png)

**Comment by axeldavy** [comment]
Could you try the game after changing this function
https://github.com/iXit/Mesa-3D/blob/master/src/gallium/state_trackers/nine/nine_pipe.h#L47

to return PIPE_TRANSFER_READ_WRITE always ?

**Comment by Oblit03** [comment]
The game now renders as shown in [pontostroy's video](http://www.gearsongallium.com/?p=2580).
The traces appear to remain the same as described above.

I'll upload 2 new traces (nine/wined3d) shortly.

**Comment by axeldavy** [comment]
I'm afraid traces can't capture what the game is doing

**Comment by Oblit03** [comment]
Would a log be useful?

**Comment by axeldavy** [comment]
Can you try the following ?
`static inline unsigned d3dlock_buffer_to_pipe_transfer_usage(DWORD Flags)
{
    unsigned usage;

    if (Flags & D3DLOCK_DISCARD)
        usage = PIPE_TRANSFER_WRITE | PIPE_TRANSFER_DISCARD_WHOLE_RESOURCE;
    else
    /*if (Flags & D3DLOCK_READONLY)
        usage = PIPE_TRANSFER_READ;
    else*/
        usage = PIPE_TRANSFER_READ_WRITE;

    if (Flags & D3DLOCK_NOOVERWRITE)
        usage = (PIPE_TRANSFER_UNSYNCHRONIZED |
                 PIPE_TRANSFER_DISCARD_RANGE | usage) & ~PIPE_TRANSFER_READ;
    else
    if (Flags & D3DLOCK_DONOTWAIT)
        usage |= PIPE_TRANSFER_DONTBLOCK;

    /*
    if (Flags & D3DLOCK_NO_DIRTY_UPDATE)
        usage |= PIPE_TRANSFER_FLUSH_EXPLICIT;
    */

    return usage;
}`

**Comment by axeldavy** [comment]
The fact it works with PIPE_TRANSFER_READ_WRITE is quite some indicator.

We must find down which case exactly is fixed with that flag. We'll have to find exactly what is the value of 'Flags' that required PIPE_TRANSFER_READ_WRITE to work properly, then find out which Pool and formats were the source, etc. Then we can deduce exactly what is happening and how to workaround properly.

**Comment by axeldavy** [comment]
If the propose change didn't help, try instead to comment the part
if (Flags & D3DLOCK_DISCARD)
    usage = PIPE_TRANSFER_WRITE | PIPE_TRANSFER_DISCARD_WHOLE_RESOURCE;
else

**Comment by Oblit03** [comment]
Commenting out 
```
if (Flags & D3DLOCK_READONLY)
    usage = PIPE_TRANSFER_READ;
else
```
works.

Commenting out 
```
if (Flags & D3DLOCK_DISCARD)
usage = PIPE_TRANSFER_WRITE | PIPE_TRANSFER_DISCARD_WHOLE_RESOURCE;
else
```
doesn't work.

**Comment by axeldavy** [comment]
Can you undo your changes and try in buffer9.c:

There are some lines

info->usage = PIPE_USAGE_DEFAULT;
    if (Usage & D3DUSAGE_DYNAMIC)
        info->usage = PIPE_USAGE_STREAM;
    else if (Pool == D3DPOOL_SYSTEMMEM)
        info->usage = PIPE_USAGE_STAGING;

Remove them and manually set info->usage to one of the three values.

See if one value helps.

**Comment by axeldavy** [comment]
Last thing to try (I expect it should fix the issue) is to add at the beginning of NineBuffer9_ctor

after user_assert(Pool != D3DPOOL_SCRATCH, D3DERR_INVALIDCALL);

add

Pool = D3DPOOL_MANAGED;

**Comment by Oblit03** [comment]
Results:

`info->usage = PIPE_USAGE_DEFAULT;`
No change
Triangles blocking view

`info->usage = PIPE_USAGE_STREAM;`
Functions normally

`info->usage = PIPE_USAGE_STAGING;`
Functions normally

`Pool = D3DPOOL_MANAGED`
Does not function(Crashes on loading)

Logs:
[*** Error in `WorldOfWarships.exe': corrupted double-linked list: 0x64362321 ***](https://github.com/iXit/Mesa-3D/files/167986/WoWS-D3DPOOL_M-Log1.txt)

[*** Error in `WorldOfWarships.exe': malloc(): memory corruption (fast): 0xe1db2748 ***](https://github.com/iXit/Mesa-3D/files/167987/WoWS-D3DPOOL_M-Log2.txt)

[Stalls at: nine:resource9:ctor: (0xe7b1ccd0) Creating pipe_resource.](https://github.com/iXit/Mesa-3D/files/167988/WoWS-D3DPOOL_M-Log3.txt)

[Stalls later in the loading process](https://github.com/iXit/Mesa-3D/files/168024/WoWS-D3DPOOL_M-Log4.txt)

Code:
```
NineBuffer9_ctor( struct NineBuffer9 *This,
                        struct NineUnknownParams *pParams,
                        D3DRESOURCETYPE Type,
                        DWORD Usage,
                        UINT Size,
                        D3DPOOL Pool )
{
    struct pipe_resource *info = &This->base.info;
    HRESULT hr;

    DBG("This=%p Size=0x%x Usage=%x Pool=%u\n", This, Size, Usage, Pool);

    user_assert(Pool != D3DPOOL_SCRATCH, D3DERR_INVALIDCALL);
    
    Pool = D3DPOOL_MANAGED;

    This->maps = MALLOC(sizeof(struct pipe_transfer *));
    if (!This->maps)
        return E_OUTOFMEMORY;
    This->nmaps = 0;
    This->maxmaps = 1;
    This->size = Size;

    This->pipe = pParams->device->pipe;

    info->screen = pParams->device->screen;
    info->target = PIPE_BUFFER;
    info->format = PIPE_FORMAT_R8_UNORM;
    info->width0 = Size;
    info->flags = 0;

    info->bind = PIPE_BIND_VERTEX_BUFFER | PIPE_BIND_TRANSFER_WRITE;
    if (!(Usage & D3DUSAGE_WRITEONLY))
        info->bind |= PIPE_BIND_TRANSFER_READ;

    info->usage = PIPE_USAGE_DEFAULT;
    if (Usage & D3DUSAGE_DYNAMIC)
        info->usage = PIPE_USAGE_STREAM;
    else if (Pool == D3DPOOL_SYSTEMMEM)
        info->usage = PIPE_USAGE_STAGING;

    /* if (pDesc->Usage & D3DUSAGE_DONOTCLIP) { } */
    /* if (pDesc->Usage & D3DUSAGE_NONSECURE) { } */
    /* if (pDesc->Usage & D3DUSAGE_NPATCHES) { } */
    /* if (pDesc->Usage & D3DUSAGE_POINTS) { } */
    /* if (pDesc->Usage & D3DUSAGE_RTPATCHES) { } */
    if (Usage & D3DUSAGE_SOFTWAREPROCESSING)
        DBG("Application asked for Software Vertex Processing, "
            "but this is unimplemented\n");
    /* if (pDesc->Usage & D3DUSAGE_TEXTAPI) { } */

    info->height0 = 1;
    info->depth0 = 1;
    info->array_size = 1;
    info->last_level = 0;
    info->nr_samples = 0;

    hr = NineResource9_ctor(&This->base, pParams, NULL, TRUE,
                            Type, Pool, Usage);

    if (FAILED(hr))
        return hr;

    if (Pool == D3DPOOL_MANAGED) {
        This->managed.data = align_malloc(
            nine_format_get_level_alloc_size(This->base.info.format,
                                             Size, 1, 0), 32);
        if (!This->managed.data)
            return E_OUTOFMEMORY;
        memset(This->managed.data, 0, Size);
        This->managed.dirty = TRUE;
        u_box_1d(0, Size, &This->managed.dirty_box);
        list_inithead(&This->managed.list);
        list_inithead(&This->managed.list2);
        list_add(&This->managed.list, &pParams->device->update_buffers);
        list_add(&This->managed.list2, &pParams->device->managed_buffers);
    }

    return D3D_OK;
}

**Comment by axeldavy** [comment]
I guess you cannot ask for the game being fixed ?

There are vertexbuffers created in default pool with no usage flag. That get mapped with readonly flag...

See:
`
nine:vertexbuffer9:ctor: This=0x66a94db8 Size=0x16a4 Usage=0 Pool=0
nine:buffer9:ctor: This=0x66a94db8 Size=0x16a4 Usage=0 Pool=0
nine:resource9:ctor: This=0x66a94db8 pParams=0x12ee668 initResource=(nil) Allocate=1 Type=6 Pool=0 Usage=0
nine:resource9:ctor: (0x66a94db8) Creating pipe_resource.
nine:buffer9:Lock: This=0x66a94db8(pipe=0x66a94cf0) OffsetToLock=0x0, SizeToLock=0x16a4, Flags=0x10
nine:buffer9:Lock: returning pointer 0x6ac52000
nine:buffer9:Unlock: This=0x66a94db8
nine:device9:CreateIndexBuffer: This=0x7d0fb6d8 Length=2118 Usage=0 Format=D3DFMT_INDEX16 Pool=0 ppOut=0x150e534 pSharedHandle=(nil)
nine:indexbuffer9:ctor: This=0x66a95028 pParams=0x12ee668 pDesc=0x12ee6d8 Usage=
nine:buffer9:ctor: This=0x66a95028 Size=0x846 Usage=0 Pool=0
nine:resource9:ctor: This=0x66a95028 pParams=0x12ee668 initResource=(nil) Allocate=1 Type=7 Pool=0 Usage=0
nine:resource9:ctor: (0x66a95028) Creating pipe_resource.
nine:buffer9:Lock: This=0x66a95028(pipe=0x66a94f90) OffsetToLock=0x0, SizeToLock=0x0, Flags=0x0
nine:buffer9:Lock: returning pointer 0x6bcde000
nine:buffer9:Unlock: This=0x66a95028
nine:buffer9:Lock: This=0x66a94db8(pipe=0x66a94cf0) OffsetToLock=0x0, SizeToLock=0x16a4, Flags=0x10
nine:buffer9:Lock: returning pointer 0x7ba6b000
nine:buffer9:Unlock: This=0x66a94db8
`

It gets locked twice... with readonly. And then is used a lot of times as source for rendering.

**Comment by axeldavy** [comment]
According to the driver documentation:
https://msdn.microsoft.com/en-us/library/windows/hardware/ff551637(v=vs.85).aspx

readonly is never passed to the driver since windows 2000, which means readonly can have impact only for things having a ram copy backing (like managed, and perhaps dynamic).

I guess the solution is just to ignore the READONLY flag (except for managed textures)

**Comment by Oblit03** [comment]
Results:

```
if (Pool == D3DPOOL_MANAGED) {
        This->managed.data = align_malloc(
            nine_format_get_level_alloc_size(This->base.info.format,
                                             Size, 1, 0), 256);
```
Crashes during loading (Seems to crash sooner than `Size, 1, 0), 32);`)

```
if (Pool == D3DPOOL_MANAGED) {
        This->managed.data = align_malloc(
            nine_format_get_level_alloc_size(This->base.info.format,
                                             Size+1000, 1, 0), 32);
```
Loads into the game, but shows graphical errors: 
Textures missing or incorrect.
Incorrect vertex data which changes by switching to a different ship.  

Images:
![shot-16 03 11_17 50 27-0627](https://cloud.githubusercontent.com/assets/17604550/13710789/1b57501a-e7b3-11e5-8ce0-8890cd234027.jpg)
![shot-16 03 11_16 09 34-0562](https://cloud.githubusercontent.com/assets/17604550/13711124/d23bddd6-e7b4-11e5-85c6-56171d28f624.jpg)

Other tests:
```
if (Pool == D3DPOOL_MANAGED) {
        This->managed.data = align_malloc(
            nine_format_get_level_alloc_size(This->base.info.format,
                                             Size, 1, 0), 512);
```
Same as 256
```
if (Pool == D3DPOOL_MANAGED) {
        This->managed.data = align_malloc(
            nine_format_get_level_alloc_size(This->base.info.format,
                                             Size+2000, 1, 0), 32);
```
Same as +1000

To add to previous results:
```
if (Pool == D3DPOOL_MANAGED) {
        This->managed.data = align_malloc(
            nine_format_get_level_alloc_size(This->base.info.format,
                                             Size, 1, 0), 32);
```
Crashes most of the time, but does sometimes get into the game (about 1 in 12 attempts).

**Comment by axeldavy** [comment]
This is very wierd, no idea what's the problem for MANAGED Pool.

Anyway, the problem described in this issue should be fixed in current ixit/master, could you check ?

**Comment by Oblit03** [comment]
The geometry issues are now fixed with your recent commits and there are no signs of the vertex/texture problems shown above. 

(If it would be better to create separate issue reports I will edit this report to remove anything not related to the now fixed geometry issue and close it.)


The other bugs still remain, but I don't think I can provide much data to help find the problems causing them. Apitrace remains non-functional with this game and provides even less on Windows 7 (D3DERR_INVALIDCALL followed by Unknown Object, no graphics).

I doubt this image will be of much use:
![shot-16 03 12_19 30 17-0224](https://cloud.githubusercontent.com/assets/17604550/13724816/ec893218-e888-11e5-878b-fb8f39ded1c7.jpg)

Those projectiles move with the camera and rotate around on the right side of the screen. I've never seen them appear on the left side and they actually cut off in the middle of the screen. This is shown in [pontostroy's video](http://www.gearsongallium.com/?p=2580) as well (2:07).

Cursor remains missing. Unless there is anything I can test/upload it's probably not worth chasing unless it would help with testing nine.

R600 bug remains (wined3d only. If this is irrelevant I will remove it).
I don't think I can provide much here either other than the information posted earlier and this [wine backtrace](https://github.com/iXit/Mesa-3D/files/170605/backtrace.txt). Running any of the apitrace traces posted earlier crashes on my HD6950 while using wined3d (do they crash on other systems?). This occurs with or without CSMT.

**Comment by axeldavy** [comment]
This is quite weird

**Comment by Oblit03** [comment]
**The R600 error does not occur if `LIBGL_ALWAYS_SOFTWARE=1` is used, but I do get an  "out of memory" error if not run with CSMT (Tested on 1.9.3-staging):**
```
Mesa: User error: GL_OUT_OF_MEMORY in glTexImage2D
err:d3d:wined3d_debug_callback 0x68be398: "GL_OUT_OF_MEMORY in glTexImage2D".
err:d3d_texture:texture2d_prepare_texture >>>>>>>>>>>>>>>>> GL_OUT_OF_MEMORY (0x505) from glTexImage2D @ texture.c / 951
err:d3d:wined3d_debug_callback 0x68bdfb8: "GL_OUT_OF_MEMORY in glCompressedTexSubImage2D".
err:d3d_surface:wined3d_surface_upload_data >>>>>>>>>>>>>>>>> GL_OUT_OF_MEMORY (0x505) from glCompressedTexSubImage2D @ surface.c / 1389
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
wine: Assertion failed at address 0xf773dba0 (thread 003c), starting debugger...

**Comment by Oblit03** [comment]
The memory error above does not occur in-game and it seems to work fine with `LIBGL_ALWAYS_SOFTWARE=1`, other than being extremely slow.

**Comment by Oblit03** [comment]
The R600 bug seems to have been fixed in upstream mesa. 
[This commit has fixed it](https://cgit.freedesktop.org/mesa/mesa/commit/?id=e502801d9843984233426f1b31e42bf6095d63be)

**Comment by axeldavy** [comment]
Good !
