### ISSUE TITLE
Stalker - black menu

### ISSUE THREAD

**Issue by iiv3** [iXit/Mesa-3D#196]
I've uploaded `stalker.soc.black.menu.XR_3DA.d3d9.trace` in the ftp.
It plays fine under wined3d, but is pitch black when using latest git Nine. 

I think the image is not completely black, some shadow of motion could be sensed when moving the mouse of the menu.Clicking on menu entry could get you to a visible menu. The main menu would be black when you return to it. Loading a game works, the game is also pitch black.

The problem appears only when using the "static" d3d9 game render.

 When using any of the other 2 "dynamic shadow" d3d9 renders, the menu and game are visible, with some exceptions. The screen also goes black when player is shot in-game.

It's a little bit hard to check if this bug is regression, because of issue #80. What I know is that it is not "recent" regression.

**Comment by axeldavy** [comment]
Fixed on ixit/master
