### ISSUE TITLE
World of Warships cursor not rendering

### ISSUE THREAD

**Issue by Oblit03** [iXit/Mesa-3D#197]
The cursor shows briefly during loading (flashes in for about half a second) and then disappears. It does not render in-game in fullscreen or windowed mode.

This bug is not present with wined3d.

Changing the following code causes the cursor to render correctly:

**device9.c lines 733-734**

```
if (!This->cursor.software)
    This->cursor.software = FALSE; //ID3DPresent_SetCursor(This->swapchains[0]->present, NULL, NULL, bShow) != D3D_OK;
```

Or this:

```
if (This->cursor.software)
    This->cursor.software = ID3DPresent_SetCursor(This->swapchains[0]->present, NULL, NULL, bShow) != D3D_OK;
```

Or this:

```
/*
if (!This->cursor.software)
    This->cursor.software = ID3DPresent_SetCursor(This->swapchains[0]->present, NULL, NULL, bShow) != D3D_OK;
*/
```

Forcing software cursor also works:
**device9.c line 278**
`This->cursor.software = TRUE;`

Files:
[Log](https://mega.nz/#!GosnTBAS!_NjQMKUpNBu533xfKhgjLp7iOQJexhGlYPxYXRiRAzc)
[Trace](https://mega.nz/#!3t1GgDzY!_2KVYh2v5MSfM3VI_KTUwr6Xn3u3qUtKQsydli-ui2Q)

Reverting commit [`a306847`](https://github.com/iXit/Mesa-3D/commit/a30684712ee9a3ef6738de8c357134a01a24924c) does not fix this bug.

**Comment by axeldavy** [comment]
This is quite weird

**Comment by Oblit03** [comment]
As of game update 0.5.5.0 all of the above workarounds are useless. The cursor does not render on nine, but still renders correctly under wined3d.

*Will attach log here shortly*

**Comment by Oblit03** [comment]
The following code fixes the cursor bug in WoWS without breaking SC:
**wine/dlls/d3d9-nine/present.c:549**
```
   if (This->hCursor) {
      if (bShow)
          SetCursor(This->hCursor);
      else
          SetCursor(NULL);
   }
 //  SetCursor(bShow ? This->hCursor : NULL);
```

**Comment by axeldavy** [comment]
Perhaps the code

      if (cursor)
         DestroyCursor(This->hCursor);
      This->hCursor = cursor;

should be

      if (cursor) {
         DestroyCursor(This->hCursor);
         This->hCursor = cursor;
      }

**Comment by axeldavy** [comment]
It looks like our code is buggy,
and if you call NineDevice9_ShowCursor to show the cursor,
whereas you were already showing the cursor (and didn't change it),
the we call SetCursor with a This->hCursor that wasn't filled.

**Comment by axeldavy** [comment]
Is the game supposed to keep system cursor ?

**Comment by axeldavy** [comment]
I think the correct fix is
/* if bShow, but no cursor given yet, keep displaying system cursor */
   if (!bShow || this->hCursor)
       SetCursor(bShow ? This->hCursor : NULL);

The other solution is in Mesa change
This->cursor.visible = bShow && (This->cursor.hotspot.x != -1);
    if (!This->cursor.software)
        This->cursor.software = ID3DPresent_SetCursor(This->swapchains[0]->present, NULL, NULL, bShow) != D3D_OK;

by

This->cursor.visible = bShow && (This->cursor.hotspot.x != -1);
    if (!This->cursor.software && This->cursor.visible != old)
        This->cursor.software = ID3DPresent_SetCursor(This->swapchains[0]->present, NULL, NULL, bShow) != D3D_OK;

Both should work, but are not strictly equivalent. We have to choose.

**Comment by Oblit03** [comment]
**Results:**
```

This->cursor.visible = bShow && (This->cursor.hotspot.x != -1);
if (!This->cursor.software && This->cursor.visible != old)
    This->cursor.software = ID3DPresent_SetCursor(This->swapchains[0]->present, NULL, NULL, bShow) != D3D_OK;
```
Cursor is shown in WoWS but not in Supreme Commander (SC works fine without these changes).

```
  if (cursor) {
     DestroyCursor(This->hCursor);
     This->hCursor = cursor;
  }
```
No changes.

```
/* if bShow, but no cursor given yet, keep displaying system cursor */
if (!bShow || This->hCursor)
SetCursor(bShow ? This->hCursor : NULL);
```
Cursor is shown in both WoWS and Supreme Commander.

**Comment by axeldavy** [comment]
siro, do you agree with the wine patch ?

I think we cannot put it in the for_upstream_staging branch, we need more testing for that patch.

**Comment by siro20** [comment]
Yes it need more tests. Should be simple to merge when ready.

**Comment by Altosk** [comment]
I've been playing this game the above patch works with no changes in  WoW 7.1.5 and 1.12.1 .

**Comment by axeldavy** [comment]
I think the problem with
```
This->cursor.visible = bShow && (This->cursor.hotspot.x != -1);
if (!This->cursor.software && This->cursor.visible != old)
    This->cursor.software = ID3DPresent_SetCursor(This->swapchains[0]->present, NULL, NULL, bShow) != D3D_OK;
```

Is that the application can do calls to the cursor api outside d3d.

We have applications like World of Warships which probably call SetCursor one time at init outside d3d, and thus we must not overwrite their SetCursor call when no cursor has been given to d3d.

However what may be happening with Supreme Commander is that it uses a d3d cursor, then uses manually SetCursor, to hide the cursor, then switches to d3d cursor again. With the above code, for us the cursor is still visible and thus we don't call SetCursor again.

Thus we have to be especially careful about these outside of d3d calls.

I think the following patch is the best way to handle the approach:

 ```
This->cursor.visible = bShow && (This->cursor.hotspot.x != -1);
if (!This->cursor.software && This->cursor.hotspot.x != -1)
    This->cursor.software = ID3DPresent_SetCursor(This->swapchains[0]->present, NULL, NULL, bShow) != D3D_OK;
```

That is until we have any cursor given ((This->cursor.hotspot.x set to -1), everything is noop. However when there has been a cursor given, pass everything to SetCursor.

I'll push an equivalent patch. Please reopen if any of the two mentionned games has any issue.
