### ISSUE TITLE
[Deus Ex: Human Revolution Directors Cut] graphical artifacts

### ISSUE THREAD

**Issue by DarkDefender** [iXit/Mesa-3D#198]
I had a problem with this game previously #154, this seems to be somewhat solved for me now. Now with latest mesa and wine git it only has this slow loading stuff once and then it seems to be cached so loading levels and streaming is quite fast now after the first initial load.

However, I do get some horrible graphical artifacts that were not there before. It kinda looks like this: http://i.imgur.com/vLSwa.jpg
So it seem like the vertex positions are wrong sometimes. (I can provide screenshots from ingame if needed)

@siro20 do you see the same artifacts? They doesn't seem to trigger all of the time but it seems like I allways run into them if I run around the first large city area a bit.

I don't think it's my 290x being broken either as I don't seem to get these problems in any native opengl programs. I haven't been able to try this without running the d3d9 wine backend sadly as I can't get ingame and run around without it.

**Comment by siro20** [comment]
I've haven't seen any in "Deus Ex: Human Revolution Directors Cut", but the game runs very slow on my old card. I tested only a few minutes.
I've seen similar glitches in Crysis: Warhead. They appear every few minutes and are likely related to multithreaded vertex/index buffer locking.

**Comment by DarkDefender** [comment]
Ah, ok. They only seem to trigger for me if I enter a new area so that it streams in new content. I guess that the initial load is too slow to be able to mess up the vertex buffer.

And if it is a multithread problem, then that might explain why it seems so random. I mean, one time I played for about 20 minutes and everything seemed fine and then I went into a new area ingame and I got really bad artifacting.

**Comment by siro20** [comment]
possible the same issue as https://github.com/iXit/Mesa-3D/issues/234.

**Comment by DarkDefender** [comment]
@siro20 yeah, probably. Has the new code changes been merged into upstream mesa? If so, I could easily check if this issue is fixed for me now.

**Comment by DarkDefender** [comment]
I've tried out the latest changes to mesa master and I do not have this problem anymore it seems.  Thanks for fixing it!
