### ISSUE TITLE
Archeage in dx9 mode crashes on start up

### ISSUE THREAD

**Issue by Altosk** [iXit/Mesa-3D#201]
recently the game removed hackshield which allows the game to start. wined3d gets stuck at a blackscreen while nine crashes on start up.
 heres a the part i found interesting:
nine:unknown:QueryInterface: This=0xf6a98bb0 riid=0x33bbac ppvObject=0x33bba8
nine:swapchain9:GetBackBuffer: GetBackBuffer: This=0xf6a98bb0 iBackBuffer=0 Type=0 ppBackBuffer=0xf655d630
nine:device9:SetDefaultState: This=0xf655d438 is_reset=0
nine:nine_update_state: changed state groups: fffffff
nine:nine_ff_update: vs=(nil) ps=(nil)
nine:vertexshader9:ctor: This=0xf6aa8200 pParams=0x33ba28 pFunction=(nil) cso=0xf28a5310
nine:pixelshader9:ctor: This=0xf6a5f8e0 pParams=0x33bc28 pFunction=(nil) cso=0xf284e170
nine:update_framebuffer: 
nine:update_vertex_buffers: mask=ffff
nine:nine_update_state: finished
nine:adapter9:CreateDevice: NineDevice9 created successfully.
nine:device9:dtor: This=0xf655d438
nine:vertexshader9:dtor: This=0xf6aa8200
nine:pixelshader9:dtor: This=0xf6a5f8e0
nine:swapchain9:dtor: This=0xf6a98bb0
nine:surface9:dtor: This=0xf28297c0
nine:resource9:dtor: This=0xf28297c0
/var/tmp/portage/media-libs/mesa-9999/work/mesa-9999/src/gallium/state_trackers/nine/iunknown.h:146:NineUnknown_Detach: Assertion `This->container && !This->forward' failed.
wine: Unhandled exception 0x80000003 in thread 90 at address 0xf5a4a09b (thread 0090), starting debugger...

**Comment by siro20** [comment]
try reverting this commit: https://github.com/iXit/Mesa-3D/commit/22cd54da9311c88d1486fbfd62a9486b9c4bd98f

**Comment by Altosk** [comment]
reverting that commit gets the game to the same point as wined3d

**Comment by Altosk** [comment]
heres a log https://www.sendspace.com/file/xb8kmy

**Comment by siro20** [comment]
The game doesn't start, neither with nine nor wine. how did you get it running ?

**Comment by Altosk** [comment]
i get a black screen after the poem with a themed mouse pointer with both nine and wined3d. theres a bug report on the wined3d part but i think the game set the dx mode to dx11 and not dx9.winehq bug report log shows dxgi being used.

**Comment by Altosk** [comment]
this bug has been resolve but i found another bug which ill open a new issue closing
