### ISSUE TITLE
Crysis 1 regression

### ISSUE THREAD

**Issue by iiv3** [iXit/Mesa-3D#203]
The game stops with:
```iunknown.h:146:NineUnknown_Detach: Assertion `This->container && !This->forward' failed.```

before even initializing a window.

I did a bisect and landed on:
```
22cd54da9311c88d1486fbfd62a9486b9c4bd98f is the first bad commit
commit 22cd54da9311c88d1486fbfd62a9486b9c4bd98f
Author: Axel Davy <axel.davy@ens.fr>
Date:   Sat Mar 12 20:37:16 2016 +0100
    st/nine: Fix Swapchain dtor
    Swapchain dtor didn't release the backbuffers properly.

```

**Comment by axeldavy** [comment]
Yes, known regression unfortunately.

There probably need a big cleanup to the ref/bind code.

**Comment by iiv3** [comment]
Yes, I reported it at 16 March on IRC.
I thought I should report it, because it haven't been fixed for over a month and without written issue it could be easily forgotten/neglected.

**Comment by iiv3** [comment]
That's been solved long ago.
