### ISSUE TITLE
Dark Souls 1 & 2 regression: extremely long startup time

### ISSUE THREAD

**Issue by exbb2** [iXit/Mesa-3D#206]
Dark Souls 2 in particular prints a wall of similar error messages while loading

    LLVM triggered Diagnostic Handler: SIInstrInfo::storeRegToStackSlot - Do not know how to spill register
    LLVM triggered Diagnostic Handler: SIInstrInfo::loadRegFromStackSlot - Do not know how to restore register
    LLVM triggered Diagnostic Handler: SIInstrInfo::storeRegToStackSlot - Do not know how to spill register
    LLVM triggered Diagnostic Handler: SIInstrInfo::loadRegFromStackSlot - Do not know how to restore register
    LLVM triggered Diagnostic Handler: SIInstrInfo::storeRegToStackSlot - Do not know how to spill register
    LLVM triggered Diagnostic Handler: SIInstrInfo::loadRegFromStackSlot - Do not know how to restore register
    LLVM triggered Diagnostic Handler: SIInstrInfo::storeRegToStackSlot - Do not know how to spill register
    LLVM triggered Diagnostic Handler: SIInstrInfo::loadRegFromStackSlot - Do not know how to restore register
    LLVM failed to compile shader
    radeonsi: can't create a shader

This happens in the current build and a march build https://github.com/iXit/Mesa-3D/commit/ff085d but doesn't happen in an old november 2015 build https://github.com/iXit/Mesa-3D/commit/d8c269

**Comment by pontostroy** [comment]
does R600_DEBUG=mono helps?

**Comment by axeldavy** [comment]
or R600_DEBUG=sisched

**Comment by exbb2** [comment]
There is another regression between current version and march 11 https://github.com/iXit/Mesa-3D/commit/9908b1. I didn't test this before, but currently Dark Souls 2 renders a black window instead of game content. http://i.imgur.com/idJ4ekq.png

@pontostroy @axeldavy 

Yes. Both options eliminate error spew in Dark Souls 2. With mono Dark Souls 1 loads instantly, with sisched it loads for 30 seconds instead of 50. However mono adds a lot of stuttering.

**Comment by axeldavy** [comment]
You didn't have the issue because the old build had mono by default.

now shaders in the driver are compiled straight away, thus the loading time, and then patched (sort of) to adapt to the needs (which was the initial reason it had to be compiled during play time, and add stuttering).

This is not a nine bug. If this is faster loading on windows, that's because in addition to doing that, on windows they also put the compilation in a separate thread, which radeonsi doesn't do yet.
