### ISSUE TITLE
Steam overlay wrapper doesn´t work on many titles

### ISSUE THREAD

**Issue by mandruis** [iXit/Mesa-3D#207]

**Comment by axeldavy** [comment]
Which one for example ?

**Comment by mandruis** [comment]
Counter Strike Source or Counter Strike Global Offensive

**Comment by mandruis** [comment]
I find out that doesn't work in other games like Rocket League

**Comment by axeldavy** [comment]
I have Rocket League, and the steam overlay works.

**Comment by mandruis** [comment]
Do you use Steam beta or Steam realease?

**Comment by siro20** [comment]
Tested with Counter Strike Global Offensive and the steam overlay is working fine.
Which WINE and Mesa version are you using ?

**Comment by mandruis** [comment]
I use Wine version of the Sarnex PPA and the mesa git version with LLVM git of paulo dias PPA

**Comment by mandruis** [comment]
Ok fixed but can you commit the last midifications in mesa git ?
