### ISSUE TITLE
Musl libc compatibility

### ISSUE THREAD

**Issue by xhebox** [iXit/Mesa-3D#213]
Thx for reading my issue and sorry for my poor english..
There're two problems need to be solved.
Fisrt, there's no **pthread** defined in Musl libc.They are provided by libpthread-stubs.
```diff
--- mesa-11.1.1/src/gallium/state_trackers/nine/threadpool.h
+++ mesa-11.1.1/src/gallium/state_trackers/nine/threadpool.h
@@ -23,7 +23,7 @@

 #ifndef _THREADPOOL_H_
 #define _THREADPOOL_H_
-
+#include <pthread.h>
 #define MAXTHREADS 1

 struct threadpool {
```

Second,there's no **fpu_control.h**.And i just simply copied it from glibc into the dir "src/gallium/state_trackers/nine/".Then the compiling passed.
```diff
--- mesa-11.1.1/src/gallium/state_trackers/nine/device9.c
+++ mesa-11.1.1/src/gallium/state_trackers/nine/device9.c
@@ -56,7 +56,7 @@

 #if defined(PIPE_CC_GCC) && (defined(PIPE_ARCH_X86) || defined(PIPE_ARCH_X86_64))

-#include <fpu_control.h>
+#include "fpu_control.h"

 static void nine_setup_fpu()
 {
```
And i don't know excatly if there's a macro called "MUSL" or something else that can be used for testing which libc is used.May be add a option to the configure scripts?
THX~

**Comment by okias** [comment]
First, thanks for bringing up musl topic.

1) about musl macro - http://wiki.musl-libc.org/wiki/FAQ#Q:_why_is_there_no_MUSL_macro_.3F .
So there is need to test, if feature is available and then behave by some pattern, not depending on specific libc(glibc, uclibc, musl, bionic, or whatever..)

2) about fpu_control, I think you can inspire here -> http://lists.busybox.net/pipermail/buildroot/2016-February/152266.html

3) feel free to make fork iXit/Mesa-3D on github and push patch which fix these issues. At this moment, I don't have musl enviroment which include things needed for xorg+mesa, so would be great, if you're able to test these patches and send them to us! :)

**Comment by xhebox** [comment]
Good!THX for replying.
But i'm busy studying for my exam,and i'm just a newbie.This may take long time for me to finish it.Anyway i'll do it as well as possible...

**Comment by axeldavy** [comment]
perhaps MUSL has an alternative to fpu_control.h ?

If you find out what other include we can but there that would work for both glibc and musl, I'll make a patch.

**Comment by axeldavy** [comment]
apparently the portable library is fenv.h

Unfortunately the feature we need is needing feenableexcept, fedisableexcept and fesetprec, which are not available in musl.

**Comment by axeldavy** [comment]
actually we could do with feenableexcept, fedisableexcept but not without fesetprec. The only other way would be to use assembly, which is annoying.

**Comment by okias** [comment]
@axeldavy that seems to be best approach, new libc wont include this functionality and I guess in this case we can't escape few lines of assembly code..

@xhebox if you could do it, convert (kinda copy paste with small edits) code which we use from fpu_control directly into our code, to be able get rid of fpu_control ? :) That may be task for less than hour  ;-)

**Comment by axeldavy** [comment]
But there are some added complexities to check if the assembly fpu commands can be used on the platform

**Comment by siro20** [comment]
should we use pipe_mutex_lock instead of pthread_mutex_lock ? Maybe mesa's wrapper code does compile on musl libc.

**Comment by xhebox** [comment]
@okias @axeldavy 
https://github.com/xhebox/Mesa-3D/commit/88bedf9a422c5a6dc007bf1c3898396bfff147e2
The assembly fpu commands can be safely used on x86 and x86_64, so it should work.But not yet tested.
Need to compile it with musl and glibc, and test if we can run a d3d9 game.
I do have a musl enviroment, but no xorg...Actually i'm doing a LFS system.So i can't test if we can run a d3d9 game with musl.
But I think it is no mather if we can run a d3d9 game with glibc, anyway it's a assembly command, no depencies.

**Comment by xhebox** [comment]
https://github.com/iXit/Mesa-3D/pull/214
made a pull request :)

**Comment by xhebox** [comment]
@siro20 I don't know it.It doesn't use pthread instead of something else?

**Comment by axeldavy** [comment]
Fix pushed.
