### ISSUE TITLE
Steam overlay does not work in wine

### ISSUE THREAD

**Issue by x5f3759df** [iXit/Mesa-3D#215]
Steam overlay does not work in wine. Tested games - Cod MW2 and Rocket League (I am pretty sure, it does not work in other titles)

Disabling Gallium 3D in winecfg fix the problem. So it is definitely problem with d3d-patch.

$ glxinfo | grep Mesa
client glx vendor string: Mesa Project and SGI
OpenGL core profile version string: 4.1 (Core Profile) Mesa 11.2.2
OpenGL version string: 3.0 Mesa 11.2.2
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 11.2.2

I was trying with vanilla wine (v1.9.9 and 1.8.2), patched manually - same result
Also I was trying with latest git mesa, but same result again.

**Comment by axeldavy** [comment]
We fixed that a few months ago. It needs last wine and last Mesa.

If you don't have last Mesa when compiling wine, you may get some features disabled.

**Comment by x5f3759df** [comment]
Okay, I will try that.

**Comment by x5f3759df** [comment]
Well, I build new mesa from ixit overlay and then rebuild wine - overlay works. Thanks for the tip.
