### ISSUE TITLE
World of Goo freezes when in fullscreen mode

### ISSUE THREAD

**Issue by iiv3** [iXit/Mesa-3D#221]
The game starts in fullscreen mode and it seems like it hangs before it shows anything.
You can alt+enter and switch to windows mode, then the game runs fine.

If you switch back to fullscreen, the image moves for less than a second then freezes. Music still seems to play but that's it. Trying to switch back to window actually blocks in a strange way (video mode switching takes forever and music stops and starts in a cycle).

No issues with wined3d, or the native build (afair).

I'm not uploading logs and traces, since the game have a free demo on steam. And it is quite small.

**Comment by Altosk** [comment]
Iiv3 sound like My age of Conan issue

**Comment by iiv3** [comment]
It seems like it is indeed a duplicate of issue #173 .
The game freezes at the moment mouse is moved.

I'll close this one and write comment there.
