### ISSUE TITLE
[artefacts][nine] Multiple Games: rendering artifacts

### ISSUE THREAD

**Issue by siro20** [iXit/Mesa-3D#234]
The artefacts appear randomly on nouveau, r600 and softpipe.
Mark it as nine issue.

**Comment by axeldavy** [comment]
buggy vertices on radeonsi as well. Looks like a 0/inf issue

**Comment by siro20** [comment]
Tomb Raider shows the same issues

**Comment by axeldavy** [comment]
I looked at Crysis, and it is not a shader issue (no division, and previous draw calls with same shaders fine)

I also tried clear the vertex and index buffer contents, and made them bigger than asked to checked for draw outside bounds, but nope.

**Comment by axeldavy** [comment]
Using DEFAULT pool instead of managed pool helps...

**Comment by axeldavy** [comment]
Rahh, I found the bug. We really need to review all the initial nine code, that's the second time I fix a bug in it in two days !

**Comment by axeldavy** [comment]
Fixed
