### ISSUE TITLE
[softpipe] D3DFMT_A8 pitch is different

### ISSUE THREAD

**Issue by siro20** [iXit/Mesa-3D#235]
Pitch of D3DFMT_A8 on softpipe differs to nouveaus pitch.
Found using apitrace.

**Comment by axeldavy** [comment]
How bad is it ?
One software the pitch should be of 1 byte.
But perhaps on hardware it's not possible, and it ends up 4 byte.

**Comment by axeldavy** [comment]
One windows it could be the same, it's not really a bug then.

**Comment by imirkin** [comment]
A8_UNORM should be fully supported on nouveau (nv50 and nvc0) (with 1-byte-per-pixel).

**Comment by siro20** [comment]
IDirect3DDevice9::CreateTexture(this = 0x7d4f2688, Width = 720, Height = 488, Levels = 1, Usage = D3DUSAGE_DYNAMIC, Format = D3DFMT_A8, Pool = D3DPOOL_DEFAULT, ppTexture = [0x7d5edda8], pSharedHandle = NULL)

Pitch:
nvc0 720, llvmpipe 768

IDirect3DDevice9::CreateTexture(this = 0x7d4f2688, Width = 360, Height = 244, Levels = 1, Usage = D3DUSAGE_DYNAMIC, Format = D3DFMT_A8, Pool = D3DPOOL_DEFAULT, ppTexture = [0x7deabc30], pSharedHandle = NULL) 

Pitch:
nvc0 360, llvmpipe 384

**Comment by siro20** [comment]
llvmpipe aligns the pitch to  util_cpu_caps.cacheline, which is 64 in my case.

**Comment by axeldavy** [comment]
Hum... ok.

Should it be considered a bug ?

**Comment by imirkin** [comment]
All (non-staging) textures are stored in VRAM, which means that when you map them for reading, we actually give you a copy. That copy is tightly packed. Is there some reason we should be aligning the pitch to something? In general, different drivers will hand out different pitch based on ... various things.

**Comment by siro20** [comment]
Not a bug.
