### ISSUE TITLE
WoW crashes on start

### ISSUE THREAD

**Issue by Altosk** [iXit/Mesa-3D#242]
heres my log using mesa master / ixit git
https://drive.google.com/file/d/0BzDOzwvBhElceURkVWk4NWxHOEU/view?usp=sharing

**Comment by sarnex** [comment]
Does it work with wine d3d?

**Comment by Altosk** [comment]
yes wine d3d works fine

**Comment by Altosk** [comment]
also it worked on nine just a few days ago

**Comment by axeldavy** [comment]
This is mesa regression that affects all state trackers (except GL), and there is no concensus on the fix yet. It is being discussed.

**Comment by Altosk** [comment]
retested mesa git and ixit git still not fixed with your memset patch

**Comment by axeldavy** [comment]
Do you have any more info ? With mesa git is it still wrong ? We just pushed the patches to git.

**Comment by Altosk** [comment]
Last night it was still crashing on starting the game something about unable to access memory

**Comment by Altosk** [comment]
I run mesa master with ixit appied on top. Ill retest when i can

**Comment by Altosk** [comment]
wow error 132
something about memory could not be written
0xf0a38b6f referenced memory at 0x00000028

**Comment by Altosk** [comment]
hm looks like WoW 7.0.3 is looking for dx10 and dxgi. i guess they dropped dx9?

**Comment by axeldavy** [comment]
was it working before with mesa git without ixit patches ? Could you try find the bad commit ?

**Comment by Altosk** [comment]
i'll do a bisect when i can

**Comment by Eriner** [comment]
@axeldavy @Altosk Bisected to ba0274c7d6c3b77a36bbe1b444f427b0c873e2f3 at upstream mesa.

**Comment by axeldavy** [comment]
The error seems to be in NineSurface9_ctor with the part

if (pDesc->Usage & D3DUSAGE_DYNAMIC)
pResource->flags |= NINE_RESOURCE_FLAG_LOCKABLE;

It is wrong.

**Comment by Altosk** [comment]
shouldn't this line --allocate && (pDesc->Pool == D3DPOOL_DEFAULT)-- be more like (allocate && pDesc->Pool == D3DPOOL_DEFAULT)?

**Comment by axeldavy** [comment]
that's the same

**Comment by axeldavy** [comment]
it should work fine if you remove

if (pDesc->Usage & D3DUSAGE_DYNAMIC)
pResource->flags |= NINE_RESOURCE_FLAG_LOCKABLE;

(we ignore the flag for now)

I'll figure out what's the proper fix.

**Comment by axeldavy** [comment]
thanks for reporting the issue and doing the bisect

**Comment by axeldavy** [comment]
Should be fixed now

**Comment by Altosk** [comment]
this is fixed

**Comment by Eriner** [comment]
Thanks for the fix @axeldavy, and thanks @Altosk for filing the bug report! :+1:
