### ISSUE TITLE
GetRasterStatus() method implementation needed for Flash based games on Steam, like "Machinarium"

### ISSUE THREAD

**Issue by iiv3** [iXit/Mesa-3D#244]
The game starts, creates a window, then screen freezes. It seems that it goes fullscreen and never clears it. It's possible to switch away from the game and kill it.

While the game is not responsive, it prints an infinite number of:

```
nine:swapchain9:GetRasterStatus: GetRasterStatus: This=0x7ce04280 pRasterStatus=0x32d83c
fixme:d3d9nine:DRI3Present_GetRasterStatus (0x1436f0, 0x32d83c), stub!
```

I tried to return `D3D_OK` in the stub function, but this made the game crash.
It seems that the Flash player tries to measure framerate, by calculating the speed of scanline changes and somehow it divides by zero if scanline doesn't change.

I added a counter and emulation for vblank and this let the game start and work.

I looked into wined3d implementation of that function. They seem to have a more sophisticated version of my hack, involving real timer, resolution and framerate calculations.
`wine_source/dlls/wined3d/directx.c::wined3d_get_adapter_raster_status()`

**Comment by axeldavy** [comment]
it looks like modern cards do advertise D3DCAPS_READ_SCANLINE (which guarantees support for the feature).

What wine does it the most sensible, though I don't think we need timer, just read time, divide by frequency, and decide that 2/3 of the time are going to increase raster line, and else it would be in vblank.

**Comment by iiv3** [comment]
You read time from a timer.
I just wonder, if it is possible to obtain the real info fro the hardware.
I know the hardware supports it since CGA, we just need a way to query it.

It might also be useful for other stuff, related to composite managers, etc.

**Comment by siro20** [comment]
We can fake the implementation using a timer.
I don't see any benefit to use real hardware values.
It requires drm support, we'd need to do syscalls ...

**Comment by axeldavy** [comment]
I don't get why we need a timer. Why not use gettimeofday usec field ?

**Comment by siro20** [comment]
Fixed in ixit/wine
