### ISSUE TITLE
School Mate visual bugs

### ISSUE THREAD

**Issue by zemfil** [iXit/Mesa-3D#253]
School Mate has got some visual bugs in the Main Menu (see Image).
The background in the main menu looks very blurred compared to what wine produces.
Also, once a game is started, the screen blends to white and stays white, but the game continues.
Wine doesn't have those issues.

On the terminal it says:
nine:nine_state_copy_common: Fixed function state not handled properly by StateBlocks.

nine:
![sm_nine](https://cloud.githubusercontent.com/assets/23645689/20507495/40c392a2-b05b-11e6-93ef-c4fb3608ba55.png)

wine:
![sm_wine](https://cloud.githubusercontent.com/assets/23645689/20507508/59dc8794-b05b-11e6-911a-e9f13aa35642.png)

Attached is a full debug log.
[nine.log.zip](https://github.com/iXit/Mesa-3D/files/605221/nine.log.zip)
[SchoolMate.trace.zip](https://github.com/iXit/Mesa-3D/files/605276/SchoolMate.trace.zip)

**Comment by axeldavy** [comment]
It is surprising it works at all on wine given the app is using swvp which we implemented recently in nine, but that wine hasn't.

**Comment by zemfil** [comment]
Wine manages to display the menu correctly and the game can be started, but the swvp doesn't really work as the body of the characters is warped/missing parts and the animations are f*ed up.

**Comment by axeldavy** [comment]
I fixed a part of the bugs. The background is still too dark.

**Comment by axeldavy** [comment]
I didn't mean to close it, sorry

**Comment by zemfil** [comment]
I made two more traces. In one scene the whole screen is way too bright, in the other a wall is painted in purple.
[sm_traces.zip](https://github.com/iXit/Mesa-3D/files/607979/sm_traces.zip)

**Comment by zemfil** [comment]
Actually disregard the bright one. Windows shows the same behavior.

**Comment by axeldavy** [comment]
Here is our fixed function shaders for the wall issue

`VERT
PROPERTY NEXT_SHADER FRAG
DCL IN[0]
DCL IN[1]
DCL IN[2]
DCL OUT[0], POSITION
DCL OUT[1], COLOR
DCL OUT[2], COLOR[1]
DCL OUT[3], TEXCOORD[0]
DCL OUT[4], TEXCOORD[1]
DCL CONST[19..23]
DCL CONST[24]
DCL CONST[0..7]
DCL CONST[16..18]
DCL TEMP[0..10]
DCL ADDR[0]
IMM[0] FLT32 {    0.0000,     1.0000,    32.0000,     3.0000}
IMM[1] FLT32 {    2.0000,     8.0000,     0.0000,     0.0000}
  0: MUL TEMP[0], IN[0].xxxx, CONST[0]
  1: MAD TEMP[0], IN[0].yyyy, CONST[1], TEMP[0]
  2: MAD TEMP[0], IN[0].zzzz, CONST[2], TEMP[0]
  3: MAD OUT[0], IN[0].wwww, CONST[3], TEMP[0]
  4: MUL TEMP[0].xyz, IN[0].xxxx, CONST[4]
  5: MAD TEMP[0].xyz, IN[0].yyyy, CONST[5], TEMP[0]
  6: MAD TEMP[0].xyz, IN[0].zzzz, CONST[6], TEMP[0]
  7: MAD TEMP[0].xyz, IN[0].wwww, CONST[7], TEMP[0]
  8: MUL TEMP[1].xyz, IN[1].xxxx, CONST[16]
  9: MAD TEMP[1].xyz, IN[1].yyyy, CONST[17], TEMP[1]
 10: MAD TEMP[1].xyz, IN[1].zzzz, CONST[18], TEMP[1]
 11: DP3 TEMP[2].x, TEMP[1], TEMP[1]
 12: RSQ TEMP[2].x, TEMP[2].xxxx
 13: MUL TEMP[1].xyz, TEMP[1], TEMP[2].xxxx
 14: MOV TEMP[3], IN[2]
 15: MOV OUT[3], TEMP[3]
 16: DP3 TEMP[6].x, TEMP[0], TEMP[0]
 17: RSQ TEMP[6].x, TEMP[6].xxxx
 18: MUL TEMP[5], TEMP[0], TEMP[6].xxxx
 19: DP3 TEMP[2].x, TEMP[5], TEMP[1]
 20: MUL TEMP[2].xyz, TEMP[1], TEMP[2].xxxx
 21: ADD TEMP[2].xyz, TEMP[2], TEMP[2]
 22: SUB TEMP[3].xyz, TEMP[5], TEMP[2]
 23: MOV TEMP[3].w, IMM[0].yyyy
 24: MOV OUT[4], TEMP[3]
 25: MOV TEMP[6].w, IMM[0].zzzz
 26: MOV TEMP[7].xyz, IMM[0].xxxx
 27: MOV TEMP[8].xyz, IMM[0].xxxx
 28: MOV TEMP[9], IMM[0].xxxx
 29: BGNLOOP :80
 30:   ARL ADDR[0].x, TEMP[6].wwww
 31:   SNE TEMP[2].x, CONST[ADDR[0].x].xxxx, IMM[0].wwww
 32:   MOV TEMP[4].xyz, -CONST[ADDR[0].x+5]
 33:   MOV TEMP[3].w, IMM[0].yyyy
 34:   IF TEMP[2].xxxx :44
 35:     SUB TEMP[4].xyz, CONST[ADDR[0].x+4], TEMP[0]
 36:     DP3 TEMP[2].x, TEMP[4], TEMP[4]
 37:     RSQ TEMP[2].y, TEMP[2].xxxx
 38:     MUL TEMP[2].x, TEMP[2].xxxx, TEMP[2].yyyy
 39:     MAD TEMP[3].w, TEMP[2].xxxx, CONST[ADDR[0].x].wwww, CONST[ADDR[0].x].zzzz
 40:     MAD TEMP[3].w, TEMP[2].xxxx, TEMP[3].wwww, CONST[ADDR[0].x].yyyy
 41:     RCP TEMP[3].w, TEMP[3].wwww
 42:     SLT TEMP[2].x, TEMP[2].xxxx, CONST[ADDR[0].x+4].wwww
 43:     MUL TEMP[3].w, TEMP[3].wwww, TEMP[2].xxxx
 44:   ENDIF
 45:   DP3 TEMP[10].x, TEMP[4], TEMP[4]
 46:   RSQ TEMP[10].x, TEMP[10].xxxx
 47:   MUL TEMP[4].xyz, TEMP[4], TEMP[10].xxxx
 48:   SEQ TEMP[2].x, CONST[ADDR[0].x].xxxx, IMM[1].xxxx
 49:   IF TEMP[2].xxxx :58
 50:     DP3 TEMP[2].y, -TEMP[4], CONST[ADDR[0].x+5]
 51:     SUB TEMP[2].x, TEMP[2].yyyy, CONST[ADDR[0].x+6].yyyy
 52:     MUL TEMP[2].x, TEMP[2].xxxx, CONST[ADDR[0].x+6].zzzz
 53:     POW TEMP[2].x, TEMP[2].xxxx, CONST[ADDR[0].x+5].wwww
 54:     SGE TEMP[2].z, TEMP[2].yyyy, CONST[ADDR[0].x+6].xxxx
 55:     SGE TEMP[2].y, TEMP[2].yyyy, CONST[ADDR[0].x+6].yyyy
 56:     MAD_SAT TEMP[2].x, TEMP[2].xxxx, TEMP[2].yyyy, TEMP[2].zzzz
 57:     MUL TEMP[3].w, TEMP[3].wwww, TEMP[2].xxxx
 58:   ENDIF
 59:   DP3 TEMP[10].x, TEMP[0], TEMP[0]
 60:   RSQ TEMP[10].x, TEMP[10].xxxx
 61:   MUL TEMP[5].xyz, TEMP[0], TEMP[10].xxxx
 62:   SUB TEMP[5].xyz, TEMP[4], TEMP[5]
 63:   DP3 TEMP[10].x, TEMP[5], TEMP[5]
 64:   RSQ TEMP[10].x, TEMP[10].xxxx
 65:   MUL TEMP[5].xyz, TEMP[5], TEMP[10].xxxx
 66:   DP3_SAT TEMP[2].y, TEMP[1], TEMP[5]
 67:   IF TEMP[2].yyyy :71
 68:     POW TEMP[2].y, TEMP[2].yyyy, CONST[23].xxxx
 69:     MUL TEMP[2].y, TEMP[3].wwww, TEMP[2].yyyy
 70:     MAD_SAT TEMP[9], CONST[ADDR[0].x+2], TEMP[2].yyyy, TEMP[9]
 71:   ENDIF
 72:   DP3_SAT TEMP[2].x, TEMP[1], TEMP[4]
 73:   MUL TEMP[2].x, TEMP[3].wwww, TEMP[2].xxxx
 74:   MAD_SAT TEMP[7].xyz, CONST[ADDR[0].x+1], TEMP[2].xxxx, TEMP[7]
 75:   MAD_SAT TEMP[8].xyz, CONST[ADDR[0].x+3], TEMP[3].wwww, TEMP[8]
 76:   IF CONST[ADDR[0].x+7].wwww :79
 77:     BRK
 78:   ENDIF
 79:   ADD TEMP[6].w, TEMP[6].wwww, IMM[1].yyyy
 80: ENDLOOP :0
 81: MOV TEMP[7].w, IMM[0].yyyy
 82: MOV TEMP[8].w, IMM[0].yyyy
 83: MAD TEMP[2], TEMP[8], CONST[21], CONST[19]
 84: MAD_SAT OUT[1], TEMP[7], CONST[20], TEMP[2]
 85: MUL_SAT OUT[2], TEMP[9], CONST[22]
 86: END
nine:0x74f59b40:vertexshader9:ctor: This=0x2394aa50 pParams=0x74f58e68 pFunction=(nil) cso=0x239c82f8
nine:0x74f59b40:nine_ff_build_ps STAGE[0]: colorop=MODULATE alphaop=DISABLE
FRAG
DCL IN[0], COLOR, COLOR
DCL IN[1], TEXCOORD[0], PERSPECTIVE
DCL IN[2], COLOR[1], COLOR
DCL OUT[0], COLOR
DCL SAMP[0]
DCL TEMP[0..4]
IMM[0] FLT32 {    0.0000,     0.0000,     0.0000,     0.0000}
  0: MOV TEMP[0], IMM[0].xxxx
  1: MOV TEMP[1], IMM[0].xxxx
  2: MOV TEMP[2], IMM[0].xxxx
  3: TEX TEMP[2], IN[1], SAMP[0], 2D
  4: MOV TEMP[0], IN[0]
  5: MUL TEMP[0].xyz, TEMP[2], TEMP[0]
  6: ADD TEMP[0].xyz, TEMP[0], IN[2]
  7: MOV OUT[0], TEMP[0]
  8: END`

It looks like compared to before/after the call, only the blue channel of the wall is updated (though at some locations the other values do change, but only very slightly.

How is supposed to be the wall ? Luminous or dark ? Unless it is supposed to be very lighty, I suspect it's the blue channel which is wrong. Perhaps some temporary register overwrite.

**Comment by zemfil** [comment]
It's darker than the other walls,  but similar color. 
I will try to get a Screenshot later.

**Comment by zemfil** [comment]
I uploaded comparison shots [here](http://screenshotcomparison.com/comparison/191749)

**Comment by zemfil** [comment]
I made another trace with the graphics settings set to low and determined the sequence of calls which turn the background texture purple

Calls right before turning background wall purple:
```
SetIndices(this = 0x7cf3e128, pIndexData = NULL) = D3D_OK
SetStreamSource(this = 0x7cf3e128, StreamNumber = 0, pStreamData = NULL, OffsetInBytes = 0, Stride = 0) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_ALPHABLENDENABLE, Value = FALSE) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_ZWRITEENABLE, Value = TRUE) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_SRCBLEND, Value = D3DBLEND_ONE) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_DESTBLEND, Value = D3DBLEND_ZERO) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_FOGENABLE, Value = FALSE) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_AMBIENT, Value = 3355443) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_FOGENABLE, Value = FALSE) = D3D_OK
SetTransform(this = 0x7cf3e128, State = D3DTS_WORLD, pMatrix = &{m = {{1, 0, 0, 0}, {0, 1, 0, 0}, {0, 0, 1, 0}, {0, 0, -80.88619, 1}}}) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_FILLMODE, Value = D3DFILL_SOLID) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_CULLMODE, Value = D3DCULL_CW) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_ALPHABLENDENABLE, Value = TRUE) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_SRCBLEND, Value = D3DBLEND_ZERO) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_DESTBLEND, Value = D3DBLEND_INVSRCCOLOR) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_ZWRITEENABLE, Value = FALSE) = D3D_OK
SetSamplerState(this = 0x7cf3e128, Sampler = 0, Type = D3DSAMP_MIPFILTER, Value = D3DTEXF_NONE) = D3D_OK
SetSamplerState(this = 0x7cf3e128, Sampler = 1, Type = D3DSAMP_MIPFILTER, Value = D3DTEXF_NONE) = D3D_OK
SetSamplerState(this = 0x7cf3e128, Sampler = 0, Type = D3DSAMP_MAGFILTER, Value = D3DTEXF_POINT) = D3D_OK
SetSamplerState(this = 0x7cf3e128, Sampler = 0, Type = D3DSAMP_MINFILTER, Value = D3DTEXF_POINT) = D3D_OK
SetSamplerState(this = 0x7cf3e128, Sampler = 1, Type = D3DSAMP_MAGFILTER, Value = D3DTEXF_POINT) = D3D_OK
SetSamplerState(this = 0x7cf3e128, Sampler = 1, Type = D3DSAMP_MINFILTER, Value = D3DTEXF_POINT) = D3D_OK
SetTexture(this = 0x7cf3e128, Stage = 0, pTexture = 0x7c23fc08) = D3D_OK
SetTexture(this = 0x7cf3e128, Stage = 1, pTexture = NULL) = D3D_OK
SetMaterial(this = 0x7cf3e128, pMaterial = &{Diffuse = {r = 0.8, g = 0.8, b = 0.8, a = 1}, Ambient = {r = 1, g = 1, b = 1, a = 1}, Specular = {r = 0, g = 0, b = 0, a = 1}, Emissive = {r = 0.2, g = 0.2, b = 0.2, a = 1}, Power = 0}) = D3D_OK
SetSoftwareVertexProcessing(this = 0x7cf3e128, bSoftware = TRUE) = D3DERR_INVALIDCALL
SetFVF(this = 0x7cf3e128, FVF = D3DFVF_XYZ | D3DFVF_NORMAL | 0x100) = D3D_OK
SetStreamSource(this = 0x7cf3e128, StreamNumber = 0, pStreamData = 0x7c284970, OffsetInBytes = 0, Stride = 32) = D3D_OK
SetIndices(this = 0x7cf3e128, pIndexData = 0x7c2847a8) = D3D_OK
DrawIndexedPrimitive(this = 0x7cf3e128, PrimitiveType = D3DPT_TRIANGLELIST, BaseVertexIndex = 0, MinVertexIndex = 0, NumVertices = 4, startIndex = 0, primCount = 2) = D3D_OK
```
This sequence is repeated a couple of times and seems to darken the backround every time a little more.
Right after this sequence follows the following sequence which turns the background wall purple:
```
SetIndices(this = 0x7cf3e128, pIndexData = NULL) = D3D_OK
SetStreamSource(this = 0x7cf3e128, StreamNumber = 0, pStreamData = NULL, OffsetInBytes = 0, Stride = 0) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_ALPHABLENDENABLE, Value = FALSE) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_ZWRITEENABLE, Value = TRUE) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_SRCBLEND, Value = D3DBLEND_ONE) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_DESTBLEND, Value = D3DBLEND_ZERO) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_FOGENABLE, Value = FALSE) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_AMBIENT, Value = 3355443) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_FOGENABLE, Value = FALSE) = D3D_OK
SetTransform(this = 0x7cf3e128, State = D3DTS_WORLD, pMatrix = &{m = {{1, 0, 0, 0}, {0, 1, 0, 0}, {0, 0, 1, 0}, {0, 0, -86.28141, 1}}}) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_FILLMODE, Value = D3DFILL_SOLID) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_CULLMODE, Value = D3DCULL_CW) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_ALPHABLENDENABLE, Value = TRUE) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_SRCBLEND, Value = D3DBLEND_SRCALPHA) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_DESTBLEND, Value = D3DBLEND_INVSRCALPHA) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_ZWRITEENABLE, Value = FALSE) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_ALPHABLENDENABLE, Value = TRUE) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_SRCBLEND, Value = D3DBLEND_SRCALPHA) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_DESTBLEND, Value = D3DBLEND_ONE) = D3D_OK
SetRenderState(this = 0x7cf3e128, State = D3DRS_ZWRITEENABLE, Value = FALSE) = D3D_OK
SetSamplerState(this = 0x7cf3e128, Sampler = 0, Type = D3DSAMP_MIPFILTER, Value = D3DTEXF_NONE) = D3D_OK
SetSamplerState(this = 0x7cf3e128, Sampler = 1, Type = D3DSAMP_MIPFILTER, Value = D3DTEXF_NONE) = D3D_OK
SetSamplerState(this = 0x7cf3e128, Sampler = 0, Type = D3DSAMP_MAGFILTER, Value = D3DTEXF_POINT) = D3D_OK
SetSamplerState(this = 0x7cf3e128, Sampler = 0, Type = D3DSAMP_MINFILTER, Value = D3DTEXF_POINT) = D3D_OK
SetSamplerState(this = 0x7cf3e128, Sampler = 1, Type = D3DSAMP_MAGFILTER, Value = D3DTEXF_POINT) = D3D_OK
SetSamplerState(this = 0x7cf3e128, Sampler = 1, Type = D3DSAMP_MINFILTER, Value = D3DTEXF_POINT) = D3D_OK
SetTexture(this = 0x7cf3e128, Stage = 0, pTexture = 0x7c23fc08) = D3D_OK
SetTexture(this = 0x7cf3e128, Stage = 1, pTexture = NULL) = D3D_OK
SetMaterial(this = 0x7cf3e128, pMaterial = &{Diffuse = {r = 1, g = 1, b = 1, a = 0.2}, Ambient = {r = 1, g = 1, b = 1, a = 0.2}, Specular = {r = 0, g = 0, b = 1, a = 0.2}, Emissive = {r = 1, g = 1, b = 0.4, a = 0.2}, Power = 0}) = D3D_OK
SetSoftwareVertexProcessing(this = 0x7cf3e128, bSoftware = TRUE) = D3DERR_INVALIDCALL
SetFVF(this = 0x7cf3e128, FVF = D3DFVF_XYZ | D3DFVF_NORMAL | 0x100) = D3D_OK
SetStreamSource(this = 0x7cf3e128, StreamNumber = 0, pStreamData = 0x7c284cf8, OffsetInBytes = 0, Stride = 32) = D3D_OK
SetIndices(this = 0x7cf3e128, pIndexData = 0x7c284b30) = D3D_OK
DrawIndexedPrimitive(this = 0x7cf3e128, PrimitiveType = D3DPT_TRIANGLELIST, BaseVertexIndex = 0, MinVertexIndex = 0, NumVertices = 4, startIndex = 0, primCount = 2) = D3D_OK
```
Sadly this is the extent of my debugging skills and hope this will be useful

**Comment by axeldavy** [comment]
I fixed recently a lot of issues in our computation of lightning, but I see the code has some differences with what wine does.

Is wine having exactly the right behaviours everywhere ?

**Comment by axeldavy** [comment]
Well when wine replays the trace, it has blue wall as well.

The different between nine and wine is that nine accepts the software vertex processing shaders, and wine doesn't, which make it fallback to a full hardware path.

Perhaps we do accept things that shouldn't be accepted. The best would be to have a trace taken on windows.

**Comment by zemfil** [comment]
Trace made in Windows:
[sm_purple_win.trace.zip](https://github.com/iXit/Mesa-3D/files/613951/sm_purple_win.trace.zip)

**Comment by axeldavy** [comment]
The game seems to be relying on a corner case behaviour (which looks like a Windows implementation bug to me).
As wine has the same issue, I reported it:
https://bugs.winehq.org/show_bug.cgi?id=41827

**Comment by zemfil** [comment]
Almost all the rendering bugs have been fixed, as far as I could see, thank you!
There is only one thing missing, and that seems like fog in the nine version on the main menu.
Windows shows a fog like effect on the background plane where the trees and mountains are, but that effect is missing on nine.

When I disable fog effects in the game options. It shows the same picture as nine, so I assume there is something wrong with fog calculations(they are skipped/not applied?).

Here are comparison shots(latest mesa):
[http://screenshotcomparison.com/comparison/192014](url)

**Comment by axeldavy** [comment]
link is not working

**Comment by zemfil** [comment]
Fixed

**Comment by axeldavy** [comment]
This last fog issue is going to take longer to resolve.

**Comment by axeldavy** [comment]
Should be fixed on master. Can you confirm ?

**Comment by zemfil** [comment]
I can confirm it works, thanks!
Closing.
