### ISSUE TITLE
Media Player Classic shows an error message D3DERR_INVALIDCALL when d3d9 is enabled

### ISSUE THREAD

**Issue by KOLANICH** [iXit/Mesa-3D#256]
To reproduce:
1 Enable d3d9 in Wine settings
2 Download [Media Player Classic Home Cinema](https://nightly.mpc-hc.org/MPC-HC.1.7.10.269.x64.7z)
3 Unpack, run mpc-hc64.exe in Wine.
4 Open any video. You will see an error message.

This error message doesn't harm playback (it seems it works as good as with d3d9 disabled), though it is surely an indicator of some problem.

**Comment by axeldavy** [comment]
d3d9 has some parts of the API reserved for video players only.

I didn't know video players actually used that API :-) So far I thought that not.
I'll take a look.
Does it work with gallium nine disabled ?

**Comment by KOLANICH** [comment]
It works with both gallium nine enabled and disabled (I found no difference except the error message).

**Comment by siro20** [comment]
It calls d3dadapter9_GetAdapterDisplayModeEx, which is a STUB.

**Comment by siro20** [comment]
Should be fixed as of ixit wine's pull request 26.
