### ISSUE TITLE
Nine csmt buggy on amdgpu kernel driver

### ISSUE THREAD

**Issue by Altosk** [iXit/Mesa-3D#258]
topic
disabling csmt works fine

**Comment by axeldavy** [comment]
on which game, config ?

**Comment by Altosk** [comment]
Wow amd r9 390 works fine on Radeon kernel driver

**Comment by axeldavy** [comment]
That is definitely weird to have bugs on one kernel and not the other...
I have tonga, so amdgpu, and hadn't had particular issues.
Could you try get more info (debug info, etc) ?

**Comment by Altosk** [comment]
it might be that fact that its a CIK and not VI which is still experimental

**Comment by axeldavy** [comment]
It should be handled the same in mesa, it shouldn't be an issue.

**Comment by Altosk** [comment]
hm my debug log is getting cut off with csmt enabled?
my last line is : Binary file (standard input) matches

**Comment by Altosk** [comment]
ran a NINE_DEBUG for 3 hours got nothing but 10 mins of no debug WoW hangs going to check 4.10-rc1 for a possible fix

**Comment by axeldavy** [comment]
This looks like a sort of race. Do you have a crash backlog ?

**Comment by Altosk** [comment]
it doesnt crash it hangs with no info

**Comment by axeldavy** [comment]
I think I can reproduce.

Please confirm we hit the same issue.
When the game is hanged, use htop to find its pid, and use
sudo operf --pid=....

then wait a few seconds running the game

then opreport -l | grep d3d

Show what is reported.
For me it's only os_wait_until_zero

**Comment by Altosk** [comment]
with latest ixit git and mesa git  csmt i'm getting amdgpu_bo_cpu_map: Assertion `bo->cpu_map_count > 0' failed.

**Comment by Altosk** [comment]
still happens but not nearly as much or often

**Comment by axeldavy** [comment]
for me fixed by https://cgit.freedesktop.org/~mareko/mesa/commit/?h=master&id=960e85cf4155f3f75256e60baced503bfceb244b

**Comment by Altosk** [comment]
that commit works for me as well

**Comment by Altosk** [comment]
hm i'm hitting not enough memory error after several hours

**Comment by Altosk** [comment]
the error the WoW pops is error 134  OsMemBankPointer : failed to map view of file - not enough memory

**Comment by axeldavy** [comment]
did it not happen before ?

**Comment by Altosk** [comment]
I haven't tested radeon since the first issue was fixed but its new to me

**Comment by axeldavy** [comment]
I think the issues are fixed now, reopen if it is not the case.
