### ISSUE TITLE
Crysis 2 hangs before menu

### ISSUE THREAD

**Issue by mtmkls** [iXit/Mesa-3D#262]
The game starts with "press enter to begin", and when you do that it shows a login dialog for mycrysis.com, canceling that takes you to the main menu. With wined3d everything is fine. With nine, the game hangs when you press enter. This is printed to the console:
err:ntdll:RtlpWaitForCriticalSection section 0x7aad2b8 "?" wait timed out in thread 010e, blocked by 0121, retrying (60 sec)

**Comment by axeldavy** [comment]
Is this with ixit/master or with mesa master ?

**Comment by mtmkls** [comment]
mesa master, wine from ixit repo (the patch set doesn't apply to vanilla wine)

**Comment by x09723593** [comment]
Running with 'csmt_force=0' seems to fix the issue.

**Comment by axeldavy** [comment]
I found a few fixes to csmt, it may work better on ixit master.

**Comment by mtmkls** [comment]
I updated to latest mesa and ixit wine, but it still hangs. With csmt_force=0 it doesn't hang, and the game is playable (with wined3d the outdoor areas are slideshow).

**Comment by mtmkls** [comment]
With latest mesa it works without specifying csmt_force=0.
