### ISSUE TITLE
[CSMT] Hitman Blood Money freezes/crashes on loading savegame

### ISSUE THREAD

**Issue by zemfil** [iXit/Mesa-3D#263]
Once loading a savegame the game either crashes with a segmentation fault or it freezes on the loading screen. Without CSMT it works.
Wine doesn't crash.

[HitmanBM_nine.zip](https://github.com/iXit/Mesa-3D/files/682307/HitmanBM_nine.zip)

**Comment by axeldavy** [comment]
Does the log correspond to a freeze, segfault or just a normal run ?
The end of the log doesn't seem to show any particular problem.

When there is a segfault, is there some backtrace ?

**Comment by zemfil** [comment]
The log is from a segfault, I can't get a backtrace for the segfault case, but for the freezing case I get:

Backtrace:
=>0 0xf7737c97 __kernel_vsyscall+0x7() in [vdso].so (0x0154afb8)
1 0xf7531f62 __lll_lock_wait+0x21() in libpthread.so.0 (0x0154afb8)
2 0xf752b9ae __GI___pthread_mutex_lock+0x8d() in libpthread.so.0 (0x0154afb8)
3 0x7d4b6ed8 mtx_lock+0x53() in d3dadapter9.so (0x0154afb8)
4 0x7d4ba3ee LockDevice9_CreateVertexDeclaration+0x3d() in d3dadapter9.so (0x0154aff8)
5 0x7ea20ac3 WineNineDevice9_CreateVertexDeclaration+0x22() in d3d9-nine<elf> (0x0154b028)
6 0x0048fcd6 in hitmanbloodmoney (+0x8fcd5) (0x11d0e2a0)

I did a bisect and ac2927335bc7cd4994d2fc0906eb328773b1f923 seems to be the first bad commit. Does that seem plausible?

**Comment by axeldavy** [comment]
Thanks for the report.

I've spotted the issue and will try to fix it soon.

**Comment by axeldavy** [comment]
Should be fixed on ixit/master. Could you check ?

**Comment by zemfil** [comment]
Reloaded several times and didn't encounter the bug.
Closing.
