### ISSUE TITLE
Feature request: wire up Mesa common uploaders

### ISSUE THREAD

**Issue by Hi-Angel** [iXit/Mesa-3D#267]
Recently landed [a supposedly lowering memory usage patchset](https://lists.freedesktop.org/archives/mesa-dev/2017-February/thread.html#143622). It's adding two members into the pipe_context struct, and the docs recommend to state trackers to make use of them.

I tried wiring it up into nine myself, but for some reason games fails with my attempt. What I essentially did, was just [following this patch](https://lists.freedesktop.org/archives/mesa-dev/2017-February/143633.html), i.e. I removed all `u_upload_create()`, `u_upload_destroy()` bits, and replaced `*_uploader` variables in `u_upload_data()`, `u_upload_unmap()` to `const_uploader` and `stream_uploader`. It compiles, but doesn't work unfortunately :( To make it working I'd need more knowledge about nine internals, which I didn't have.

**Comment by Hi-Angel** [comment]
FTR, I hope it'd help *(e.g. because one don't need to search the code for the bits to change)*, here's a content of `git diff` from my attempt https://gist.github.com/Hi-Angel/4609e881409988c41d05944a5bc556f3

**Comment by axeldavy** [comment]
the patch is using pipe_sw for things that should use pipe (we use 3 pipe, you have to pick the correct one). It is missing also some cases in nine_state.c (I assume you want to use the common uploader for constants as well)

**Comment by Hi-Angel** [comment]
> the patch is using pipe_sw for things that should use pipe (we use 3 pipe, you have to pick the correct one).

Well, the struct `NineDevice9` have just 2 `pipe_context`s, it's `pipe_sw` and `pipe_secondary`. Do you mean, I'd need to add another one?

Btw, is my assumption correct, that, with regard to `pipe_context`s the only thing that matters, is what happens in between `u_upload_data()` and `u_upload_unmap()`? That's what I thought from reading the Marek's docs, but then a single `pipe_context` seems could be safely reused everytime, which not seem to be the case *(because my patch didn't work)*.

> It is missing also some cases in nine_state.c (I assume you want to use the common uploader for constants as well)

You probably mean `constbuf_uploader`, yeah, it was the only thing that upon creation [sets alignment](https://github.com/iXit/Mesa-3D/blob/547057d63bb5ce9a1a6a2c22a0acae1c3936fd84/src/gallium/state_trackers/nine/device9.c#L499), I didn't know what the changed code should look like, so I decided first to make sure the rest works. It didn't ☺

**Comment by Hi-Angel** [comment]
s/then a single `pipe_context` seems could be safely reused/then a single `u_upload_mgr` seems could be safely reused

**Comment by axeldavy** [comment]
Three pipes are used. pipe is used for rendering. pipe_secondary is used for uploads in a different context, and pipe_sw is for rendering with llvmpipe (there are some sw rendering operations in d3d9).

**Comment by Hi-Angel** [comment]
Oh, I see what you mean! Yay, it's working!! Now I've left to figure out what to do with `constbuf_uploader`, probably the same as with the rest, but to use `const_uploader`.

**Comment by Hi-Angel** [comment]
@axeldavy I'm going to send [the patch](https://gist.github.com/Hi-Angel/dc434491550d46abbc8b6833f01943c8) to Mesa-dev, but not sure about the description — should I include the line 

    co-authored by: Axel Davy

?

**Comment by Hi-Angel** [comment]
@axeldavy and while on it: I'm using uploaders of `pipe_sw` for variables with `_sw_` infix. IIRC at some moment I used for them a usual pipe, and it worked too. So I'm wondering, would it be better to use `pipe` for them too, e.g. perhaps it would render faster?

**Comment by axeldavy** [comment]
you must be careful with which uploader you use. It must use the corresponding uploader for a given pipe.

Don't put me as co author, you are the author.

**Comment by Hi-Angel** [comment]
Thank you, I sent the patch. Can't link to it though as it didn't appear yet in the mailing list archive.

**Comment by Hi-Angel** [comment]
Oh, here it is https://lists.freedesktop.org/archives/mesa-dev/2017-February/145034.html :3

**Comment by Hi-Angel** [comment]
Okay, FTR, this one is off because thunderbird broke formatting, I resent it here https://lists.freedesktop.org/archives/mesa-dev/2017-February/145047.html
