### ISSUE TITLE
winecfg d3d9 button unselectable, it's gray

### ISSUE THREAD

**Issue by andysendo** [iXit/Mesa-3D#268]
i tried to compile wine2.2 and wine staging 2.2 follow d3d9 patch file rules, this is my config.log about d3d9 part (some of grep -i nine config.log):

#define D3D9NINE_MODULEPATH "/usr/lib/i386-linux-gnu/d3d/d3dadapter9.so.1"
#define D3D9NINE_HEADERS_CFLAGS "-I/usr/include"
#define D3D9NINE_DRI2 1
        dlls/d3d9-nine \
        dlls/wininet \
        dlls/wininet/tests \
        dlls/wininet/tests \
D3D9NINE_LIBS =  -lxcb -lxcb-dri3 -lxcb-present -lxcb-xfixes -lX11-xcb -lX11 -lXext -lGL -lEGL
D3D9NINE_LIBS=' -lxcb -lxcb-dri3 -lxcb-present -lxcb-xfixes -lX11-xcb -lX11 -lXext -lGL -lEGL'
#define HAVE_D3D9NINE 1
#define D3D9NINE_MODULEPATH "/usr/lib/i386-linux-gnu/d3d/d3dadapter9.so.1"
#define D3D9NINE_HEADERS_CFLAGS "-I/usr/include"
#define D3D9NINE_DRI2 1

so compiled winecfg d3d9 button is gray, unselectable. i download https://launchpad.net/~commendsarnex/+archive/ubuntu/winedri3 2.1 version, winecfg d3d9 button selectable.

**Comment by axeldavy** [comment]
did you check you have d3dadapter9.so

**Comment by andysendo** [comment]
i self-compiled mesa-13.0.4-1~bpo8 with enale nine, source from debian8 backports.
d3d9 patched wine/staging config.log as above shuold tell d3dadapter9.so* could be found, does it?

i comment out the lines as bellow in patch and recompile winecfg can select d3d9 button.
#if !defined(HAVE_D3D9NINE)
    disable(IDC_ENABLE_NATIVE_D3D9);
#endif
now error is : Setting Software\Wine\Direct3DNine ModulePath is required.

**Comment by andysendo** [comment]
then i write registry key module path for d3dadapter9.so path, d3d9 can be actived.
maybe patch for compile script have some bug? configure.log show up any error, but micro HAVE_D3D9NINE / DEFAULT_Module_Path did not set correct.

i tested a few 3d games, still exits some renderring bugs i've met, otherhand cpu-load / fps indeed have some improved, and gpu will random crash. d3d9 patch still needs more work for stable.

good job.

**Comment by iiv3** [comment]
I hope you are going to report all rendering bugs.

**Comment by siro20** [comment]
Can you please provide the ./configure call and ./configure output ?

**Comment by siro20** [comment]
Closing bug report. Please reopen if the problem still exists and provide additional information.
