### ISSUE TITLE
GALLIUM_HUD_DUMP_DIR not generating data

### ISSUE THREAD

**Issue by zemfil** [iXit/Mesa-3D#270]
I wanted to capture the GALLIUM_HUD data with GALLIUM_HUD_DUMP_DIR, but the generated files are all empty. Nothing is written to them. The display of the HUD is working alright.

I'm on latest ixit mesa.

**Comment by vinibali** [comment]
Hello.
Same here with mesa 17.0.1-2 on rolling Arch.

**Comment by zemfil** [comment]
I tested mesa git and the bug is fixed there. Closing.
