### ISSUE TITLE
Black Screen on Max Payne 3

### ISSUE THREAD

**Issue by gamusin** [iXit/Mesa-3D#273]
nine log

http://pastebin.com/14gjTMLR

**Comment by gamusin** [comment]
I see that my card is wrongly detected I don't have a r9 290, I have a rx 460

**Comment by gamusin** [comment]
this also happens if nine is disabled maybe I should report at wine bugs.

**Comment by sarnex** [comment]
There just some huge struct that maps PCI ids to card names, it's just
outdated. It shouldn't matter.

**Comment by gamusin** [comment]
sorry this is already reported on wine bugs it's a long standing bug something with ddraw not redirecting properly. It works if you set to emulate a virtual desktop.
