### ISSUE TITLE
[nine] Dragon Age: Origins hangs after cutscenes with internal CSMT enabled

### ISSUE THREAD

**Issue by Itzamnaaj** [iXit/Mesa-3D#277]
Description: 
The game 'Dragon Age: Origins' will hang after cutscene videos with Nine's internal CSMT enabled. There are no relevant error messages or meaningful backtraces; WINE and Mesa were compiled with CFLAGS="-Og -ggdb -g -gdwarf-2 -gstrict-dwarf" and FEATURES="nostrip".

Expected behaviour:
'Dragon Age: Origins' does not hang after the cutscene ends.

Workarounds:
1: Exiting the cutscene before it ends by pressing escape will circumvent the hang.
2: Disabling Nine's internal CSMT by providing the 'csmt_force=0' environment variable allows the game to proceed normally after cutscenes end.

System information:
Distribution: Gentoo GNU/Linux
Kernel version: 4.9.6-gentoo-r1
Mesa version: 17.0.1
WINE version: 2.3
LLVM version: 4.0.0

**Comment by axeldavy** [comment]
This sounds like a thread safety issue.

While the game is hanged, you can go to a terminal (or switch VT), and use tools like operf to know where time is spent. That would give an indication if it is in nine or in the gallium driver.

**Comment by axeldavy** [comment]
I found a few issues with multithreading. Patches will be added shortly to mesa master (and are already in this git)

**Comment by Itzamnaaj** [comment]
Amazing, you fixed this bug in record time (I hope).

I will test it once it hits Mesa's master branch.

Do you still need OProfile samples, Axeldavy?

**Comment by siro20** [comment]
Can it be close as it is fixed upstream ?

**Comment by axeldavy** [comment]
I assume the bug is fixed, thus closing.
