### ISSUE TITLE
World of Warcraft Crashing with wine2.0 + Gallium 9 

### ISSUE THREAD

**Issue by NerdHarder615** [iXit/Mesa-3D#280]
Since the update last week I have been having constant crashes with World of Warcraft if I have gallium9 enabled on my wine client. Not sure which logs you need me to get for you, so please let me know and I will provide any logs, configs, etc... that is needed to troubleshoot these issues.

**Comment by axeldavy** [comment]
it seems mesa git has regression

**Comment by delovoy** [comment]
A similar problem

**Comment by NerdHarder615** [comment]
The issues were fixed upstream. The update from 5/26/2017 fixed my issues.
