### ISSUE TITLE
Artefacts after 91771ccf9669cc1

### ISSUE THREAD

**Issue by psychiatrists** [iXit/Mesa-3D#282]
Arch Linux
Mesa-git Repo 

R600 (HD6970) + RadeonSI (HD7750)

wine-staging-nine (2.7/2.8)
Game:
Requime Rise of the Reaver
playrequiem.com

after commit "91771ccf9669cc1" i see:
odd artefacts
flickering
unstable lighting / darker textures
half loaded textures (text) that load properly after "2nd draw" by revisiting the "object"

For some screenshots see:
https://imgur.com/a/STFT7

**Comment by Eignar17** [comment]
is new patch in wine-staging 2.8 no add in the nine :/

**Comment by axeldavy** [comment]
potentially fixed a few hours ago.

**Comment by psychiatrists** [comment]
Mesa-git Repo build: 
fixed in short head "9229348faedbc7e"

Thanks, great work.
