### ISSUE TITLE
Resident Evil 5 white texture shading

### ISSUE THREAD

**Issue by zemfil** [iXit/Mesa-3D#283]
There is a pretty interesting issue in the shading of some textures on the weapon and characters. The textures are glowing white in dark places. When alt tabbing out of the game and again into the game the textures are rendered correctly, but they slowly turn white and stay that way. In open spaces the issue is still there but less pronounced/visible.

Both nine and wine suffer from this issue, but wines result is less bright.

Here are some screenshots for reference:

nine at the beginning of the scene:
![re5_1](https://user-images.githubusercontent.com/23645689/26956699-06744ef0-4cc0-11e7-8ac2-1e3e80d2d605.jpg)

nine after a couple of seconds:
![re5_2](https://user-images.githubusercontent.com/23645689/26956701-0bb01b88-4cc0-11e7-9f7a-88ca39a4c2d0.jpg)

wine after a couple of seconds:
![re5_3](https://user-images.githubusercontent.com/23645689/26956703-0f04d26a-4cc0-11e7-926e-24eb1f8245eb.jpg)

I also captured a [trace](https://mega.nz/#!OF43yTjA!jHYfcbWt79rYgk9Vq8ndLk_dD10WWABX5-xPEvz-CQc) of the same scene.

**Comment by axeldavy** [comment]
the trace shows the same pattern on windows.

It could be something in another dll ? Do you use windows ones ?

**Comment by zemfil** [comment]
I'm not sure, but I didn't add any dlls into wine.

**Comment by axeldavy** [comment]
try install d3d9 native dlls with winetricks

**Comment by zemfil** [comment]
I installed d3d9x, but the same happens

**Comment by zemfil** [comment]
Tested the game on windows and it turns out this is a bug in the game itself, so nine was rendering correctly after all...
