### ISSUE TITLE
Freesync support

### ISSUE THREAD

**Issue by DestroyFX** [iXit/Mesa-3D#286]
Hi, I just configured freesync on my side with latest mesa git and kernel 4.12 with DC patch.

On OpenGL (wine) with freesync enabled : It work perfectly
On Nine (wine) with freesync enabled : It's like without any kind of vsync, 150fps+
On Nine (wine) with freesync disabled : The vsync go down to 30fps instead of 60fps (It does that since forever, it's not related to freesync/DC patchs)

**Comment by axeldavy** [comment]
I don't know how freesync is handled in the graphic stack, and I don't know how much we can make it work with the dx9 swapbuffer model.
You can make gallium nine behave more like opengl with:
tearfree_discard=true as env var (or drirc config)
If it doesn't behave well, thread_submit=true can help too.

If freesync is implemented such that the opengl swapbuffer way works as is without modifications, these could help.

**Comment by DestroyFX** [comment]
@axeldavy I tested with both and each envvar and thread_submit=true seam to fix the problem.

**Comment by DestroyFX** [comment]
@sarnex 
I used the last 4.12 with last DC in it I got there : https://cgit.freedesktop.org/~agd5f/linux/log/?h=amd-staging-4.12

The rest of my gfx stack (libdrm, mesa, llvm, ddx) is 100% blñeeding edge, so it might need some other bit in the userspace that require like this week mesa or something, I don't know.

And it seam to work fine, it stay at 60fps then if it can't render that fast, it go down for example to 55fps, not 30. So I assume it's is working find.

xrandr --prop
*blabla*
                supported: off, on, auto
        freesync_capable: 1 
                range: (0, 1)
        freesync: 1 
                range: (0, 1)
        underscan vborder: 0 
*blabla*

**Comment by sarnex** [comment]
Have you checked using your monitor on screen menu that the actual refresh
rate is changing?

**Comment by mirh** [comment]
Is there any improvement/difference now that DC is up and official?

**Comment by axeldavy** [comment]
My understanding is it should be working without changes

**Comment by axeldavy** [comment]
Moved here:
https://github.com/iXit/wine-nine-standalone/issues/14
