### ISSUE TITLE
 Black screen in wow (compatibility with winXP), after the update

### ISSUE THREAD

**Issue by delovoy** [iXit/Mesa-3D#287]
Hi guys, 

Encountered a problem after wow upgrade to version 7.3.0 stopped running wow, a black screen appears, while "Battle.net" works. But if you set winecfg compatibility different from winxp, even Battle.net does not start.

What information do you need to provide?

I ask help

wine --version 
wine-2.14

**Comment by axeldavy** [comment]
Does it still work with standard wine ?
Tell un about the console messages

**Comment by delovoy** [comment]
[Wine wow.txt](https://github.com/iXit/Mesa-3D/files/1272406/Wine.wow.txt)

**Comment by delovoy** [comment]
And black screen

**Comment by axeldavy** [comment]
Could you produce the same log with NINE_DEBUG=all ? (works only if mesa built with --enable-debug)

**Comment by delovoy** [comment]
What should the team look like?

**Comment by delovoy** [comment]
wine nine_debug=all .wine/drive_c/Program\ Files/World\ of\ Warcraft/Wow.exe 
wine: cannot find L"C:\\windows\\system32\\nine_debug=all.exe"

**Comment by sarnex** [comment]
You need to put it before "wine"

**Comment by delovoy** [comment]
=)

nine_debug=all wine .wine/drive_c/Program\ Files/World\ of\ Warcraft/Wow.exe

[debug.txt](https://github.com/iXit/Mesa-3D/files/1272590/debug.txt)

**Comment by sarnex** [comment]
Please do NINE_DEBUG=all, it is case sensitive

**Comment by delovoy** [comment]
[NINE_DEBUG.txt](https://github.com/iXit/Mesa-3D/files/1272803/NINE_DEBUG.txt)

I do not see any changes

**Comment by axeldavy** [comment]
if there is no change, it means mesa wasn't built with --enable-debug. Which distribution are you using ? sarnex may know which ppa do have it, if you use ubuntu.

**Comment by delovoy** [comment]
I use Ubuntu 16.04

**Comment by delovoy** [comment]
http://ppa.launchpad.net/commendsarnex/winedri3/ubuntu
http://ppa.launchpad.net/oibaf/graphics-drivers/ubuntu

**Comment by sarnex** [comment]
I looked into it, the oibaf ppa nor the padoka ppa is using --enable-debug.
I guess you'd have to compile mesa yourself

**Comment by axeldavy** [comment]
That's not easy to build mesa yourself for ubuntu (especially since wow will likely need 32 bits).
Wasn't there a third ppa ?

**Comment by sarnex** [comment]
I just looked again and haven't been able to find one. A year or two ago I
ran one with debug, but nobody used it so I deleted it.

**Comment by delovoy** [comment]
I need to compile it: https://github.com/iXit/Mesa-3D? Terribly. To compile under what architecture? I don't remember that I established from a repository whether I was for 32 bits or for 64 there. 

The 64th bit system is used

**Comment by delovoy** [comment]
Prompt please, it is necessary to compile with what parameters? --enable-debug and ...?

**Comment by sarnex** [comment]
If you are using a 32bit wineprefix, you will need 32bit mesa.

Here the the flags from the oibaf ppa with --enable-debug added:

--prefix=/usr --mandir=\${prefix}/share/man
--infodir=\${prefix}/share/info --sysconfdir=/etc
--libdir=\${prefix}/lib/i386-linux-gnu --localstatedir=/var
--build=i686-linux-gnu --enable-debug --enable-dri
--with-dri-drivers=" nouveau i915 i965 r200 radeon swrast"
--with-dri-driverdir=/usr/lib/i386-linux-gnu/dri
--with-dri-searchpath='/usr/lib/i386-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri'
--enable-osmesa --enable-glx-tls --enable-shared-glapi
--enable-texture-float --with-vulkan-drivers=intel,radeon
--enable-driglx-direct --enable-dri3 --with-egl-platforms="x11 wayland
drm" --enable-xa --enable-llvm ac_cv_path_LLVM_CONFIG=llvm-config-5.0
--enable-vdpau --enable-omx --enable-va --enable-xvmc --enable-opencl
--enable-opencl-icd --enable-nine --enable-gallium-extra-hud
--enable-lmsensors --with-gallium-drivers=" nouveau svga r600 r300
virgl radeonsi swrast" --enable-gles1 --enable-gles2

**Comment by sarnex** [comment]
Feel free to remove options that aren't for your GPU. "sudo apt-get
build-dep mesa" may be helpful also.

**Comment by delovoy** [comment]
Sarnex, tell me please, I'm stumped:

./autogen.sh --prefix=/usr .<..> --enable-gles2

configure: error: LLVM 3.9.0 or newer is required for radeonsi

But I have installed "LLVM"

root@IdeaPad:/home/delovoy/Mesa-3D# dpkg -l llvm
ii  llvm                           1:6.0-38~exp1~201707 amd64                Low-Level Virtual Machine (LLVM)

What kind of a specific package is needed?

[autogen.txt](https://github.com/iXit/Mesa-3D/files/1277861/autogen.txt)

**Comment by axeldavy** [comment]
this is very time consuming to build mesa on ubuntu (especially 32 bits).

What about wine with gallium nine disabled ? Is the problem similar ?

**Comment by delovoy** [comment]
Nothing wrong. Time is now. To understand it would be desirable with "llvm"

> What about wine with gallium nine disabled ? Is the problem similar ?

Did not try

**Comment by delovoy** [comment]
Checked, the window does not open at all

**Comment by delovoy** [comment]
I noticed one feature, the game was run only with compatibility winhp. I previously received a message from Blizzard that as soon as the time has come to end the support for winxp, but the game was not previously run with another compatibility, what could this be related to?

![don t_support](https://user-images.githubusercontent.com/1622211/30074237-4df7384c-9260-11e7-82ee-7174f791c8d1.png)

By the way, I wanted to ask the native speakers, do you understand me? Google translate copes with the obligation assigned to him?

**Comment by axeldavy** [comment]
On our irc channel, we are told there is a patched version of wine 
staging that supports the new Wow. You'd have to use that version + the 
patches to enable gallium nine. Sarnex, what is the best way to get that 
on ubuntu ?

**Comment by sarnex** [comment]
Right now there is no PPA that is nine+staging. I can make one, but if we plan to merge with staging somewhat soon it is not useful. If not, I can make my PPA use staging + d3d9 instead, since I assume that use case is more common

**Comment by delovoy** [comment]
By the way, WorlofTanks works on my computer. The only problem with warcraft 7.3.0

**Comment by Altosk** [comment]
warcraft 7.3.0 works fine with nine when set to windows 7 or higher. i believe that windows xp was dropped from supported systems also.

**Comment by delovoy** [comment]
Not relevant, I do not remember how I decided
