### ISSUE TITLE
Archeage crashes with invalid pointer

### ISSUE THREAD

**Issue by Altosk** [iXit/Mesa-3D#289]
*** Error in `C:\Program Files (x86)\Steam\steamapps\common\ArcheAge\Games\ArcheAge\Live\bin32\ArcheAge.exe': free(): invalid pointer: 0xa922d8c8 ***
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 4451 requests (4451 known processed) with 0 events remaining.
i dont have debug compile atm but can if need

**Comment by axeldavy** [comment]
We definitely need the debug info to be able to debug this.

mesa built with --enable-debug, and then game ran with NINE_DEBUG=all

**Comment by Altosk** [comment]
it never happened again might have been an radeonsi bug or an amdgpu-drm-next-4.15 bug(was testing DC with my rx480)

**Comment by axeldavy** [comment]
Ok
