### ISSUE TITLE
nine gets loaded when a dx11 game(divinity 2) is started

### ISSUE THREAD

**Issue by Altosk** [iXit/Mesa-3D#291]
should it? i ask because i feel like it shouldnt

**Comment by axeldavy** [comment]
there is no possibility dx9 gets loaded when dx11 is asked. The game must have some reasons to load dx9 as well as dx11

**Comment by siro20** [comment]
DX11 is emulated by wined3d, which only access OpenGL functions.
Not a bug.

**Comment by iiv3** [comment]
I would like to reopen this bug.

It is possible the game does use both interfaces and that Nine should detect this case and handle it properly.

[Surface Sharing Between Windows Graphics APIs](https://msdn.microsoft.com/en-us/library/windows/desktop/ee913554(v=vs.85).aspx)

**Comment by Altosk** [comment]
I agree that this should be handled

**Comment by iiv3** [comment]
BTW, which game is it exactly:
[Divinity II: Developer's Cut](https://www.gog.com/game/divinity_2_developers_cut) or 
[Divinity: Original Sin 2](https://www.gog.com/game/divinity_original_sin_2) ?

Because "Divinity II" is D3D9 game, "Original Sin 2" is D3D11.

**Comment by axeldavy** [comment]
It must be the latter because I've managed to make the former work without issues.

**Comment by Altosk** [comment]
Divinity original sin 2
