### ISSUE TITLE
Textures problems

### ISSUE THREAD

**Issue by Youness-e** [iXit/Mesa-3D#293]
Hi, 
I have textures problems for 3 months, with the release of version 7.3.0 of World of Warcraft:
https://image.noelshack.com/fichiers/2017/46/1/1510534069-capture-d-ecran-de-2017-11-13-01-06-57.png
https://image.noelshack.com/fichiers/2017/46/1/1510534070-capture-d-ecran-de-2017-11-13-01-06-45.png
https://image.noelshack.com/fichiers/2017/46/1/1510534074-capture-d-ecran-de-2017-11-13-01-06-26.png

Do you have any ideas about the origin of this problem ? I could fix the bug, but impossible for me to find the origin of this problem ><

Thanks
Archlinux, wine 2.19, mesa 17.2.5-1

**Comment by Altosk** [comment]
This is a wow 7.3.0 ish dx9 error as it happens on windows

**Comment by siro20** [comment]
@Altosk: is it a game bug ?

**Comment by Altosk** [comment]
Last I read it was

**Comment by axeldavy** [comment]
Ok, closing then.
