### ISSUE TITLE
d3d9-adapter programs freeze display first frame with xorg-server 1.19.6 (commit 5c00e69)

### ISSUE THREAD

**Issue by john-tho** [iXit/Mesa-3D#300]
Hi,

With gallium nine active:
I get one rendered frame, then no visual change.
Process does not crash.
winedbg attached and generated backtrace: [poe-nine1.log](https://github.com/iXit/Mesa-3D/files/1631457/poe-nine1.log) [poe-nine-winedbg.log](https://github.com/iXit/Mesa-3D/files/1631461/poe-nine-winedbg.log)
Programs work with gallium nine disabled in winecfg.
Tested Path of Exile
These were working in December.
linux, llvm and mesa were all updated around this time.

Radeon HD 5850
i7-2600

Arch Linux x64
[linux 4.14.13-1-ARCH](https://git.archlinux.org/svntogit/packages.git/tree/repos/core-x86_64?h=packages/linux&id=cde4fff622eb9b760e51893e3d9befe64d4e29d3)
[llvm-libs 5.0.1-1](https://git.archlinux.org/svntogit/packages.git/tree/repos/extra-x86_64?h=packages/llvm&id=440ca7d9a7c9b564d023fd845e33d1600aeafe8e)
[mesa 17.3.2-2](https://gitlab.com/archlinux-packages-johnth/packages-modified/blob/f70c0338d1d7062e91eff31091893a244b2573b0/trunk/PKGBUILD)
wine staging + gallium nine 2.21:
[wine-compholio/wine-patched + sarnex/wine-d3d9-patches from wine-gaming-nine 2.21-2](https://gitlab.com/archlinux-packages-johnth/wine-gaming-nine/blob/bb428c15be89cfc5fb4581309be5ccede2bc17f0/PKGBUILD)
wine staging + gallium nine 2.18 showed the same symptoms.

```
grep DRI /var/log/Xorg.0.log
[    11.630] (**) RADEON(0): Option "DRI" "3"
[    12.095] (II) glamor: EGL version 1.5 (DRI2):
[    12.296] (II) RADEON(0): [DRI2] Setup complete
[    12.296] (II) RADEON(0): [DRI2]   DRI driver: r600
[    12.296] (II) RADEON(0): [DRI2]   VDPAU driver: r600
[    12.313] (**) RADEON(0): DRI3 enabled
[    12.426] (II) GLX: Initialized DRI2 GL provider for screen 0
```

`NINE_DEBUG=all` does not seem to add any output

Thanks

**Comment by siro20** [comment]
Does it work with csmt_force=0 ?
For NINE_DEBUG to function you need to compile Mesa with debugging enabled.
Does it work on DRI2 ?

**Comment by john-tho** [comment]
No difference with `csmt_force=0` or DRI2
[dri2-nine.log](https://github.com/iXit/Mesa-3D/files/1633208/dri2-nine.log)
[dri2-poe-nine-winedbg.log](https://github.com/iXit/Mesa-3D/files/1633209/dri2-poe-nine-winedbg.log)

I thought my [mesa compile options](https://gitlab.com/archlinux-packages-johnth/packages-modified/blob/f70c0338d1d7062e91eff31091893a244b2573b0/trunk/PKGBUILD#L45) should enable debug, but I may have missed something.  
`NINE_DEBUG=help` does give me a list of debug options.

**Comment by siro20** [comment]
If NINE_DEBUG=help gives you a list you have debugging enabled.
Can you find the regression in Mesa ? I guess 17.3.1 or 17.2 should work for you. Once found d you can start a bisect to find the bad commit.

**Comment by john-tho** [comment]
I didn't have debugging enabled in my 32bit mesa package, sorry.
[NINE_DEBUG=all from launch to frozen graphics](https://github.com/iXit/Mesa-3D/files/1634609/poe-nine-debug.log)

Without restarting between changing packages, I had the same problem with mesa 17.0, 17.1 and 17.2.
Going to reinstall system from December packages and try from there.

Thanks

**Comment by john-tho** [comment]
xorg-server 1.19.5-1 to 1.19.6-1 is my cause

xorg-server 1.19.5-1 works
xorg-server 1.19.6-1 frozen graphics

[The Arch package only updates the version](https://git.archlinux.org/svntogit/packages.git/commit/?id=a40a90d5850dee09940dd28d941500b2841df3db)

Any suspicious changes there?
I will start bisect tomorrow.

**Comment by axeldavy** [comment]
Fuck. Thanks for reporting.

It must be https://github.com/mirror/xserver/commit/5c00e693631475679c1c2504e03177652ec7de28

If this is this commit, please open a bug report to xorg, in order to begin the discussion on whether we do something wrong or they do. The spec also has to be discussed.

**Comment by john-tho** [comment]
Yes, caused by
> mirror/xserver@5c00e69

xorg-server
5c00e693631475679c1c2504e03177652ec7de28
present: Only send PresentCompleteNotify events to the presenting client


xorg-server 1.19.6 with this commit reverted works

> please open a bug report to xorg

I will open xorg bug in a few hours

Can anyone else confirm the above?

**Comment by axeldavy** [comment]
I cannot confirm, I cannot use my test machine for some time.
In the bug report, It may be useful to link to the part of the code where nine uses the Present extension:
https://github.com/iXit/wine/blob/master/dlls/d3d9-nine/dri3.c
(and https://github.com/iXit/wine/blob/master/dlls/d3d9-nine/present.c)

Two xcb connections are used, I guess that means two clients use the same windows and we hit what the patch disallows. I think it is legal according to the spec and thus the patch should be reverted, but this has to be discussed.

**Comment by john-tho** [comment]
[Xorg bug 104678](https://bugs.freedesktop.org/show_bug.cgi?id=104678) submitted

Thanks @siro20 & @axeldavy for the help tracking it down

**Comment by axeldavy** [comment]
Xorg issue should be fixed.
