### ISSUE TITLE
Stuck splash-screen on Halo: Custom Edition

### ISSUE THREAD

**Issue by Vaporeon** [iXit/Mesa-3D#301]
This game was released in three slightly different versions, a small demo, the original retail release and later a standalone multiplayer release with custom map support.

Interestingly, the original full retail release works fine using nine however with Custom Edition, the games splash screen will stay in place, flickering wildly depending on the video mode. The game does not hang and is still responsive to input.

Both versions were updated to the official 1.10 version using a clean wine-staging prefix with the nine patch applied. It was also tested with and without common mods.

**Comment by axeldavy** [comment]
by 'the game is still responsive to input' you mean the game plays ? or just the menu

**Comment by Vaporeon** [comment]
The game can be played blind however there is heavy graphical corruption and the initial loading splash screen lingers.
Example:
https://cdn.discordapp.com/attachments/406800875017863169/408477370371014657/haloerror.mkv
