### ISSUE TITLE
Halo: missing blood effect

### ISSUE THREAD

**Issue by Vaporeon** [iXit/Mesa-3D#302]
In the game "halo", spilt blood is missing from the ground.

Screenshot of blood taken in Windows 10
![with](https://cdn.discordapp.com/attachments/406800875017863169/406815134627921930/Screenshot_20180128_001549.png)

This one without is under wine-staging using nine.
![without](https://cdn.discordapp.com/attachments/406800875017863169/406815185257365504/Screenshot_20180128_002023.png)

**Comment by axeldavy** [comment]
Interesting. The game has a demo, we can use that for testing

**Comment by Vaporeon** [comment]
I have a spare key for this game if needed.

**Comment by axeldavy** [comment]
I could use that spare key.
However in all cases I don't have access to my nine dev machine for some time and cannot debug right now the issue.

**Comment by Vaporeon** [comment]
Okay, Let me know when you have access to a machine again and I'll send you the key.

**Comment by axeldavy** [comment]
Ok, I can work on the issue again now.

**Comment by Vaporeon** [comment]
OK, if still required tell me where to send the key to full or custom edition and I will send it.

**Comment by axeldavy** [comment]
I indeed do not have the blood effect. I took a trace and replayed on windows and there is no blood.
But perhaps I did the trace, wrong ? If you reload a game with dead bodies around you, there's supposed to be blood, right ?

**Comment by axeldavy** [comment]
Right, it seems when a trace with blook on wine is taken, it shows again when replaying with nine. It must be some flag advertised issue that makes it disabled.

**Comment by axeldavy** [comment]
I reinvestigated the issue and found the fix.

This is very weird because the trace of the game running under nine still doesn't have blood, but now when you run the game, it has blood. It's as if the game detects if the feature is working properly.

**Comment by axeldavy** [comment]
Broken again...

**Comment by axeldavy** [comment]
Even getting back at the commit that was supposed to fix the issue, It doesn't work. No idea what exactly triggered the good behaviour back then.

**Comment by axeldavy** [comment]
Looks like a small test patch I had when debugging the issue was actually important. Reintroducing it fixes it and the decals issue.
