### ISSUE TITLE
[nine][shader] Guild Wars 2 with Shaders on "medium"

### ISSUE THREAD

**Issue by siro20** [iXit/Mesa-3D#303]
![gw2](https://user-images.githubusercontent.com/2340747/35513791-7b113e24-0504-11e8-993a-3a9187bd5575.png)
The grass has some weird blue on radeonsi / llvmpipe. It doesn't happen on wine. Looks like a shader is faulty.

**Comment by siro20** [comment]
Looks like the vertex shader is broken, as the vertex/texture has a slight offset. It doesn't overlap with the previous calculated lightmap, causing the blue artifacts.

**Comment by axeldavy** [comment]
Do you happen to have a trace ?

**Comment by siro20** [comment]
Uploaded on our FTP: Gw2-64.5.trace.xz

**Comment by axeldavy** [comment]
Fixed
