### ISSUE TITLE
Evoland 2 does not work, and already shows trouble at menus

### ISSUE THREAD

**Issue by kode54** [iXit/Mesa-3D#318]
I've run the latest version of Evoland 2, from Steam Play, through Gallium Nine, using wine-d3d-staging version 3.15~b from ppa:commendsarnex/winedri3, dated 2018-09-02.

Hardware and software specs from Steam, I'm testing on the bottom spec (RX480, AMDGPU/RadeonSI):

https://gist.github.com/kode54/3ff952f39b407d6f806a6779838f5335

The game is nigh unplayable in Steam's Proton, even the latest 3.7-5 Beta.

With wine-d3d9-staging, with Gallium Nine disabled, it's fully playable, quite fast, loading times not withstanding. With Gallium Nine enabled, the menu text renders completely transparent and therefore unreadable, and upon attempting to load my save, the game locks up.

I'm providing three apitrace traces in a rather large (209MB) .tar.xz.

evoland2_wrapped_gl.trace [Linux, GL] - Working, via the regular D3D9 to GL wrapper, captured by Linux apitrace.
evoland2_d3d9_galliumnine.trace [Win, D3D9] - Traced by Windows mingw apitrace d3d9, running under wine-d3d9-staging with Gallium Nine enabled, stopped by ctrl-c to the terminal when the game apparently locked up.
evoland2_d3d9_working.trace [Win, D3D9] - Also traced by Windows mingw apitrace d3d9, running under wine-d3d9-staging with Gallium Nine disabled, managed to make it in-game to the 3D overworld, which takes a full 3 seconds to load in-game but less time on replay, and then back to the menu and quit again.

https://f.losno.co/evoland2_traces.tar.xz

**Comment by iiv3** [comment]
Few tips.
- Use the msvc apitrace build. The mingw one is not updated and it might not recent fixes. In your case it seems that it worked fine, so no problem.
- Usually we would only need the "working" trace. You just have to test replaying it both with wined3d and Nine. Anyway, no need to reupload and edit your post.

I do hope we have your permission to upload that trace to the private nine ftp, so it could be used for regression testing.

I did replay the trace, right before showing the menu a shader is dumped to the console and then every draw operation that uses it returns an error. This greatly slows down the replay.
I see menu text as white rectangles and in-game I only see some UI elements and the in-game menus.

It renders perfectly with wined3d.

**Comment by axeldavy** [comment]
Thank you for these traces.

The game uses a feature not seen in many d3d9 games, and in fact I'm happy to have an example now to implement the feature (predicated instructions).

**Comment by axeldavy** [comment]
To my knowledge, wine doesn't support predicate either, and may compile a incorrect shader. Do you have any misrendering ?

**Comment by axeldavy** [comment]
This seems fixed with my new implementation of predicated instructions.

Please share if there is any visual error with our implementation (which is currently on this repo)

**Comment by kode54** [comment]
I'll check out your work, as soon as I get a build environment working, or hopefully if my source of binaries picks it up.
