### ISSUE TITLE
WoW 1.12 wrongly colored lighting

### ISSUE THREAD

**Issue by Oschowa** [iXit/Mesa-3D#319]
World of Warcraft version 1.12 when running under Nine shows wrongly colored lighting effect on windows which is not present when running under wined3d. I captured an apitrace which shows the issue, notice the violet tint on the windows.

I tested with:
wine 3.16
radeonsi RX560 / r600 HD5850
Mesa 18.2 (LLVM 6) / 17.3 (LLVM 6)

[apitrace](https://drive.google.com/open?id=1F6TxD2Dh2d6bUUVz67y9e3-Fg8O53JYG)

**Comment by axeldavy** [comment]
Thank you for this trace and bug report.

Apparently the tint is due to the fog rendering.
The fog parameters are wrong because it uses a previously set value (not the most up to date) because it incorrectly thinks its internal parameters were updated.

I'll fix shortly.

**Comment by Oschowa** [comment]
Thank you for looking into it and fixing it so quickly.
