### ISSUE TITLE
Latest changes in mesa master broke something.

### ISSUE THREAD

**Issue by rox4d** [iXit/Mesa-3D#331]
commit:
1cc8192ad0be52220043d40f2c7ead149d479809 
st/nine: Switch to presentation buffer if resize is detected
broke d3dretrace  with trace from #324 (it crashes witn nouveau now) , reverting this change are restoring behaviour.

**Comment by iiv3** [comment]
Crashes on r600 too.

**Comment by axeldavy** [comment]
I added the zero

**Comment by iiv3** [comment]
It fixes the "Tomb Rider" trace playback for me.
