### ISSUE TITLE
Halo / Halo Custom Edition Broken cubemaps

### ISSUE THREAD

**Issue by Vaporeon** [iXit/Mesa-3D#337]
Currently cubemaps render wrong in halo, they seem to be rotated 90 degrees.
Gallium Nine:
http://vaporeon.io/archive/img/haloce_broken.png

wine3d:
http://vaporeon.io/archive/img/haloce_working.png

Mesa: 18.3.3
wine-staging: 4.0
gallium-nine-git: https://github.com/iXit/wine-nine-standalone/commit/90ef914ee6a74d21ceb7d330501fee7cc0ba7a8d

**Comment by iiv3** [comment]
Can you provide an apitrace showing the issue(s)?
It may be uploaded to our ftp and kept for regression testing.

**Comment by Vaporeon** [comment]
Sure but whenever I create a trace for this game playing it back shows a black screen.

**Comment by iiv3** [comment]
That's bad.

Another program that can take D3D9 traces is PIXWin from the June 2010 DirectX SDK. If you feel like it you may try your luck with it. Better to do it under native windows.

If I understand correctly Halo Custom Edition is free upgrade for everybody who has the original Halo.
Does any of the problems appear with the original Halo?

**Comment by Vaporeon** [comment]
Halo custom edition is a standalone version of the game with custom map support. they both use the same CDkey system, there is a trail version too for the retail release.
Note though that they changed the shaders in custom edition and it behaves differently in some cases.

I'll try PIXWin and see what happens.

**Comment by Vaporeon** [comment]
Oh, AMD RX 580

**Comment by axeldavy** [comment]
Maybe this will help ?
https://github.com/iXit/Mesa-3D/commit/d74b6f949d6d3b9f89655fa012cb22b7479ccee6

**Comment by Vaporeon** [comment]
I cherry-picked this commit and applied it to stable mesa and it did not change anything.

**Comment by axeldavy** [comment]
Could you provide a savegame displaying the issue ?

**Comment by Vaporeon** [comment]
You can start a LAN MP game on "Death Island" and look out over the water to see it.

**Comment by axeldavy** [comment]
The buggy draw had a shader with:
```
    texm3x3pad t1, t0_bx2
    texm3x3pad t2, t0_bx2
    texm3x3vspec t3, t0_bx2
```
It seems in this case we ignored the bx2.
