### ISSUE TITLE
NIR support for Gallium Nine

### ISSUE THREAD

**Issue by Venemo** [iXit/Mesa-3D#339]
We need to support NIR in case users want to run Gallium Nine with drivers that don't support TGSI. So far this hasn't been a problem because nouveau and the radeon drivers all support and primarily work with TGSI. However, as-is, nine won't work with iris (and I think it also won't work with zink).

I've started the work on this branch:  
https://github.com/Venemo/Mesa-3D/commits/nine-nir

Just opened this issue to provide a place to document our progress.

**Comment by Venemo** [comment]
The decision is that we don't want to port nine to NIR just yet, so we wanna use `tgsi_to_nir` (aka TTN). TTN was originally written to work on the output of `glsl_to_tgsi` so it should have us covered for the most part. More recently however, TTN hasn't been used for any serious purpose, and therefore is subject to bit rot and it was also never tested with nine, so some features are unsupported.

Problems encountered so far:

1. `ttn_src_for_file_and_index`: in `case TGSI_FILE_SYSTEM_VALUE` when it gets `TGSI_SEMANTIC_POSITION` it crashes with `"bad system value"`. I added the recommended `nir_intrinsic_load_frag_coord` but now it sometimes generates incorrect shaders. Need to investigate more.
2. There is no concept of `TGSI_PROPERTY_VS_WINDOW_SPACE_POSITION` in NIR, so I added a `bool` variable to `shader_info` and let radeonsi use that the same way. It is however not supported in other NIR drivers.
3. It is unclear which NIR lowering and optimization passes are required and this is not documented. So far, I've added what was recommended. A good guideline is that the NIR that we output should be mostly in line with what `glsl_to_nir` outputs, so that' a place to look for more.

Current status:

Some games run (window is created, music is played) but have a black screen (when NIR vertex shaders are used) and/or bad colors (when NIR pixel shaders are used).

**Comment by dhewg** [comment]
Same status on iris: it builds, games "work" (black window, but sound and input works).
The D3D SDK sample `HLSLwithoutEffects.exe` renders *something*:

iris:
![](https://i.imgur.com/v7kXFSw.png)

radeonsi:
![](https://i.imgur.com/zVwZFrv.png)

**Comment by dhewg** [comment]
One shader's [tgsi](https://pastebin.com/vqfQ25uh) and [nir](https://pastebin.com/bPb0KaTG).
gcn asm at the bottom.
````
16:04:11 <mannerov> TGSI constants have 4 channels
16:04:17 <mannerov> xyzw
16:04:32 <mannerov> somehow the nir one it's as if there was only x
16:04:44 <mannerov> everything gets thus compacted
````

**Comment by Venemo** [comment]
Looking more closely at the problem shader, Axel pointed out that the problem is with the constant data (aka. NIR `load_uniform`). From there I figured out that somehow it indexes the constant data incorrectly. The problem may have been with the conversion from uniforms to UBO, but TTN already had a case that generated an UBO, so I decided to delete the code that generated a uniform:

https://github.com/Venemo/Mesa-3D/commit/cb1f24cf5ed54e5d8cbcfa56588147f20173f5db

Now I no longer get a black screen with `NINE_NIR=vs`, just visual glitches.

**Comment by dhewg** [comment]
With that patch and Witcher 1 on gallium nine on iris:
![iris-witcher1](https://user-images.githubusercontent.com/605548/52367270-f69e6400-2a4b-11e9-8ee4-2ad99ba0327d.png)
Quite some glitches, but no more solid black ;)

**Comment by dhewg** [comment]
Witcher 2 has similar glitches:
![](https://i.imgur.com/ATZQa91.png)

**Comment by Venemo** [comment]
>  `ttn_src_for_file_and_index`: in `case TGSI_FILE_SYSTEM_VALUE` when it gets `TGSI_SEMANTIC_POSITION` it crashes with `"bad system value"`. I added the recommended `nir_intrinsic_load_frag_coord` but now it sometimes generates incorrect shaders. Need to investigate more.

Actually nine checks `PIPE_SHADER_CAP_TGSI_FS_POSITION_IS_SYSVAL` before using it. So this problem can be worked around by setting that flag to false when using nir.

**Comment by Venemo** [comment]
Here is my latest branch: https://gitlab.freedesktop.org/Venemo/mesa/commits/nine-nir-wip - I've cleaned up the work I've done so far.

**Comment by dhewg** [comment]
with the latest patches witcher2 looks like this

radeonsi tgsi:
![](https://i.imgur.com/tanYeaB.png)
radeonsi nir:
![](https://i.imgur.com/nxrgbCH.png)
iris nir:
![](https://i.imgur.com/6vLSf2r.png)

**Comment by dhewg** [comment]
iris nir glitches less with the "high" rendering profile:
![](https://i.imgur.com/jj5TJnu.png)

**Comment by Venemo** [comment]
Yay, we had an article on Phoronix: https://www.phoronix.com/scan.php?page=news_item&px=Gallium-Nine-Working-On-NIR

Also, I've fixed up my TTN patches according to the reviews and the IRC discussions. [See this comment for details.](https://gitlab.freedesktop.org/mesa/mesa/merge_requests/225#note_115289)

**Comment by gcavalcante8808** [comment]
Is this feature compatible with Intel Iris driver? I just updated to mesa 19.1 (Oibaf) and Cormerx wine-d3d and tried to launch World of Warcraft 2.4.3 with the command `MESA_LOADER_DRIVER_OVERRIDE=iris wine Wow.exe` and I got the following result:

```
../src/gallium/drivers/iris/iris_program.c:1388: iris_create_shader_state: Assertion `state->type == PIPE_SHADER_IR_NIR' failed.
```

Thanks in advance.

**Comment by dhewg** [comment]
It is compatible, but the pieces haven't yet been merged to mesa master.
See https://gitlab.freedesktop.org/mesa/mesa/merge_requests/225
And after that a small patch to hook tgsi->nir up in iris/nine.

**Comment by Venemo** [comment]
@gcavalcante8808 It should be compatible once our patches are merged into mesa, but I wouldn't expect WoW to work perfectly yet. Since it is also a Blizzard game, I would expect that in WoW there will be similar issues as we've seen in SC2. Iris is still in heavy development, so this will get better over time.

**Comment by Venemo** [comment]
I've figured out the reason for the Witcher 1 problem, and filed a bug against iris: https://bugs.freedesktop.org/show_bug.cgi?id=109781 ― once this is solved, Witcher 1 will run flawlessly on nine+iris.

With regards to SC2: I'm seeing a lot of flashing and flickering textures, and some black areas. It is not totally bad since [the iris clear patch](https://gitlab.freedesktop.org/mesa/mesa/commit/cacf84ed5ff48a3f4ea3fcb22b727732b723c352), but it still feels broken.

**Comment by gcavalcante8808** [comment]
Hi Folks, I just updated my intel drivers yesterday based on phoronix news about the merge and Im able to play Wow 2.4.3 almost flawlessly! I would like to thank you for the awesome work! 

![image](https://user-images.githubusercontent.com/640897/54085297-8bca9c00-431b-11e9-8659-6b800052410b.png)

Just some corruption on icons, but I can live with it!

**Comment by Venemo** [comment]
@gcavalcante8808 Thanks for your kind words. We can investigate what causes the bad icons. Can you please record an apitrace for us? [Here is how you can do that.](https://github.com/iXit/wine-nine-standalone/wiki/apitrace).

**Comment by gcavalcante8808** [comment]
I tried to trace, but the corruption just occurs after a few minutes (15+). Is there any other strategy to debug?

**Comment by Venemo** [comment]
@gcavalcante8808 Hard to say, we'll have to think about it. A 15+ minute trace would result in a pretty big file, though there may be ways to compact it...

One more question: do you see get shadows in WoW? I'm asking because currently shadows are missing from SC2 (another Blizzard game), and I also don't see any shadows on your screenshot, but not sure if that's because you disabled them or because of the same bug.

**Comment by gcavalcante8808** [comment]
@Venemo just a very simple shadow, but I dont remember if the game had good shadows in its release time.

![image](https://user-images.githubusercontent.com/640897/54092921-c9a5df80-4370-11e9-9ce4-cff04be3d47f.png)

**Comment by dhewg** [comment]
Some iris fixes landed on master, maybe the icons render properly now?

**Comment by Venemo** [comment]
I'm closing this issue, since NIR support is pretty much done now. Let's open separate issues for specific problems.

@gcavalcante8808 Can you please open a new issue for your WoW problem? I would suspect that it's likely to be an iris bug (rather than a nine bug or a tgsi_to_nir bug), but would still be nice to track that problem here.
