### ISSUE TITLE
Gallium Nine no longer increases FPS in StarCraft 2. Probably needs rebase after the latest Wine commit.

### ISSUE THREAD

**Issue by Kerrung** [iXit/Mesa-3D#341]
Hi! Gallium Nine no longer increases FPS in StarCraft 2 if I use the newest  [Wine commit](https://source.winehq.org/git/wine.git/commit/f7b3120991df02ecaa975c18c6421fedb48ae731).
I can assume that this began to happen after [this Wine commit](https://source.winehq.org/git/wine.git/commit/c74c8800b3e8b2f89a43c38b9d90de675abae0ae) but at the moment I have not checked this statement. But I know for sure that this does not happen if I use this commit. If this helps you, then I can try rebuilding Wine several times using different commits to find out exactly which commit causes Gallium Nine to fail. Should I do this?
Thank you.

**Comment by axeldavy** [comment]
How to you use nine with wine ? Do you use the wine nine standalone, or sarnex's patches, or something else ?

**Comment by Kerrung** [comment]
sarnex's patches

**Comment by axeldavy** [comment]
I would suggest to try the alternative
https://github.com/iXit/wine-nine-standalone

Just to check it is not an issue with the patches

**Comment by Kerrung** [comment]
I have not a PKGBUILD to compile it. I am on Arch Linux.

**Comment by Kerrung** [comment]
This issue only appears after updating Wine to [the latest Wine commit](https://source.winehq.org/git/wine.git/commit/f7b3120991df02ecaa975c18c6421fedb48ae731). This issue is missing if I use .
[this  a slightly older Wine commit](https://source.winehq.org/git/wine.git/commit/c74c8800b3e8b2f89a43c38b9d90de675abae0ae).

**Comment by axeldavy** [comment]
maybe the sarnex patches don't apply well with this change.

the alternative I suggested may still work. I think there are some aur package for it. Else there is a binary in the repo. You don't need root rights to add nine to your wine dir.

**Comment by Kerrung** [comment]
There is no wine-nine-standalone binary package in the official Arch Linux repositories or in the AUR.

**Comment by axeldavy** [comment]
lib32-gallium-nine

**Comment by Kerrung** [comment]
Ohhh... Thank you, I will try it.

**Comment by Kerrung** [comment]
[UPDATE]:
Wine cannot compile at all now if @sarnex 's Gallium Nine patches are applied. I use this commit:
https://github.com/wine-staging/wine-staging/commit/c6aeba1397722b9ccb88f7c3bae68da84144bb35

![screenshot from 2019-02-10 14-00-06](https://user-images.githubusercontent.com/36989404/52532082-fc908f80-2d40-11e9-97c3-7c1553d14c2f.png)

**Comment by Kerrung** [comment]
@axeldavy I compiled and installed the gallium-nine-git lib32-gallium-nine-git packages.
But I don’t know how to apply them to my WINEPREFIX now? Would you tell me how to do this, please?
Why is this information not in the Wiki of this repository?

**Comment by axeldavy** [comment]
Is it all explained in the README of
https://github.com/iXit/wine-nine-standalone

**Comment by dhewg** [comment]
Did you get the standalone version working? Does SC2 use nine with that again?

**Comment by Kerrung** [comment]
>Did you get the standalone version working? Does SC2 use nine with that again?

@dhewg  Unfortunately, I could not find my free time to do this. I will inform you about the results as soon as I find the time to do it. Thank.

**Comment by montvid** [comment]
SC2 works okay with gallium nine here. Cpu and gpu load is ~40℅ always and about 60 fps. Don't know if it should have more fps.

**Comment by Kerrung** [comment]
@montvid look here, please: https://github.com/iXit/Mesa-3D/issues/343

**Comment by montvid** [comment]
@Kerrung I use g9 standalone and it works with wine 4.1 or tkg 4.1 - worse or better can't realy tell. Just compiled it myself the latest master. Do you mean g9 does not load at all when you run a game? I clearly see in the log that it runs.

**Comment by Kerrung** [comment]
https://github.com/sarnex/wine-d3d9-patches
@montvid my issue is about @sarnex 's patches, not about standalone version. May be standalone version works perfect, but I don't care about it. Thank you.

**Comment by Kerrung** [comment]
https://github.com/sarnex/wine-d3d9-patches
@montvid my issue is about @sarnex 's patches, not about standalone version. May be standalone version works perfect, but I don't care about it. And I still waiting when @sarnex do rebase his patches.
Thank you.

**Comment by dhewg** [comment]
What's the issue with standalone?

**Comment by Kerrung** [comment]
>What's the issue with standalone?

@dhewg Unfortunately, I could not find my free time to do this. I will inform you about the results as soon as I find the time to do it. Thank.

**Comment by Venemo** [comment]
@Kerrung Wine 4.2 staging here. SC2 works pretty well with Gallium Nine Standalone on this version. Should be easy enough to set up but if you have problems with it, we're here to help.

**Comment by Kerrung** [comment]
Since Wine Staging 4.3 applying the @sarnex 's Gallium Nine patches will be not supported by Wine anymore. So, this issue loose the actuality, then I close it. Thank you!
