### ISSUE TITLE
Wine Staging cannot be compiled at all now if @sarnex 's Gallium Nine patches are applied.

### ISSUE THREAD

**Issue by Kerrung** [iXit/Mesa-3D#343]
Wine cannot be compiled at all now if @sarnex 's Gallium Nine [patches](https://github.com/sarnex/wine-d3d9-patches) are applied. I use this commit:
https://github.com/wine-staging/wine-staging/commit/c6aeba1397722b9ccb88f7c3bae68da84144bb35

My specs is:
Arch [Linux](https://www.archlinux.org/packages/core/x86_64/linux/),  AMD Radeon HD7850, ordinary [Mesa-git](https://gitlab.freedesktop.org/mesa/mesa/commits/master), AMDGPU kernel driver, [Wine git](https://source.winehq.org/git/wine.git/commit/f7b3120991df02ecaa975c18c6421fedb48ae731) + [Wine Staging Git](https://github.com/wine-staging/wine-staging).

![screenshot from 2019-02-10 14-00-06](https://user-images.githubusercontent.com/36989404/52532082-fc908f80-2d40-11e9-97c3-7c1553d14c2f.png)

**Comment by sarnex** [comment]
I have not released my patches for 4.1 yet, only 4.0. Please wait until then.
