### ISSUE TITLE
Max: The Curse of (bloody) Brotherhood

### ISSUE THREAD

**Issue by dungeon007** [iXit/Mesa-3D#346]
Sorry about title, to not be boring i feel like somehow there is a point :dancer: 

 AMDGPU used and trace is here:

 https://www.dropbox.com/s/53mrle21uk9380h/Max2-bloodytreebug.trace.xz?dl=0

 Or in pictures under the tree, nine looks like this here and wined3d like that: 

  https://i.postimg.cc/Ls26FqS0/nine.png

  https://i.postimg.cc/TPtG8CCp/wined3d.png

 Or in videos how it should look like @ 05:35

 https://www.youtube.com/watch?v=pGpHp1tTZZw

 D3D_ALWAYS_SOFTWARE=1 is OK or -force-d3d9-ref also OK, UNITY_DISABLE_GRAPHICS_DRIVER_WORKAROUNDS=yes does not help. blah, blah...

 Kind on half of things are fine and another half don't, kind of maybe like in Rayman Legends or maybe not... or just some shader issue

**Comment by iiv3** [comment]
I can see the bug on my R600 Redwood Evergreen HD5670.
It is not affected by `csmt_force=0`.
It happens with mesa-19.1.git+mesa-ixit patches from few days ago and with mesa-11.2.2 , so likely not a regression.
I bisected frame 500, the first draw call for the red tree seems to be 1728899.

**Comment by dungeon007** [comment]
Well, i forgot to mention that game uses Unity 4.3.1 that might help.

 I am guessing that ParticleSystem making a bug, as not every particles do this but some do. If not entire editor but basically one could download source of unity built in shaders for that version and maybe to guess which one of these 9 variant making this bug 

 https://download.unity3d.com/download_unity/builtin_shaders-4.3.1.zip

**Comment by axeldavy** [comment]
Looks like the game writes to all 4 components of 'fog' (last shader version of d3d has fog with 4 components).
It is a behaviour that I thought was supposed to work, but we map to TGSI_SEMANTIC_FOG which has only one component in gallium. I need to use something else.
