### ISSUE TITLE
Panzers Phase I game crashes in NineSwapChain9_Resize on r300 (RV530)

### ISSUE THREAD

**Issue by FabioPedretti** [iXit/Mesa-3D#46]
Using main oibaf + DDX dri3 + wine dri3 PPAs with game Panzers Phase I. The game runs fine with gallium-nine disabled. After enabling gallium-nine the game freezes, switching to console and then again to X I see this:
```
Edit: long log removed for clarity, see below the updated log.
```
Note: I tried other games (including Panzer Phase II) and they don't crash (they don't render properly however).

**Comment by FabioPedretti** [comment]
Modified swapchain9.c file (I added some DBG("point X\n") lines): http://pastebin.com/raw.php?i=rDUszfjn
New debug output: http://pastebin.com/raw.php?i=8HnHYsZi

Let me know if it's enough.

**Comment by axeldavy** [comment]
if you replace:
if (newBufferCount != oldBufferCount)
by
if ((newBufferCount != oldBufferCount) || (has_present_buffers && !This->present_buffers))
does it work ?

**Comment by axeldavy** [comment]
or rather (similar but better)
if ((newBufferCount != oldBufferCount) || (has_present_buffers != !!This->present_buffers))

**Comment by FabioPedretti** [comment]
I tested the second approach and it no longer crashes indeed!

Just for the record I had this issue only with r300, when using D3D_ALWAYS_SOFTWARE=1 this was not reproducible.

**Comment by axeldavy** [comment]
Fixed pushed to master

**Comment by FabioPedretti** [comment]
Hi, I tried current master from iXit on my RV530 but it doesn't work properly as the fix tested on my previous comment. As soon as I start the game I get a wine pop up window with this message:
```
SGepard::ResetDevice: Reset failed:
D3DERR_DEVICELOST
```
Here is the full output with NINE_DEBUG=all : http://pastebin.com/raw.php?i=6GeVUSVa

It still works fine when running with D3D_ALWAYS_SOFTWARE=1

**Comment by axeldavy** [comment]
I would be interested to have the info of where it crashes in NineSwapChain9_Resize.

You were likely hitting two bugs, and I solved only one on master.

**Comment by axeldavy** [comment]
oh wait, it doesn't crash, but gives error

**Comment by axeldavy** [comment]
ok I found the error. You hit the problem with master because we do more checks now. But it probably wasn't working perfectly when you tried the simple fix

**Comment by axeldavy** [comment]
Probably fixed on master, please retry

**Comment by FabioPedretti** [comment]
I am still getting the wine little window titled "Fatal error" with this text:
```
SGepard::ResetDevice: Reset failed:
D3DERR_DEVICELOST
```
and the OK button. When I press OK the game exit. Updated console output with NINE_DEBUG=all : http://pastebin.com/raw.php?i=EZKeakRB

**Comment by axeldavy** [comment]
ok, I think I found the problem.

Can you try again master ?

**Comment by FabioPedretti** [comment]
Good work, it no longer crashes or exit now!
I filed a new bug for missing rendering at #62 .
