### ISSUE TITLE
Repetitive messages about unsupported TGSI opcode

### ISSUE THREAD

**Issue by Bitiquinho** [iXit/Mesa-3D#47]
Trying to launch Tomb Raider Legend and Tomb Raider Anniversary (latest updates from Steam) with Nine gives me the output (only relevant parts, I guess):

> [...]
> fixme:d3d9:d3dadapter9_new 
> Native Direct3D 9 is active.
> For more information visit https://wiki.ixit.cz/d3d9
> fixme:system:SystemParametersInfoW Unimplemented action: 59 (SPI_SETSTICKYKEYS)
> fixme:win:EnumDisplayDevicesW (L"\\.\DISPLAY1",0,0x33e254,0x00000000), stub!
> fixme:d3dadapter:DRI3PresentGroup_GetMultiheadCount (0x1fcae8), stub!
> fixme:d3dadapter:DRI3PresentGroup_GetMultiheadCount (0x1fcae8), stub!
> [MSFileSourceDisk::Open] Filename: \TR7\game\pc\TR7.arg
> fixme:advapi:RegisterTraceGuidsW (0x2b024d0, 0x2b0d6e8, {7c830ece-5fb3-417a-a1bd-508f45277356}, 1, 0x33e534, (null), (null), 0x2b0d6f0): stub
> fixme:wbemprox:client_security_SetBlanket 0x633925a4, 0x1ebbc0, 10, 0, (null), 3, 3, (nil), > 0x00000000
> fixme:wbemprox:client_security_Release 0x633925a4
> fixme:wbemprox:enum_class_object_Next timeout not supported
> fixme:wbemprox:client_security_SetBlanket 0x633925a4, 0x1ebba8, 10, 0, (null), 3, 3, (nil), 0x00000000
> fixme:wbemprox:client_security_Release 0x633925a4
> fixme:wbemprox:enum_class_object_Next timeout not supported
> fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x4160416, 0000: semi-stub!
> EE r600_shader.c:2516 tgsi_unsupported - NOP tgsi opcode unsupported
> EE r600_shader.c:158 r600_pipe_shader_create - translation from TGSI failed !
> EE r600_state_common.c:757 r600_shader_select - Failed to build shader variant (type=1) -22
> EE r600_shader.c:2516 tgsi_unsupported - NOP tgsi opcode unsupported
> EE r600_shader.c:158 r600_pipe_shader_create - translation from TGSI failed !
> EE r600_state_common.c:757 r600_shader_select - Failed to build shader variant (type=1) -22
> [...]

Everything runs fine and with more FPS when not using Nine (With Nine and TR Legend, I even have some weird screen blueness: http://imgur.com/1hzcQCs ) 

I suppose I have to dump the shader to find the problematic one. How could I do it ?

**Comment by axeldavy** [comment]
for the performance, it's possible that wine and nine get different rendering path, because of difference caps/formats advertised.

**Comment by axeldavy** [comment]
I close the bug report as it is fixed (as for the performance, I don' t know, but it likely has evolved since)
