### ISSUE TITLE
Black hangar and battle field in World of Tanks with improved settings.

### ISSUE THREAD

**Issue by steemandlinux** [iXit/Mesa-3D#54]
http://i.imgur.com/p4d99sl.png

iXit repo git (oibaf/gallium-nine), llvm-3.5, linux-git, wine-1.7.33, d3dx9_?? installed, r9 280x.

log: http://www.mediafire.com/download/bfvew5g3gb2rvrq/wot-nine-improved.log.xz

**Comment by axeldavy** [comment]
Is it the same for both mesa-git and ixit repo ?

**Comment by steemandlinux** [comment]
Oh sorry. With iXit git, not freedesktop mesa.  With freedesktop mesa build I get the bug #42. And black hangar with iXit repo. Log from iXit repo.

**Comment by axeldavy** [comment]
Radeonsi card ?
LLVM 3.5 triggers this bug, but llvm-svn doesn't. So it's going to be fixed for 3.6
