### ISSUE TITLE
Lotro fails with radeon: Failed to allocate a buffer:

### ISSUE THREAD

**Issue by oneru** [iXit/Mesa-3D#56]
Fedora 21 with mesa recompiled with the patch set recently sent in to mesa. Running Wine 1.7.33 built from this repo. An AMD hd6850. Trying to run Lord of the Rings Online. It runs correctly with vanilla wine. We use pylotro to launch the game. This log is run with +d3dadapter9,+d3d9

The game loading screen never comes up.

http://incomsystems.biz/lotro.log

**Comment by axeldavy** [comment]
The error is very strange.
The error message can only come for dri3 glx backend, but we don't use it.
Probably the game is checking both d3d9 and gl.

Are you using our ati ddx branch implementing dri3 ? Try using the normal ati ddx. We have DRI2 fallback now.

**Comment by oneru** [comment]
I was using the ddx branch from here. However, I had yum reinstall the xorg-x11-drv-ati package, which I believe should return me to the Fedora version.

I think Fedora 21 ships dri3 enabled xf86-driver-ati, so not sure it matters.

**Comment by axeldavy** [comment]
can you try again with the ati ddx of Fedora with our last git branches ?

**Comment by axeldavy** [comment]
I guess game is fixed now. Re-open if not.
