### ISSUE TITLE
Battle.net and starcraft 2 exception

### ISSUE THREAD

**Issue by maaniv** [iXit/Mesa-3D#57]
When Native Direct3D 9 is active minimize and maximize battle.net application throws an exception. In starcraft 2 after intro, while loading, throws exception. Without Native Direct3D 9 all is ok. Mesa and wine from iXit git. I use radeon 7850 with dri2 opensource driver. Sorry for bad English.
https://gist.github.com/maaniv/7bd70a4fcbe78c735373#file-battle-net-log
https://gist.github.com/maaniv/a60c358ff5402eb1a0d4#file-starcraft-2-log

**Comment by axeldavy** [comment]
is it solved now on mesa ixit git ?

**Comment by maaniv** [comment]
No.

**Comment by axeldavy** [comment]
to get more debug output, can you build mesa with --enable-debug and use NINE_DEBUG=all ?

**Comment by maaniv** [comment]
I'm not sure I did it properly.
Actions:
1. Added --enable-debug in pkgbild.
2. Build mesa (makepkg -si) and install new packages
3. export NINE_DEBUG=all
4. run battle.net with exception
https://gist.github.com/maaniv/bb177e609c2937ccf3ad#file-battle-net-debug-log

**Comment by axeldavy** [comment]
yep, something is wrong, but I don't know what exactly. The debug outputs aren't there.

**Comment by maaniv** [comment]
I am rebuilded only 64 bit mesa. Sorry. With 32 bit mesa git all is ok. Thanks!
