### ISSUE TITLE
3DMark05 crashes in NineDevice9_dtor on r600 (RS880)

### ISSUE THREAD

**Issue by kakurasan** [iXit/Mesa-3D#58]
After pressing "Run 3DMark" button, 3DMark05 crashes.
If native Direct3D 9 is disabled, this program runs.

Log: https://onedrive.live.com/?cid=3F9BE5B1CD4A806C&id=3F9BE5B1CD4A806C!2416

ppa:oibaf/graphics-drivers + ppa:commendsarnex/winedri3 + iXit/Mesa-3D add861e1fc

**Comment by axeldavy** [comment]
Did you test some time before ?

I guess it is a recent bug

**Comment by axeldavy** [comment]
Is it solved now on master ?

**Comment by kakurasan** [comment]
Yes, it works fine. Thanks.

ppa:oibaf/graphics-drivers + ppa:commendsarnex/winedri3 + iXit/Mesa-3D 6fc5122e43
