### ISSUE TITLE
Dark Souls II crashes on start

### ISSUE THREAD

**Issue by sobkas** [iXit/Mesa-3D#59]
When I use latest Mesa from https://github.com/iXit/Mesa-3D.git, Dark Souls 2 crashes on startup:
http://sta.sh/download/3441774045465980/log_by_fboxnf-d8ea3gu.xz?token=c3556b5a88fef302fa53bdbe08766df40dcca29b&ts=1421526250
I have used NINE_DEBUG=all WINEDEBUG=+d3dadapter9,+d3d9, Game starts through steam if I try to run it wine DarkSoulsII.exe, so I dumped steam output, but it didn't do a lot, so need an advice what to do next.

**Comment by sobkas** [comment]
Other log, still not much:
http://sta.sh/0gwo8o6j7vn

**Comment by sobkas** [comment]
New log: http://sta.sh/0vmsbotqqxp

**Comment by rboxeur** [comment]
AFAIR to play this game you must first launch it without using GalliumNine so all files for your save game can be initialized. 
1) Uncheck "GalliumNine" through winecfg. Launch the game. No worry about flickering screen. When you get into the main menu. Just exit
2) Check "GalliumNine" through winecfg. Rerun the game; That should do it.
That was I did so I can do thsi video https://www.youtube.com/watch?v=R2-aXOAoT58&index=5&list=PLhmTqTnY5Ke_wQ771BiiJaye0K9j-738p 
Hope it helps

**Comment by sobkas** [comment]
Actually mannerov wrote this patch and it fixes the problem with start(before even the white screen appears) so it might have been other problem:
diff --git a/src/gallium/state_trackers/nine/vertexdeclaration9.c b/src/gallium/state_trackers/nine/vertexdeclaration9.c
index dd0887e..8986d30 100644
--- a/src/gallium/state_trackers/nine/vertexdeclaration9.c
+++ b/src/gallium/state_trackers/nine/vertexdeclaration9.c
@@ -190,7 +190,7 @@ NineVertexDeclaration9_ctor( struct NineVertexDeclaration9 *This,
     }
 
     caps = NineDevice9_GetCaps(This->base.device);
-    user_assert(0 < This->nelems && This->nelems <= caps->MaxStreams, D3DERR_INVALIDCALL);
+    user_assert(0 <= This->nelems && This->nelems <= caps->MaxStreams, D3DERR_INVALIDCALL);
 
     This->decls = CALLOC(This->nelems+1, sizeof(D3DVERTEXELEMENT9));
     This->elems = CALLOC(This->nelems, sizeof(struct pipe_vertex_element));

**Comment by rboxeur** [comment]
Still have work! Will try to test this in a couple of hours when get back home

**Comment by sobkas** [comment]
When you go to the shacks in no man wharf, does the system locks up?

**Comment by axeldavy** [comment]
It isn't my patch, but a recent patch of siro20. However it is incomplete and needs some more work.

**Comment by sobkas** [comment]
rboxeur: ping

**Comment by rboxeur** [comment]
Apologies I was quite busy these past days.  Should be able to test this tomorrow. Still at work but should test this ASAP :)  today

**Comment by rboxeur** [comment]
Using the work-around to start this game is seems and using GalliumNine


- commit add861e1fc8e783f5ab9f7fbe07125e02c49fbc0: KO..game crashes!


- commit 497d974fd27f4f8366de2eaac3fd8a1b3c3f0ad5: OK...game can be played

I need to do more tests.

I am testing both the current wine and wine-staging version (www.wine-staging.com) applying the latest GalliumNine patch for wine.

I will let you know if I have any update :)

**Comment by rboxeur** [comment]
Hey sobkas,

The system locks up from me too  in no man wharf (near the shacks). 

The latest commit I tested and for which I can start the game is 1458197e040f29960066c291d969079889c3961f

**Comment by sobkas** [comment]
I started to think that I have a broken video card, thanks for confirmation that you have the same problem.

**Comment by rboxeur** [comment]
I noticed that when you play without using D3D9 (wined3d native) and if you stay in front of the shacks the 3D object is a "black" object in 3D. I was able to go through the shacks using wined3d native. 


This black object is flickering and its colors change (depending on angle used).

Well I don't know. Perhaps something D3D9 can't handle

![capture du 2015-01-22 03 30 08](https://cloud.githubusercontent.com/assets/10597062/5849551/28f6b5de-a1e7-11e4-9164-4eed60784cbc.png)

**Comment by sobkas** [comment]
Does it crash with set R600_DEBUG=notiling ?

**Comment by rboxeur** [comment]
Yes it works with this setting :) 

I will reply on https://github.com/iXit/Mesa-3D/issues/63

**Comment by sobkas** [comment]
It should be fixed in ixit repo
