### ISSUE TITLE
Rendering problems and gpu lockups with undocumented Depth-Stencil and Render target multisample type combination

### ISSUE THREAD

**Issue by tizbac** [iXit/Mesa-3D#60]
Using different multisample type on DepthStencil Surface and Render target is forbidden as MSDN docs say ( http://msdn.microsoft.com/en-us/library/windows/desktop/bb174431%28v=vs.85%29.aspx )
But there are games (Splinter cell conviction for start ) that do that, and under windows it renders correctly, some tests on nouveau show the "wrong" behavior
Using this simple test program https://drive.google.com/file/d/0B5uKF4o3fPSWc2VySTR0NW9tVms/view?usp=sharing , dstest.exe , under nouveau you can either trigger a complete System&GPU lockup using DF16 and 4x multisample on depthstencil vs 1x on device/render target or,using DF24S8 instead, wrong render happens also with some errors on dmesg about render target overrun.
The nouveau driver seems to choose to use multisample or not by giving precedence to depth stencil, but in that case , as far i understood, it will try to write outside the other render targets that are NOT multisampled.
Same problem even if (apparently) it does not cause lockup, shows up using an HD5770 card and nine

https://drive.google.com/file/d/0B5uKF4o3fPSWc3d6OEVmeFhRWUU/view?usp=sharing This is the output of wined3d (left) vs nine ( right) , using DF24S8 and non-multisample device , with multisample depth stencil

**Comment by axeldavy** [comment]
Solved
