### ISSUE TITLE
WOLF RPG Editor (Game.exe): nine_pipe.h:476:d3dcmpfunc_to_pipe_func: Assertion `0' failed

### ISSUE THREAD

**Issue by kakurasan** [iXit/Mesa-3D#61]
When I try to run Game.exe in GPU rendering mode, the program aborts.
If native Direct3D 9 is disabled, this program runs (but font rendering is broken in version 2.10, see https://bugs.winehq.org/show_bug.cgi?id=35205).

Log: https://onedrive.live.com/redir?resid=3F9BE5B1CD4A806C!2417&authkey=!ALRpbjLwEFejO44&ithint=file%2ctxt
WOLF RPG Editor download page (Japanese): http://www.vector.co.jp/soft/dl/winnt/game/se475870.html

ppa:oibaf/graphics-drivers + ppa:commendsarnex/winedri3 + iXit/Mesa-3D f9c387b

**Comment by tizbac** [comment]
The game is explictly setting D3DRS_ALPHAFUNC to 0 , so the behavior in that case has to be tested on windows to see what function to use

**Comment by kakurasan** [comment]
Log (native Direct3D 9 is disabled): https://onedrive.live.com/redir?resid=3F9BE5B1CD4A806C!2419&authkey=!AEasdWehTKPLBuE&ithint=file%2cxz

Is this useful or not?

**Comment by tizbac** [comment]
Now with latest master it should start , but i get only black screen

**Comment by kakurasan** [comment]
Anyway it runs. Thanks. I opened a new issue about this.
