### ISSUE TITLE
Dark Souls 2 causes a gpu hang

### ISSUE THREAD

**Issue by sobkas** [iXit/Mesa-3D#63]
Dark Souls 2 causes a gpu hang
When you go into a No man wharf's shacks or going out of last bonefire in old iron crown dlc, gpu hangs:
Output from console:
https://gist.github.com/sobkas/b0c33798b5db74f0bfb3

**Comment by sobkas** [comment]
A new console log:
https://gist.github.com/sobkas/b439063d52d99d962d6e

**Comment by sobkas** [comment]
It works with R600_DEBUG=nosb,nohyperz,no2d,notiling,nodma,nocpdma,switch_on_eop
Will checkout with one fixes the problem

**Comment by sobkas** [comment]
Now I was able to pinpoint it on R600_DEBUG=notiling, with it I'm able to play game

**Comment by rboxeur** [comment]
Here I am currently on current Mesa-3D repo (iXit)  5ff32e24921c86b087085929e86720cc5b64be35
using Wine-Staging (www.wine-staging.com) patched with latest gallium nine patch

a) To start the game I have to revert 4f40acec32191f20e2c66ea86fbda94ebc31f9e0

git format-patch -1 4f40acec32191f20e2c66ea86fbda94ebc31f9e0
patch -p1 -R < 0001-st-nine-Add-check-to-vertexdeclaration9.patch

b) Setting R600_DEBUG=notiling helped as work around.

Compared to your other ticket I am currently on Kernel 3.18.1 (don't know if it can help!)

**Comment by sobkas** [comment]
Apitrace of Dark Souls 2:
http://goo.gl/vgz6Y4
I have used http://people.freedesktop.org/~jrfonseca/apitrace/apitrace-5.0.20140502-windows.7z
How to retrace: https://github.com/apitrace/apitrace/wiki/WINE

**Comment by axeldavy** [comment]
fixed, if I understand ?

**Comment by sobkas** [comment]
Yes it is, fixes landed in this tree
