### ISSUE TITLE
Tales of Monkey Island on RV530 gives "r300compiler error: Failed to translate rgb instruction"

### ISSUE THREAD

**Issue by FabioPedretti** [iXit/Mesa-3D#64]
This may be a r300 specific issue, filing here anyway.

When running Tales of Monkey Island game with quality >= 7/9 using iXit master branch I get the following error:
```
r300compiler error: Failed to translate rgb instruction.
r300 FP: Compiler Error:
Failed to translate rgb instruction.
Using a dummy shader instead.
r300: Initial fragment program
```

If useful here is the output when running with "RADEON_DEBUG=fp wine MonkeyIsland101.exe > ~/nine-tales-monkey-island.txt 2>&1":
https://bugs.freedesktop.org/attachment.cgi?id=112679

**Comment by axeldavy** [comment]
The shader seems fine, it is likely a r300 compiler error

**Comment by FabioPedretti** [comment]
Thanks I reported it here:
https://bugs.freedesktop.org/show_bug.cgi?id=88717

**Comment by axeldavy** [comment]
I close it, since not our bug
