### ISSUE TITLE
Artefacts and no dynamic shadows in World of Tanks

### ISSUE THREAD

**Issue by steemandlinux** [iXit/Mesa-3D#68]
http://i.imgur.com/1vhZAP9.png

tested on radeon 5470 and radeon r9 280x with llvm-3.6-rc1.

With mesa master git and old ixit-20150108 works fine. But with ixit mesa I have this issue.

http://www.mediafire.com/download/n5svq91px0fb3mx/wotixitmesa.log.xz

**Comment by axeldavy** [comment]
yes, sorry, we know which patch broke it, but not why and what is the correct fix. We are investigating

**Comment by steemandlinux** [comment]
stateblocks patch?

**Comment by axeldavy** [comment]
no, broken vertex

**Comment by steemandlinux** [comment]
23da5b4a493131b5b86d1d2685b62a2afc09aa2c fixed this bug

**Comment by tizbac** [comment]
Rendering is completely correct now?

**Comment by steemandlinux** [comment]
before vertex broken patch. But it has dark artefacts on mountains and has not dynamic shadows.

http://i.imgur.com/uzLRzHW.jpg

**Comment by axeldavy** [comment]
Can you guys check last ixit/master see if the bug is still there ? I hope it is fixed now.
