### ISSUE TITLE
League of Legends in-game shop crash the game

### ISSUE THREAD

**Issue by mandruis** [iXit/Mesa-3D#70]
For me League of Legends works perfectly the only problem is the in-game shop that crash the game my grafic is a HD7770 (RadeonSI) Ubuntu 14.10 PPAs: https://launchpad.net/~oibaf/+archiv e/ubuntu/graphics-drivers https://launchpad.net/~commendsar nex/+archive/ubuntu/winedri3 https://launchpad.net/~commendsar nex/+archive/ubuntu/mesadri3test https://launchpad.net/~commendsar nex/+archive/ubuntu/ixitmaster

**Comment by steemandlinux** [comment]
Without any logs?

**Comment by mandruis** [comment]
https://mega.co.nz/#!kEUHFTaa!7Xvw0E_6do41bbepZV4psML_U8gjDGn1r-BUyItNH9s
Now doesnt start

**Comment by sarnex** [comment]
This is not a problem with Gallium Nine, it has to do with textures in wine. You need to patch the LoL textures here.

https://github.com/A-Metaphysical-Drama/LoL-Linux-Tools

**Comment by mandruis** [comment]
I tried but when i use the firts one i get white screen ofter the game charge the second is a fix for wined3d and with the third one Rito can ban me.

**Comment by sarnex** [comment]
@mandruis yeah i get the same white screen. im looking into this issue now

**Comment by mandruis** [comment]
Sarnex,how is it going the patch for this bug?

**Comment by sarnex** [comment]
@mandruis I'm not sure I'm not a developer. The wine staging guys gave us a patch that has been submitted to normal wine d3d to fix this issue, and I think mannerov is going to try to fix it on Nine using that patch as a base. Ask mannerov in #d3d9 on irc.freenode.net for better info
