### ISSUE TITLE
Tomb Raider: Legend "Fullscreen effects" cause high GPU load

### ISSUE THREAD

**Issue by siro20** [iXit/Mesa-3D#72]
Tomb Raider: Legend
enabling "Fullscreen effects" cause high GPU load. Frames drop from 180fps to 0fps.
"Fullscreen effects" are HDR, motion blur, depth of field...

**Comment by siro20** [comment]
Update: "Depth of field" can be disabled once "Fullscreen effects" are enabled, but the GPU load is still to high, so it's another postprocessing effect. (HDR or motion blur)

**Comment by siro20** [comment]
"Fullscreen effects" cause the game to uses 2 pixelshader, while it doesn't use pixelshaders with "Fullscreen effects" disabled.
Here are both shaders:
 ps_1_1
    tex t0
    tex t2
    mov r0, t2
    mov r0.w, t0.w

 ps_1_1
    tex t0
    texreg2ar t1, t0
    texreg2gb t2, t0
    texreg2gb t3, t0
    add r1, t1, t2
    add r0, t3, r1

**Comment by siro20** [comment]
cannot reproduce with latest git, assume it has been fixed

**Comment by axeldavy** [comment]
Ok
