### ISSUE TITLE
Assassins Creed: Brotherhood (bad textures)

### ISSUE THREAD

**Issue by smirkybg** [iXit/Mesa-3D#75]
OS: Archlinux
Kernel version: 3.19.0
Wine version: 1.7.36 (with d3dadapter patchset)
Mesa version: 10.6.0 (using mesa-git from AUR)
xorg-server version: 1.16.3
GPU: ATI Mobility HD 4570

Here's what I get: https://www.youtube.com/watch?v=yFUp2qbY8qk

**Comment by axeldavy** [comment]
Is it better on current master ?

**Comment by smirkybg** [comment]
I can't seem to build it. I get this:
In file included from osmesa.c:44:0:
../../../../src/mesa/main/macros.h:34:25: fatal error: util/u_math.h: No such file or directory
 #include "util/u_math.h"
                         ^
I'll try later when some fixes are pushed to solved this.

**Comment by smirkybg** [comment]
With the latest mesa-git from AUR (compiled today) and this being the last commit before compiling:
http://cgit.freedesktop.org/mesa/mesa/commit/?id=49d3c6a8e63ead43fafb7d52e2c770a1320eb2ee

The result is the same. This is the only game so far which gives me such textures.

**Comment by axeldavy** [comment]
But it could be fixed on Ixit Master. Can you try it ?

**Comment by smirkybg** [comment]
I rebuilt mesa from this repo and I wasn't able to get pass through the second intro screen. This actually happened in previous versions of mesa while using the state tracker, but I was able to get around it by recreating ~/.wine and the game's saved content. This is what I get every single time now:
http://www.youtube.com/watch?v=78HU4TTD_5s

**Comment by Eignar17** [comment]
is not implemented multi-threaded and good fps O.O

**Comment by axeldavy** [comment]
we would need the gallium nine log, which you can get if you have debug info on (--enable-debug when compiling mesa) and with NINE_DEBUG=all

**Comment by smirkybg** [comment]
I made 2 logs which surprisingly turned out to be quite big, but I managed to compress them with bz2.

The first one is with "WINEDEBUG=all NINE_DEBUG=all".
Compressed 7.5 MB / Decompressed 162 MB (please be aware)
https://cloud.smirky.net/index.php/s/ybDGl4tgU2fMAuP

The second one is only with "NINE_DEBUG=all"
Compressed 269 KB / Decompressed 23 MB
https://cloud.smirky.net/index.php/s/Xw8bGZkG8IdGhh1

**Comment by axeldavy** [comment]
I do not see anything special in the log that could explain the bug.

If mesa master git is ok for you but not out mesa ixit git,
then one of our commit on top of mesa ixit git is the problem.

Can you do a git bisect to find out which commit is the problem ?

**Comment by smirkybg** [comment]
I'm not experienced in bisecting git commits. Anyway, I made a rollback to the latest stable mesa from Archlinux (10.4.5) and I can't get through the second intro screen again as in the youtube video. If I disable the state tracker through winecfg, I can get through it. BUT! When I start playing, my PC freezes. No tty switching, no process killing, nothing. I have to restart manually. I know this isn't a bug for this section but it actually might turn out to be one.

**Comment by axeldavy** [comment]
git bisect is not that hard to use, documentation on internet is pretty good.

On top of current ixit master, it should be:
git bisect start
git bisect bad
git bisect good 1180e61a1bb52d8fdf99185ca2c3042e7f686594

it will put you at some state between this commit and the last one, and you say if it's fine or not with git bisect good or git bisect bad. At the end it tells you which commit is the culprit.

**Comment by axeldavy** [comment]
It's been 3 years and I assume the issue has been fixed either by nine changes or driver changes. Please reopen if not.
