### ISSUE TITLE
Star Wars Battlefront 2: Water reflections broken

### ISSUE THREAD

**Issue by siro20** [iXit/Mesa-3D#78]
Water on setting "High" uses a pixelshader, which should reflect the environment, but it's broken on Nine.
![swbf2_broken_water](https://cloud.githubusercontent.com/assets/2340747/6168969/2b88bf38-b2ca-11e4-9b49-a7f66a872acf.png)

**Comment by axeldavy** [comment]
How do you launch the game ?
I have it on steam, but doesn't launch under nine

**Comment by siro20** [comment]
I'm owning the DVD version and I'm using a NoCD Fixed Exe.
There are some other issues using Nine, for example the game isn't able to switch to fullscreen, but displays a borderless window.

**Comment by siro20** [comment]
I've bought the Steam version and it is starting and running without problems, like the DVD version.

**Comment by siro20** [comment]
I see the same texture corruption on TrackMania Nations with settings set to "Low". But in this case the terrain, and not the water, is displayed incorrect.

**Comment by axeldavy** [comment]
do you have the corruption with the state_rework2 branch ?

**Comment by siro20** [comment]
tested TrackMania Nations with state_rework: no texture corruption
tested TrackMania Nations with state_rework2: crash sb/sb_sched.cpp:251:unreserve: Assertion `rp[cycle][chan] == sel && uc[cycle][chan]' failed.

**Comment by axeldavy** [comment]
can you bisect state_rework2 find the source of the crash ?

**Comment by siro20** [comment]
tested Star Wars Battlefront 2 with state_rework: no texture corruption
tested Star Wars Battlefront 2 with state_rework2: no texture corruption

**Comment by siro20** [comment]
tested TrackMania Nations with state_rework2: crash sb/sb_sched.cpp:251:unreserve: Assertion `rp[cycle][chan] == sel && uc[cycle][chan]' failed.
bisected:

928e21df930b78860196f341a62dd89d8d8b5e3a is the first bad commit
commit 928e21df930b78860196f341a62dd89d8d8b5e3a
Author: Axel Davy <axel.davy@ens.fr>
Date:   Sat May 16 12:14:54 2015 +0200
st/nine: Implement ff vertex data passthrough

**Comment by siro20** [comment]
Tested with Mesa 11.0.2. This issue is fixed.
