### ISSUE TITLE
Crash occurs when enabling Gallium nine (DRI_PRIME=1 radeon)

### ISSUE THREAD

**Issue by astroty** [iXit/Mesa-3D#81]
http://paste.opensuse.org/63118793

Ubuntu 15.04 with Intel/ATI cards
AMD 7730M

Using the following PPAs: ppa:commendsarnex/ixitmaster , ppa:commendsarnex/mesadri3test (only intel driver from vivid) , ppa:commendsarnex/winedri3 , ppa:oibaf/graphics-drivers  

Using this app: http://www.codesampler.com/dx9src/dx9src_1.htm#dx9_initialization

**Comment by sarnex** [comment]
Caused by https://bugs.freedesktop.org/show_bug.cgi?id=87452, not out bug. Found by mannerov
