### ISSUE TITLE
Shogun 2: Total War - Menu Elements are Whited Out

### ISSUE THREAD

**Issue by ToucheSir** [iXit/Mesa-3D#86]
Distro: Ubuntu 14.10
Some diagnostic info: 
>- uname -r: 3.19.0-031900-generic

>- glxinfo | grep OpenGL: 
OpenGL vendor string: X.Org
OpenGL renderer string: Gallium 0.4 on AMD TAHITI
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.6.0-devel (git-71b155a 2015-02-20 trusty-sarnex-ppa)
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 10.6.0-devel (git-71b155a 2015-02-20 trusty-sarnex-ppa)
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 10.6.0-devel (git-71b155a 2015-02-20 trusty-sarnex-ppa)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

>- lspci:
00:00.0 Host bridge: Intel Corporation 4th Gen Core Processor DRAM Controller (rev 06)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor PCI Express x16 Controller (rev 06)
00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)
00:03.0 Audio device: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller (rev 06)
00:14.0 USB controller: Intel Corporation 9 Series Chipset Family USB xHCI Controller
00:16.0 Communication controller: Intel Corporation 9 Series Chipset Family ME Interface #1
00:1a.0 USB controller: Intel Corporation 9 Series Chipset Family USB EHCI Controller #2
00:1b.0 Audio device: Intel Corporation 9 Series Chipset Family HD Audio Controller
00:1c.0 PCI bridge: Intel Corporation 9 Series Chipset Family PCI Express Root Port 1 (rev d0)
00:1c.2 PCI bridge: Intel Corporation 9 Series Chipset Family PCI Express Root Port 3 (rev d0)
00:1c.3 PCI bridge: Intel Corporation 9 Series Chipset Family PCI Express Root Port 4 (rev d0)
00:1d.0 USB controller: Intel Corporation 9 Series Chipset Family USB EHCI Controller #1
00:1f.0 ISA bridge: Intel Corporation 9 Series Chipset Family Z97 LPC Controller
00:1f.2 SATA controller: Intel Corporation 9 Series Chipset Family SATA Controller [AHCI Mode]
00:1f.3 SMBus: Intel Corporation 9 Series Chipset Family SMBus Controller
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Tahiti XT [Radeon HD 7970/8970 OEM / R9 280X]
01:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Tahiti XT HDMI Audio [Radeon HD 7970 Series]
03:00.0 Ethernet controller: Qualcomm Atheros Killer E220x Gigabit Ethernet Controller (rev 10)
04:00.0 PCI bridge: Intel Corporation 82801 PCI Bridge (rev 41)

Currently using these ppas:
https://launchpad.net/~commendsarnex/+archive/ubuntu/winedri3
https://launchpad.net/~commendsarnex/+archive/ubuntu/mesadri3test
https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers/
https://launchpad.net/~commendsarnex/+archive/ubuntu/ixitmaster

Installed Steam on a fresh prefix using PlayOnLinux. Enabled nine via winecfg and installed Shogun 2. Though some UI elements are rendered properly, most menus show up completely white. Units and other character models appear unaffected.

![shogun2gallium1](https://cloud.githubusercontent.com/assets/4062143/6315929/1ec5ec4a-b9c7-11e4-9ad2-3f91a7fcb367.png)
![shogun2gallium2](https://cloud.githubusercontent.com/assets/4062143/6315931/214bf0e0-b9c7-11e4-9f77-570e325cd051.png)
![shogun2gallium3](https://cloud.githubusercontent.com/assets/4062143/6315932/22bf74e2-b9c7-11e4-894b-78bad66bc3cc.png)

Here's the (non-truncated) log with WINEDEBUG=+d3d9,d3dadapter9. Note that this was taken from PlayOnLinux, so I'm not sure if there's any superfluous info in the log file.

https://gist.github.com/ToucheSir/94e9357cd59d17fd1442

**Comment by sarnex** [comment]
I downloaded the demo on Steam and I experience the same menu corruption.

**Comment by ToucheSir** [comment]
@sarnex Is there any other info I should provide?

**Comment by sarnex** [comment]
@ToucheSir Yeah if you are using my ixitmaster PPA, go into the Misc tab of the Shogun prefix in POL and under commands to exec before running the program put "export NINE_DEBUG=all". Then run the game until the menu. The log will be huge so you can close the game once it's at the menu.

**Comment by ToucheSir** [comment]
Should I clear WINEDEBUG? The resulting log file is ~700mb, and I'm having trouble uploading it...

**Comment by ToucheSir** [comment]
@sarnex Here's [the log]. I found a couple of interesting lines popping up throughout; not sure if they're at all relevant:

>Driver: nvd3dum.dll
Description: NVIDIA GeForce GTX 680
DeviceName: AMD TAHITI

Seems like my card is being identified as a GTX680, even though I have a r9 280X.

**Comment by sarnex** [comment]
@ToucheSir The 680 is a hardcoded value and doesn't cause any problems.

**Comment by ToucheSir** [comment]
Good to know. Hopefully the log is helpful.

**Comment by sarnex** [comment]
@ToucheSir I'm not setting a link to a log.

**Comment by ToucheSir** [comment]
Oh. My bad. Seems like I forgot to make the hyperlink an actual hyperlink.
Here 'tis: https://gist.github.com/ToucheSir/42e1aa168e102ee953bf

**Comment by sarnex** [comment]
@ToucheSir Log is too big, try tail -n 5k and upload that. Assuming you closed the program during some graphical corrupution.

**Comment by ToucheSir** [comment]
@sarnex [Here you go](https://gist.github.com/ToucheSir/76f6e6d92dca8bc9aa07). Not sure If I managed to isolate the issue, but should be close.

**Comment by ToucheSir** [comment]
@sarnex Made another attempt at creating a fresh test environment, but to no avail (issue still persists). Is there any additional information I should provide? Apologies for bringing this back from the dead.

**Comment by sarnex** [comment]
@ToucheSir try the state_rework2 branch

**Comment by ToucheSir** [comment]
Using `state_rework2` did not appear to solve the issue, unfortunately. However, this appears to be solved after the mesa 10.7 merge earlier yesterday, so I suppose it's worth closing.
