### ISSUE TITLE
PCSX2 doesn`t work

### ISSUE THREAD

**Issue by steemandlinux** [iXit/Mesa-3D#88]
http://www.mediafire.com/download/nkhcaa433vqn166/pcsx2.log

nine:device9:Clear: fast path
nine:device9:SetRenderTarget: This=0x7c25f9d8 RenderTargetIndex=0 pRenderTarget=0x7be4c560
nine:device9:SetRenderTarget: This=0x7c25f9d8 RenderTargetIndex=0 pRenderTarget=0x7be3a838
nine:device9:SetDepthStencilSurface: This=0x7c25f9d8 pNewZStencil=0x7be0b8d8
nine:device9:SetScissorRect: x=(0..0) y=(2048..2048)
nine:device9:SetTexture: This=0x7c25f9d8 Stage=0 pTexture=(nil)
nine:device9:SetRenderState: This=0x7c25f9d8 State=9(D3DRS_SHADEMODE) Value=00000001
nine:vertexbuffer9:Lock: This=0x7be13e78(pipe=0x7be13f18) OffsetToLock=0x1b000, SizeToLock=0x80, Flags=0x1000
nine:vertexbuffer9:Unlock: This=0x7be13e78
nine:indexbuffer9:Lock: This=0x7be0ba68 OffsetToLock=24 SizeToLock=24 ppbData=0x7f0e35c Flags=4096 transfer=(nil) map_count=0
nine:indexbuffer9:Lock: Returning memory at 0x7c70c018 at address 0x7f0e35c
nine:indexbuffer9:Unlock: This=0x7be0ba68
nine:device9:SetRenderState: This=0x7c25f9d8 State=7(D3DRS_ZENABLE) Value=00000001
nine:device9:SetRenderState: This=0x7c25f9d8 State=14(D3DRS_ZWRITEENABLE) Value=00000001
nine:device9:SetRenderState: This=0x7c25f9d8 State=23(D3DRS_ZFUNC) Value=00000008
nine:device9:SetRenderState: This=0x7c25f9d8 State=52(D3DRS_STENCILENABLE) Value=00000000
nine:device9:SetRenderState: This=0x7c25f9d8 State=27(D3DRS_ALPHABLENDENABLE) Value=00000000
nine:device9:SetRenderState: This=0x7c25f9d8 State=168(D3DRS_COLORWRITEENABLE) Value=0000000f
nine:device9:SetVertexShader: This=0x7c25f9d8 pShader=0x7c2d31f0
nine:device9:SetVertexShaderConstantF: This=0x7c25f9d8 StartRegister=0 pConstantData=0x7f0e540 Vector4fCount=4
nine:device9:SetVertexDeclaration: This=0x7c25f9d8 pDecl=0x7be00130
nine:device9:SetPixelShader: This=0x7c25f9d8 pShader=0x7be090f0
nine:device9:SetPixelShaderConstantF: This=0x7c25f9d8 StartRegister=0 pConstantData=0x7f0e480 Vector4fCount=8
nine:device9:DrawIndexedPrimitive: iface 0x7c25f9d8, PrimitiveType 4, BaseVertexIndex 3456, MinVertexIndex 0 NumVertices 6, StartIndex 6, PrimitiveCount 2
nine:nine_update_state: changed state groups: 167 | 101680
nine:update_framebuffer: 
nine:update_vertex_elements: looking up input 0 (usage 0) from vdecl(0x7be00130)
nine:update_vertex_elements: looking up input 1 (usage 7) from vdecl(0x7be00130)
nine:update_vertex_elements: looking up input 2 (usage 22) from vdecl(0x7be00130)
nine:nine_update_state: finished
nine:device9:CreateTexture: This=0x7c25f9d8 Width=512 Height=512 Levels=1 Usage= Format=D3DFMT_A8R8G8B8 Pool=MANAGED ppOut=0x7f0e4e0 pSharedHandle=(nil)
nine:texture9:ctor: (0x7be2f930) Width=512 Height=512 Levels=1 Usage= Format=D3DFMT_A8R8G8B8 Pool=MANAGED pSharedHandle=(nil)
nine:basetexture9:ctor: This=0x7be2f930, pParams=0x7f0e404 initResource=(nil) Type=3 format=21 Pool=1 Usage=0
nine:resource9:ctor: This=0x7be2f930 pParams=0x7f0e404 initResource=(nil) Allocate=0 Type=3 Pool=1 Usage=0
nine:surface9:ctor: This=0x7be3aa88 pDevice=0x7c25f9d8 pResource=(nil) Level=0 Layer=0 pDesc=0x7f0e388
nine:resource9:ctor: This=0x7be3aa88 pParams=0x7f0e2f4 initResource=(nil) Allocate=0 Type=1 Pool=1 Usage=0
nine:surface9:ctor: (0x7be2f930(This=0x7be3aa88),level=0) Allocating 0x100000 bytes of system memory.
nine:surface9:Dump: 
NineSurface9(0x7be3aa88->(nil)/0x7b1a7008): Pool=MANAGED Type=SURFACE Usage=
Dims=512x512 Format=D3DFMT_A8R8G8B8 Stride=2048 Lockable=0
Level=0(0), Layer=0
nine:unknown:QueryInterface: This=0x7be2f930 riid=0x7f0e228 ppvObject=0x7f0e224
nine:basetexture9:Dump: 
NineBaseTexture9(0x7be2f930->NULL/(nil)): Pool=MANAGED Type=TEXTURE Usage=
Format=D3DFMT_A8R8G8B8 Dims=512x512x1/1 LastLevel=0 Lod=0(4294967295)
nine:surface9:LockRect: This=0x7be3aa88 pLockedRect=0x7f0e4ec pRect=0x7f0e530[0..512,0..448] Flags=
nine:surface9:Dump: 
NineSurface9(0x7be3aa88->(nil)/0x7b1a7008): Pool=MANAGED Type=SURFACE Usage=
Dims=512x512 Format=D3DFMT_A8R8G8B8 Stride=2048 Lockable=0
Level=0(0), Layer=0
nine:unknown:QueryInterface: This=0x7be2f930 riid=0x7f0e3e8 ppvObject=0x7f0e3e4
nine:basetexture9:Dump: 
NineBaseTexture9(0x7be2f930->NULL/(nil)): Pool=MANAGED Type=TEXTURE Usage=
Format=D3DFMT_A8R8G8B8 Dims=512x512x1/1 LastLevel=0 Lod=0(4294967295)
nine:surface9:LockRect: returning system memory
nine:surface9:AddDirtyRect: This=0x7be3aa88 box=0x7f0e4a0
wine: Unhandled page fault on read access to 0xffffffff at address 0x8061cad (thread 002b), starting debugger...

**Comment by axeldavy** [comment]
which mesa version .?

**Comment by steemandlinux** [comment]
Oh sorry. mesa-git from freedesktop, llvm-3.7-git, xorg-server 1.17, modesetting, wine 1.7.36.

**Comment by axeldavy** [comment]
Ok, probably solved on mesa ixit master then

**Comment by pontostroy** [comment]
current-git cdb04771a8d68c26dbc205b52c497fc96e0e1d06
nine:unknown:QueryInterface: This=0x7ac73048 riid=0x737e1f0 ppvObject=0x737e200
nine:basetexture9:Dump: 
NineBaseTexture9(0x7ac73048->NULL/(nil)): Pool=MANAGED Type=TEXTURE Usage=
Format=D3DFMT_A8R8G8B8 Dims=64x64x1/1 LastLevel=0 Lod=0(4294967295)
nine:surface9:LockRect: This=0x7ac993d8 pLockedRect=0x737e49c pRect=0x737e4f0[0..64,0..64] Flags=
nine:surface9:Dump: 
NineSurface9(0x7ac993d8->(nil)/0x7ac85290): Pool=MANAGED Type=SURFACE Usage=
Dims=64x64 Format=D3DFMT_A8R8G8B8 Stride=256 Lockable=0
Level=0(0), Layer=0
nine:unknown:QueryInterface: This=0x7ac73048 riid=0x737e3a8 ppvObject=0x737e3b8
nine:basetexture9:Dump: 
NineBaseTexture9(0x7ac73048->NULL/(nil)): Pool=MANAGED Type=TEXTURE Usage=
Format=D3DFMT_A8R8G8B8 Dims=64x64x1/1 LastLevel=0 Lod=0(4294967295)
nine:surface9:LockRect: returning system memory
nine:surface9:AddDirtyRect: This=0x7ac993d8 box=0x737e454
nine:texture9:AddDirtyRect: This=0x7ac73048 pDirtyRect=0x737e444[(0,0)-(64,64)]
nine:surface9:UnlockRect: This=0x7ac993d8 lock_count=1
nine:device9:SetRenderTarget: This=0x7c675c10 RenderTargetIndex=0 pRenderTarget=0x7ac24120
nine:device9:SetTexture: This=0x7c675c10 Stage=0 pTexture=0x7ac73048
nine:device9:SetRenderState: This=0x7c675c10 State=9(D3DRS_SHADEMODE) Value=00000002
nine:vertexbuffer9:Lock: This=0x7ac25860(pipe=0x7ac258f0) OffsetToLock=0x1300, SizeToLock=0x3d40, Flags=0x1000
nine:vertexbuffer9:Unlock: This=0x7ac25860
nine:indexbuffer9:Lock: This=0x7ac25a58 OffsetToLock=312 SizeToLock=2928 ppbData=0x737e31c Flags=4096 transfer=(nil) map_count=0
nine:indexbuffer9:Lock: Returning memory at 0x7ce00138 at address 0x737e31c
nine:indexbuffer9:Unlock: This=0x7ac25a58
nine:device9:SetRenderState: This=0x7c675c10 State=7(D3DRS_ZENABLE) Value=00000001
nine:device9:SetRenderState: This=0x7c675c10 State=14(D3DRS_ZWRITEENABLE) Value=00000000
nine:device9:SetRenderState: This=0x7c675c10 State=23(D3DRS_ZFUNC) Value=00000007
nine:device9:SetRenderState: This=0x7c675c10 State=52(D3DRS_STENCILENABLE) Value=00000001
nine:device9:SetRenderState: This=0x7c675c10 State=58(D3DRS_STENCILMASK) Value=00000001
nine:device9:SetRenderState: This=0x7c675c10 State=59(D3DRS_STENCILWRITEMASK) Value=00000002
nine:device9:SetRenderState: This=0x7c675c10 State=56(D3DRS_STENCILFUNC) Value=00000008
nine:device9:SetRenderState: This=0x7c675c10 State=55(D3DRS_STENCILPASS) Value=00000003
nine:device9:SetRenderState: This=0x7c675c10 State=53(D3DRS_STENCILFAIL) Value=00000002
nine:device9:SetRenderState: This=0x7c675c10 State=54(D3DRS_STENCILZFAIL) Value=00000001
nine:device9:SetRenderState: This=0x7c675c10 State=57(D3DRS_STENCILREF) Value=00000003
nine:device9:SetRenderState: This=0x7c675c10 State=27(D3DRS_ALPHABLENDENABLE) Value=00000001
nine:device9:SetRenderState: This=0x7c675c10 State=171(D3DRS_BLENDOP) Value=00000001
nine:device9:SetRenderState: This=0x7c675c10 State=19(D3DRS_SRCBLEND) Value=0000000e
nine:device9:SetRenderState: This=0x7c675c10 State=20(D3DRS_DESTBLEND) Value=00000002
nine:device9:SetRenderState: This=0x7c675c10 State=206(D3DRS_SEPARATEALPHABLENDENABLE) Value=00000001
nine:device9:SetRenderState: This=0x7c675c10 State=209(D3DRS_BLENDOPALPHA) Value=00000001
nine:device9:SetRenderState: This=0x7c675c10 State=207(D3DRS_SRCBLENDALPHA) Value=00000002
nine:device9:SetRenderState: This=0x7c675c10 State=208(D3DRS_DESTBLENDALPHA) Value=00000001
nine:device9:SetRenderState: This=0x7c675c10 State=193(D3DRS_BLENDFACTOR) Value=00282828
nine:device9:SetRenderState: This=0x7c675c10 State=168(D3DRS_COLORWRITEENABLE) Value=0000000f
nine:device9:CreateVertexShader: This=0x7c675c10 pFunction=0x2411478 ppShader=0x737e2c8
nine:vertexshader9:ctor: This=0x7ac4b650 pParams=0x737e1e8 pFunction=0x2411478 cso=(nil)
VS3.0
DEF c2 { -0.050000 -0.000000 0.000000 0.000000 }
DCL v0 POSITION0
DCL v1 TEXCOORD0
DCL v2 COLOR0
DCL v3 COLOR1
DCL o0 POSITION0
DCL o1 TEXCOORD0
DCL o2 COLOR0
ADD r0 c2.xxyy v0 
MOV r1 c0 
MAD o0 r0 r1 -(c1) 
MOV o1.xy__ v1 
MOV o1.__z_ v3.zzzz 
MOV o1.___w v0.wwww 
MOV o2 v2 
VERT
DCL IN[0]
DCL IN[1]
DCL IN[2]
DCL IN[3]
DCL OUT[0], POSITION
DCL OUT[1], GENERIC[0]
DCL OUT[2], COLOR
DCL CONST[0..1]
DCL TEMP[0..1]
IMM[0] FLT32 {   -0.0500,    -0.0000,     0.0000,     0.0000}
  0: ADD TEMP[0], IMM[0].xxyy, IN[0]
  1: MOV TEMP[1], CONST[0]
  2: MAD OUT[0], TEMP[0], TEMP[1], -CONST[1]
  3: MOV OUT[1].xy, IN[1]
  4: MOV OUT[1].z, IN[3].zzzz
  5: MOV OUT[1].w, IN[0].wwww
  6: MOV OUT[2], IN[2]
  7: END
nine:device9:CreateVertexDeclaration: This=0x7c675c10 pVertexElements=0x4dd9984 ppDecl=0x737e2cc
nine:vertexdeclaration9:ctor: This=0x7ac90d28 pParams=0x737e1e8 pElements=0x4dd9984
nine:vertexdeclaration9:ctor: VERTEXELEMENT[0]: Stream=0 Offset=0 Type=PIPE_FORMAT_R32G32_FLOAT DeclUsage=TEXCOORD0
nine:vertexdeclaration9:ctor: VERTEXELEMENT[1]: Stream=0 Offset=8 Type=PIPE_FORMAT_B8G8R8A8_UNORM DeclUsage=DIFFUSE0
nine:vertexdeclaration9:ctor: VERTEXELEMENT[2]: Stream=0 Offset=12 Type=PIPE_FORMAT_B8G8R8A8_UNORM DeclUsage=DIFFUSE1
nine:vertexdeclaration9:ctor: VERTEXELEMENT[3]: Stream=0 Offset=16 Type=PIPE_FORMAT_R32G32B32A32_FLOAT DeclUsage=POSITION0
nine:device9:SetVertexShader: This=0x7c675c10 pShader=0x7ac4b650
nine:device9:SetVertexShaderConstantF: This=0x7c675c10 StartRegister=0 pConstantData=0x737e500 Vector4fCount=4
nine:device9:SetVertexDeclaration: This=0x7c675c10 pDecl=0x7ac90d28
nine:device9:CreatePixelShader: This=0x7c675c10 pFunction=0x24114d8 ppShader=0x737e158
nine:pixelshader9:ctor: This=0x7ac8fd80 pParams=0x737e060 pFunction=0x24114d8 cso=(nil)
PS3.0
DEF c5 { -0.500000 0.000000 1.992188 0.000000 }
DEF c6 { 1.000000 2.000000 0.000000 0.000000 }
DCL v0.xy_w TEXCOORD0
DCL v1 COLOR0
DCL s0 2D
RCP r0.x___ v0.wwww 
MAD r0 v0.xyxy r0.xxxx c1 
TEX r1 r0 s0 
DP3 r2.x___ r1 r1 
MOV r2._y__ c5.yyyy 
CMP r2.x___ -(r2).xxxx r2.yyyy c4.zzzz 
ADD r2.__z_ r1.wwww c5.xxxx 
CMP r1.___w r2.zzzz c4.wwww r2.xxxx 
TEX r3 r0.zyzw s0 
DP3 r2.x___ r3 r3 
CMP r2.x___ -(r2).xxxx r2.yyyy c4.zzzz 
ADD r2.__z_ r3.wwww c5.xxxx 
CMP r3.___w r2.zzzz c4.wwww r2.xxxx 
MUL r2.x_z_ r0.xyyw c2.zyww 
FRC r2.x_z_ r2 
LRP r4 r2.xxxx r3 r1 
TEX r1 r0.xwzw s0 
TEX r0 r0.zwzw s0 
DP3 r2.___w r1 r1 
CMP r2.___w -(r2).wwww r2.yyyy c4.zzzz 
ADD r3.x___ r1.wwww c5.xxxx 
CMP r1.___w r3.xxxx c4.wwww r2.wwww 
DP3 r2.___w r0 r0 
CMP r2._y__ -(r2).wwww r2.yyyy c4.zzzz 
ADD r2.___w r0.wwww c5.xxxx 
CMP r0.___w r2.wwww c4.wwww r2.yyyy 
LRP r3 r2.xxxx r0 r1 
LRP r0 r2.zzzz r3 r4 
MUL r0 r0 v1 
MUL sat r0 r0 c5.zzzz 
MUL oC0 r0 c6.xxxy 
FRAG
PROPERTY FS_COORD_ORIGIN UPPER_LEFT
PROPERTY FS_COORD_PIXEL_CENTER INTEGER
DCL IN[0], GENERIC[0], PERSPECTIVE
DCL IN[1], COLOR, PERSPECTIVE
DCL OUT[0], COLOR
DCL SAMP[0]
DCL CONST[0..4]
DCL TEMP[0..4]
IMM[0] FLT32 {   -0.5000,     0.0000,     1.9922,     1.0000}
IMM[1] FLT32 {    1.0000,     2.0000,     0.0000,     0.0000}
  0: RCP TEMP[0].x, IN[0].wwww
  1: MAD TEMP[0], IN[0].xyxy, TEMP[0].xxxx, CONST[1]
  2: TEX TEMP[1], TEMP[0], SAMP[0], 2D
  3: DP3 TEMP[2].x, TEMP[1], TEMP[1]
  4: MOV TEMP[2].y, IMM[0].yyyy
  5: CMP TEMP[2].x, -TEMP[2].xxxx, CONST[4].zzzz, TEMP[2].yyyy
  6: ADD TEMP[2].z, TEMP[1].wwww, IMM[0].xxxx
  7: CMP TEMP[1].w, TEMP[2].zzzz, TEMP[2].xxxx, CONST[4].wwww
  8: TEX TEMP[3], TEMP[0].zyzw, SAMP[0], 2D
  9: DP3 TEMP[2].x, TEMP[3], TEMP[3]
 10: CMP TEMP[2].x, -TEMP[2].xxxx, CONST[4].zzzz, TEMP[2].yyyy
 11: ADD TEMP[2].z, TEMP[3].wwww, IMM[0].xxxx
 12: CMP TEMP[3].w, TEMP[2].zzzz, TEMP[2].xxxx, CONST[4].wwww
 13: MUL TEMP[2].xz, TEMP[0].xyyw, CONST[2].zyww
 14: FRC TEMP[2].xz, TEMP[2]
 15: LRP TEMP[4], TEMP[2].xxxx, TEMP[3], TEMP[1]
 16: TEX TEMP[1], TEMP[0].xwzw, SAMP[0], 2D
 17: TEX TEMP[0], TEMP[0].zwzw, SAMP[0], 2D
 18: DP3 TEMP[2].w, TEMP[1], TEMP[1]
 19: CMP TEMP[2].w, -TEMP[2].wwww, CONST[4].zzzz, TEMP[2].yyyy
 20: ADD TEMP[3].x, TEMP[1].wwww, IMM[0].xxxx
 21: CMP TEMP[1].w, TEMP[3].xxxx, TEMP[2].wwww, CONST[4].wwww
 22: DP3 TEMP[2].w, TEMP[0], TEMP[0]
 23: CMP TEMP[2].y, -TEMP[2].wwww, CONST[4].zzzz, TEMP[2].yyyy
 24: ADD TEMP[2].w, TEMP[0].wwww, IMM[0].xxxx
 25: CMP TEMP[0].w, TEMP[2].wwww, TEMP[2].yyyy, CONST[4].wwww
 26: LRP TEMP[3], TEMP[2].xxxx, TEMP[0], TEMP[1]
 27: LRP TEMP[0], TEMP[2].zzzz, TEMP[3], TEMP[4]
 28: MUL TEMP[0], TEMP[0], IN[1]
 29: MUL_SAT TEMP[0], TEMP[0], IMM[0].zzzz
 30: MUL OUT[0], TEMP[0], IMM[1].xxxy
 31: END
nine:device9:SetPixelShader: This=0x7c675c10 pShader=0x7ac8fd80
nine:device9:SetPixelShaderConstantF: This=0x7c675c10 StartRegister=0 pConstantData=0x737e480 Vector4fCount=8
nine:device9:SetSamplerState: This=0x7c675c10 Sampler=0 Type=ADDRESSU Value=00000001
nine:device9:SetSamplerState: This=0x7c675c10 Sampler=0 Type=ADDRESSV Value=00000001
nine:device9:SetSamplerState: This=0x7c675c10 Sampler=1 Type=ADDRESSU Value=00000003
nine:device9:SetSamplerState: This=0x7c675c10 Sampler=1 Type=ADDRESSV Value=00000003
nine:device9:SetSamplerState: This=0x7c675c10 Sampler=2 Type=ADDRESSU Value=00000003
nine:device9:SetSamplerState: This=0x7c675c10 Sampler=2 Type=ADDRESSV Value=00000003
nine:device9:SetSamplerState: This=0x7c675c10 Sampler=3 Type=ADDRESSU Value=00000001
nine:device9:SetSamplerState: This=0x7c675c10 Sampler=3 Type=ADDRESSV Value=00000001
nine:device9:SetSamplerState: This=0x7c675c10 Sampler=4 Type=ADDRESSU Value=00000001
nine:device9:SetSamplerState: This=0x7c675c10 Sampler=4 Type=ADDRESSV Value=00000001
nine:device9:SetSamplerState: This=0x7c675c10 Sampler=0 Type=MINFILTER Value=00000001
nine:device9:SetSamplerState: This=0x7c675c10 Sampler=0 Type=MAGFILTER Value=00000001
nine:device9:SetSamplerState: This=0x7c675c10 Sampler=1 Type=MINFILTER Value=00000001
nine:device9:SetSamplerState: This=0x7c675c10 Sampler=1 Type=MAGFILTER Value=00000001
nine:device9:SetSamplerState: This=0x7c675c10 Sampler=2 Type=MINFILTER Value=00000001
nine:device9:SetSamplerState: This=0x7c675c10 Sampler=2 Type=MAGFILTER Value=00000001
nine:device9:SetSamplerState: This=0x7c675c10 Sampler=3 Type=MINFILTER Value=00000001
nine:device9:SetSamplerState: This=0x7c675c10 Sampler=3 Type=MAGFILTER Value=00000001
nine:device9:SetSamplerState: This=0x7c675c10 Sampler=4 Type=MINFILTER Value=00000001
nine:device9:SetSamplerState: This=0x7c675c10 Sampler=4 Type=MAGFILTER Value=00000001
nine:device9:DrawIndexedPrimitive: iface 0x7c675c10, PrimitiveType 4, BaseVertexIndex 152, MinVertexIndex 0 NumVertices 732, StartIndex 78, PrimitiveCount 244
nine:nine_update_state: changed state groups: 3017f | 101e80
nine:basetexture9:Validate: This=0x7ac73048 dirty=1 dirty_mip=0 lod=0/4294967295
nine:basetexture9:UploadSelf: This=0x7ac73048 dirty=1 type=TEXTURE
nine:basetexture9:UploadSelf: updating LOD from 4294967295 to 0 ...
nine:basetexture9:CreatePipeResource: This=0x7ac73048 lod=0 last_level=0
nine:surface9:UploadSelf: This=0x7ac993d8 damaged=0x737e20c
nine:basetexture9:UploadSelf: DONE, generate mip maps = 0
nine:update_framebuffer: 
nine:basetexture9:UpdateSamplerView: This=0x7ac73048 sRGB=0
nine:basetexture9:UpdateSamplerView: sampler view = 0x7ac28fe0(resource = 0x7ac83e98)
nine:update_vertex_elements: looking up input 0 (usage 0) from vdecl(0x7ac90d28)
nine:update_vertex_elements: looking up input 1 (usage 4) from vdecl(0x7ac90d28)
nine:update_vertex_elements: looking up input 2 (usage 7) from vdecl(0x7ac90d28)
nine:update_vertex_elements: looking up input 3 (usage 22) from vdecl(0x7ac90d28)
nine:nine_update_state: finished
nine:device9:SetRenderState: This=0x7c675c10 State=7(D3DRS_ZENABLE) Value=00000000
nine:device9:SetRenderState: This=0x7c675c10 State=14(D3DRS_ZWRITEENABLE) Value=00000000
nine:device9:SetRenderState: This=0x7c675c10 State=52(D3DRS_STENCILENABLE) Value=00000001
nine:device9:SetRenderState: This=0x7c675c10 State=58(D3DRS_STENCILMASK) Value=00000002
nine:device9:SetRenderState: This=0x7c675c10 State=59(D3DRS_STENCILWRITEMASK) Value=00000002
nine:device9:SetRenderState: This=0x7c675c10 State=56(D3DRS_STENCILFUNC) Value=00000003
nine:device9:SetRenderState: This=0x7c675c10 State=55(D3DRS_STENCILPASS) Value=00000002
nine:device9:SetRenderState: This=0x7c675c10 State=53(D3DRS_STENCILFAIL) Value=00000002
nine:device9:SetRenderState: This=0x7c675c10 State=54(D3DRS_STENCILZFAIL) Value=00000002
nine:device9:SetRenderState: This=0x7c675c10 State=57(D3DRS_STENCILREF) Value=00000002
nine:device9:SetRenderState: This=0x7c675c10 State=27(D3DRS_ALPHABLENDENABLE) Value=00000000
nine:device9:SetRenderState: This=0x7c675c10 State=168(D3DRS_COLORWRITEENABLE) Value=00000008
nine:vertexbuffer9:Lock: This=0x7ac25860(pipe=0x7ac258f0) OffsetToLock=0x5040, SizeToLock=0x80, Flags=0x1000
nine:vertexbuffer9:Unlock: This=0x7ac25860
nine:device9:SetVertexDeclaration: This=0x7c675c10 pDecl=0x7ac14df0
nine:device9:SetVertexShader: This=0x7c675c10 pShader=0x7ac21138
nine:device9:SetPixelShader: This=0x7c675c10 pShader=0x7ac1c860
nine:device9:DrawPrimitive: iface 0x7c675c10, PrimitiveType 5, StartVertex 642, PrimitiveCount 2
nine:nine_update_state: changed state groups: 20170 | 101000
nine:update_vertex_elements: looking up input 0 (usage 0) from vdecl(0x7ac14df0)
nine:update_vertex_elements: looking up input 1 (usage 4) from vdecl(0x7ac14df0)
nine:nine_update_state: finished
nine:device9:CreateTexture: This=0x7c675c10 Width=64 Height=64 Levels=1 Usage= Format=D3DFMT_A8R8G8B8 Pool=MANAGED ppOut=0x737e478 pSharedHandle=(nil)
nine:texture9:ctor: (0x7ac83d78) Width=64 Height=64 Levels=1 Usage= Format=D3DFMT_A8R8G8B8 Pool=MANAGED pSharedHandle=(nil)
nine:basetexture9:ctor: This=0x7ac83d78, pParams=0x737e3b0 initResource=(nil) Type=3 format=21 Pool=1 Usage=0
nine:resource9:ctor: This=0x7ac83d78 pParams=0x737e3b0 initResource=(nil) Allocate=0 Type=3 Pool=1 Usage=0
nine:surface9:ctor: This=0x7ac3fe80 pDevice=0x7c675c10 pResource=(nil) Level=0 Layer=0 pDesc=0x737e344
nine:resource9:ctor: This=0x7ac3fe80 pParams=0x737e2c0 initResource=(nil) Allocate=0 Type=1 Pool=1 Usage=0
nine:surface9:Dump: 
NineSurface9(0x7ac3fe80->(nil)/0x7ac5b9b8): Pool=MANAGED Type=SURFACE Usage=
Dims=64x64 Format=D3DFMT_A8R8G8B8 Stride=256 Lockable=0
Level=0(0), Layer=0
nine:unknown:QueryInterface: This=0x7ac83d78 riid=0x737e1f0 ppvObject=0x737e200
nine:basetexture9:Dump: 
NineBaseTexture9(0x7ac83d78->NULL/(nil)): Pool=MANAGED Type=TEXTURE Usage=
Format=D3DFMT_A8R8G8B8 Dims=64x64x1/1 LastLevel=0 Lod=0(4294967295)
nine:surface9:LockRect: This=0x7ac3fe80 pLockedRect=0x737e49c pRect=0x737e4f0[0..64,0..64] Flags=
nine:surface9:Dump: 
NineSurface9(0x7ac3fe80->(nil)/0x7ac5b9b8): Pool=MANAGED Type=SURFACE Usage=
Dims=64x64 Format=D3DFMT_A8R8G8B8 Stride=256 Lockable=0
Level=0(0), Layer=0
nine:unknown:QueryInterface: This=0x7ac83d78 riid=0x737e3a8 ppvObject=0x737e3b8
nine:basetexture9:Dump: 
NineBaseTexture9(0x7ac83d78->NULL/(nil)): Pool=MANAGED Type=TEXTURE Usage=
Format=D3DFMT_A8R8G8B8 Dims=64x64x1/1 LastLevel=0 Lod=0(4294967295)
nine:surface9:LockRect: returning system memory
nine:surface9:AddDirtyRect: This=0x7ac3fe80 box=0x737e454
nine:texture9:AddDirtyRect: This=0x7ac83d78 pDirtyRect=0x737e444[(0,0)-(64,64)]
Unhandled exception: page fault on read access to 0xffffffff in 32-bit code (0x04d78d57).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:04d78d57 ESP:0737e310 EBP:0737e494 EFLAGS:00210206(  R- --  I   - -P- )
 EAX:00000008 EBX:0656d100 ECX:0737e380 EDX:7ac5b9d8
 ESI:00000100 EDI:7ac5b9b8
Stack dump:
0x0737e310:  00000000 04d71877 00000100 0737e4d0
0x0737e320:  00000000 0d8f48c0 00000008 7ac5b9b8
0x0737e330:  00000000 7a679bb9 7a7af000 7ac83d78
0x0737e340:  0737e444 00000040 7a32715b 00000800
0x0737e350:  0d89f720 7a67adc8 7ac83d78 0737e444
0x0737e360:  00000000 00000000 00003320 0656da40
000c: sel=0067 base=00000000 limit=00000000 16-bit --x
Backtrace:
=>0 0x04d78d57 in gsdx32-sse2-r5875 (+0x48d57) (0x0737e494)
  1 0x04daa70f in gsdx32-sse2-r5875 (+0x7a70e) (0x0737e524)
  2 0x04daa45c in gsdx32-sse2-r5875 (+0x7a45b) (0x0737e584)
  3 0x04da8bf6 in gsdx32-sse2-r5875 (+0x78bf5) (0x0737e5dc)
  4 0x04d8777b in gsdx32-sse2-r5875 (+0x5777a) (0x0737e6f8)
  5 0x04d9664f in gsdx32-sse2-r5875 (+0x6664e) (0x0737e768)
  6 0x04da6948 in gsdx32-sse2-r5875 (+0x76947) (0x0737e7b4)
  7 0x04d9c709 in gsdx32-sse2-r5875 (+0x6c708) (0x0737e7fc)
  8 0x04da66d2 in gsdx32-sse2-r5875 (+0x766d1) (0x0737e83c)
  9 0x04d456a1 in gsdx32-sse2-r5875 (+0x156a0) (0x0737e868)
0x04d78d57: movq        %mm1,0xffffffe0(%edx)
Wine-dbg>

**Comment by steemandlinux** [comment]
Also doesn`t work with ixit repo.

**Comment by axeldavy** [comment]
can you try with ixit master,
but changing src/gallium/state_tracker/nine_pipe.h:

static INLINE unsigned nine_format_get_stride(enum pipe_format format,
                                              unsigned width)
{
    unsigned stride = util_format_get_stride(format, width);

    return align(stride, 4);
}

by

static INLINE unsigned nine_format_get_stride(enum pipe_format format,
                                              unsigned width)
{
    unsigned stride = util_format_get_stride(format, width);

    return align(stride, 8);
}

**Comment by axeldavy** [comment]
Try with 16 and 32 instead of 4 too

**Comment by steemandlinux** [comment]
All works with return align(stride, 8);

**Comment by steemandlinux** [comment]
stride, 8 / stride, 16 / stride, 32 also causes 

wine: Unhandled page fault on read access to 0xffffffff at address 0x4f5f580 (thread 002a), starting debugger...

**Comment by axeldavy** [comment]
Initially you said it was working, then edited your message and said it doesn't work. Did something work better, or the same exactly ?

**Comment by siro20** [comment]
while testing I run into another issue using the debug build:
tested with wine1.7.40 and pcsx2 1.2.1
[...]
nine:device9:SetSamplerState: This=0x7bd5bab0 Sampler=0 Type=ADDRESSW Value=00000000
[...]
nine_pipe.h:628:d3dtextureaddress_to_pipe_tex_wrap: Assertion `0' failed.

removing the assert leads to the same error reported above. However I need a pcsx2 build with debugging symbols...

**Comment by axeldavy** [comment]
there may be several problems then

**Comment by siro20** [comment]
I've found the issue: NineTexture9_ctor allocates system memory that is beeing returned to userspace applications once they lock the texture. As pcsx2 uses SSE and AVX, we have to make sure it is aligned!  I've replaced MALLOC( ... ) with aligned_alloc(16, ... ) and now it works as expected. The default alignment of 8 byte is not sufficient !
