### ISSUE TITLE
LoL low performance and crashes

### ISSUE THREAD

**Issue by mandruis** [iXit/Mesa-3D#89]
League(2).log 394 KB
https://mega.co.nz/#!MNEylbQJ!0eMGkbHrAGy7Dwy6JMTRzQDegxQpqj1ym-87FC2yf10

**Comment by axeldavy** [comment]
nothing interesting in the log, sorry

**Comment by mandruis** [comment]
LoL 209.6 MB
https://mega.co.nz/#!YQ1FkLLQ!yE1Sv8oyAXfIQonhgvVuy3UYHVcQ073fCXIYZ5wIZNY

**Comment by mandruis** [comment]
Finally works properly
