### ISSUE TITLE
Batman: Arkham City - Red Shadows

### ISSUE THREAD

**Issue by func-boncey** [iXit/Mesa-3D#93]
Hi guys! Thanks for your amazing work, you truly are inspirational people and are doing God's work here. I have been playing Batman: Arkham City recently and I have noticed lots of improvements to the game's performance and fixes for the games issue's recently.

One issue that has always plagued the game for me has been the red shadows, this does not happen upon Windows. The bug only happens in certain areas of the game.

I am on an AMD Radeon HD 7970 card.

Here is my log for Gallium and WINE:
http://pastebin.com/raw.php?i=jPMhev3H

I used the debug commands someone gave me on the IRC, though it doesn't seem to produce as much without them, I am happy to re-log these.

Here is a screenshot of the issue:
http://i.imgur.com/DyK5yNb.jpg

Thanks, and keep up the great work. :smile:

**Comment by rboxeur** [comment]
That seems to be one of the well-known bugs with for Gallium Nine
https://wiki.ixit.cz/d3d9_bugs 

HD 7000 serie: red shadow
HD 6000 serie: green shadow

Not only for games based on Unreal Engine. I don't own this game but try to see if you can switch off ("post-processing" or "occult ambiant" or something like this) in Graphical Options for this game.

**Comment by func-boncey** [comment]
I have turned off Ambient Occlusion and everything else, put it on lowest possible settings but there are still red shadows. I guess I will wait until this is fixed. Thanks anyway. :smile:

**Comment by CalcProgrammer1** [comment]
I'm getting red shadows on HD5000 as well.  Going to test it on my 290X and see what that gives.

**Comment by axeldavy** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=89012

**Comment by axeldavy** [comment]
Solved
