### ISSUE TITLE
PPA Query & DRI3 Issue.

### ISSUE THREAD

**Issue by Abhishek-Rawal** [iXit/Mesa-3D#96]
1) I am using Oibaf PPA, sarnex winedri3, sarnex mesadri3test and ixitmaster. My question is can I use Ixit master PPA and Oibaf PPA together ? Or is it better to remove Oibaf if I am using Ixitmaster ?

2) Output of "LIBGL_DEBUG=verbose glxgears" -->
libGL: screen 0 does not appear to be DRI3 capable
libGL: pci id for fd 4: 1002:9851, driver radeonsi
libGL: OpenDriver: trying /usr/lib/x86_64-linux-gnu/dri/tls/radeonsi_dri.so
libGL: OpenDriver: trying /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so

Wine pops -->
err:x11drv:DRI3CheckExtension DRI3 advertised, but not working
err:d3dadapter:has_d3dadapter Unable to query DRI3. Trying DRI2 fallback (slower performance).

Games are working fine, no issues. Infact, games are working better than wine without patched d3d9.
But what irks me is this error. I am unable to use DRI3 and all games are falling back to DRI2.

My Hardware configuration -->
AMD APU A8-6410 with Radeon R5
Ubuntu 14.04 LTS

**Comment by axeldavy** [comment]
The DRI2 fallback just gives you slightly worse performance.

You'd better not care and use DRI2
