### ISSUE TITLE
Wine 1.7.39 can not be built for "d3dadapter9: Fix cursor handling " 

### ISSUE THREAD

**Issue by rboxeur** [iXit/Mesa-3D#97]
I tried the commit "d3dadapter9: Fix cursor handling " pushed on https://github.com/iXit/wine Saturday 03/21/2015.

Unfortunately it failed with 

gcc -c -o driver.o driver.c -I. -I../../include -D__WINESRC__ -D_REENTRANT -fPIC -Wall -pipe \
  -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body -Wignored-qualifiers \
  -Wstrict-prototypes -Wtype-limits -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith \
  -Wlogical-op -gdwarf-2 -gstrict-dwarf -fno-omit-frame-pointer -Og -ggdb -g -gdwarf-2 -gstrict-dwarf -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0
d3dadapter.c: In function â€˜DRI3Present_GetCursorPosâ€™:
d3dadapter.c:445:19: error: â€˜paramsâ€™ undeclared (first use in this function)
     draw_window = params->hDeviceWindow ?
                   ^
d3dadapter.c:445:19: note: each undeclared identifier is reported only once for each function it appears in
d3dadapter.c: In function â€˜DRI3Present_SetCursorPosâ€™:
d3dadapter.c:467:24: error: â€˜read_posâ€™ undeclared (first use in this function)
     ok = GetCursorPos(&read_pos);
                        ^
d3dadapter.c:468:36: error: request for member â€˜xâ€™ in something not a structure or union
     if (!ok || read_pos.x != pPoint.x || read_pos.y != pPoint.y)
                                    ^
d3dadapter.c:468:62: error: request for member â€˜yâ€™ in something not a structure or union
     if (!ok || read_pos.x != pPoint.x || read_pos.y != pPoint.y)
                                                              ^
d3dadapter.c:458:11: warning: unused variable â€˜real_posâ€™ [-Wunused-variable]
     POINT real_pos;
           ^
Makefile:238: recipe for target 'd3dadapter.o' failed
make[1]: *** [d3dadapter.o] Error 1

**Comment by axeldavy** [comment]
Quite a lot of errors. Sorry, should be fixed now
